### ISSUE TITLE
compiling with mysys error 

### ISSUE THREAD

**Issue by jaiabishek** [OpenVPN/openvpn-gui#11]
D_UNICODE  -i res/openvpn-gui-res.rc -o openvpn-gui-res.o
make: D_UNICODE: Command not found
please help me with this error

**Comment by chipitsine** [comment]
should we move D_UNICODE to some *.h file ?
what is benefit of having it in command line args ?

as my 5 cents, cppcheck complains:

[main.c:94]: (style) The function '_tWinMain' is never used.
 
because, cppcheck does not see D_UNICODE ((

**Comment by jaiabishek** [comment]
the compiler doesn't recognize D_UNICODE what should i do.

**Comment by chipitsine** [comment]
can please describe your steps ?

**Comment by jaiabishek** [comment]
i am trying to compile from the new request ./configure i get this error 

![untitled](https://cloud.githubusercontent.com/assets/16611590/13256075/37090502-da6f-11e5-97c2-832212753d9e.png)

**Comment by selvanair** [comment]
Looks like pkg.m4 is not loaded. Did you run 'autoreconf -i' first? If you did, probably pkg-config is not installed.

pkg-config executable is optional as its only used to detect Openssl libs which could be manually specified. So,  we should probably just include pkg.m4 in the repo for those who do not have it..

**Comment by jaiabishek** [comment]
where should i include the pkg.m4 and can you please give me steps

**Comment by jaiabishek** [comment]
i tried to install pkg-config and recompiled from 'autoreconf -i' but still having the same issue

**Comment by selvanair** [comment]
If you have the same issue likely means autoreconf did not find pkg.m4. May be pkg-config installation is not correct?  Building from git repo is only meant for developers who are expected to have a full build environment. 

Having said that, if you know where pkg.m4 is and autoreconf cannot find it, you could do

autoreconf -if -I path-to-pkg-m4

where path-to-pkg-m4 is the directory where pkg.m4 is present -- or copy it to the current dir and use
-I ./ 

If autoreconf cant find pkg-config, configure may also not find it. If so, you have two options: (i) define OPENSSL_CRYPTO_LIBS and OPENSSL_CRYPTO_CFLAGS on the configure command line or (ii) define PKG_CONFIG and if needed PKG_CONFIG_PATH. See ./configure --help

Fixing the pkg-config installation so that the build tools can see it may be better. I don't build on windows, so no idea how to do that.

**Comment by jaiabishek** [comment]
after adding the pkg path the autoreconf was sucessful but during make i get this error, please help me out.
![untitled](https://cloud.githubusercontent.com/assets/16611590/13315783/e406f110-dbd2-11e5-98d1-17a0f8e4fb48.png)

**Comment by leobasilio** [comment]
Hi. I tried myself building with msys and indeed there's something weird about it. You should try building with [msys2](https://sourceforge.net/projects/msys2/), which is much better, in my opinion. That's also the one I use. It doesn't explain why msys won't work, but it'll get the job done.

**Comment by jaiabishek** [comment]
i have been trying with msys2 but i am not able to compile it successfully, please help me,
$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... i686-pc-msys
checking host system type... i686-pc-msys
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc option to accept ISO C99... -std=gnu99
checking for windres... windres
configure: error: This project is supported for windows only.

**Comment by leobasilio** [comment]
It seems like you're not using MinGW. Here how it looks on my computer:

> checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... **x86_64-pc-mingw64**
checking host system type... **x86_64-pc-mingw64**

Maybe you're using the wrong shell. You should use one of these, according to your system:
* MinGW-w64 Win32 Shell
* MinGW-w64 Win64 Shell

**Comment by jaiabishek** [comment]
if i am running "MinGW-w64 Win32/64 Shell" i am getting the following,
$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... i686-pc-mingw32
checking host system type... i686-pc-mingw32
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc option to accept ISO C99... -std=gnu99
checking for windres... windres
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... no, using cp -pR
checking whether make sets $(MAKE)... (cached) yes
checking for makensis... no
checking for OPENSSL_CRYPTO... no
checking for RSA_new in -lcrypto... no
configure: error: Cannot find OpenSSL library

**Comment by jaiabishek** [comment]
if any packages to be appended

**Comment by leobasilio** [comment]
So, install openssl.

pacman -S openssl

**Comment by jaiabishek** [comment]
it is already install with gcc, automake,autoconf, m4, make, perl, python.
if i am missing any of the packages.

**Comment by jaiabishek** [comment]
how to set path environment variable of openssl, makensis in Msys2?

**Comment by jaiabishek** [comment]
hi guys please help me out, i am not able to compile, i have attached my compile history, please check on it and let me know what i am missing out.
[log.txt](https://github.com/OpenVPN/openvpn-gui/files/156813/log.txt)

**Comment by selvanair** [comment]
> autoreconf -if -I /c/Users/ALT-001/Desktop/m4/

> ./configure --prefix=/ --host=x86_64-w64-mingw32 --build=x86_64-pc-linux-gnu --program-
> prefix='' OPENSSL_CRYPTO_CFLAGS="-I /c/OpenSSL-Win32/include/" OPENSSL_CRYPTO_LIBS="-L /c /OpenSSL-Win32/lib/ -lcrypto"

The fact that you need to specify m4-path to autoreconf and all those parameters to ./configure shows you have a non-standard installation. So its hard to say what is wrong.

> checking for x86_64-w64-mingw32-gcc... no

So you do not have mingw-w64 installed? Note that mingw is not the same as mingw-w64 -- the latter is required and is bundled with msys2, I believe.

> cc1.exe: error: invalid option `unicode`

Using an old compiler that does not support -municode? Probably you have multiple installs of mingw and mingw-w64 (and/or msys and msys2) and configure is picking up the wrong compiler. I do not build on windows, so can't be more specific.

**Comment by jnbdz** [comment]
I have a couple follow up questions.

On Windows 7 I am now getting these errors when I do a "make": 

![error-make](https://cloud.githubusercontent.com/assets/237008/14728690/154dd71c-0805-11e6-9403-698ad657c101.png)

So I have the same problem with unicode.

You wrote "I do not build on windows". What do you build on?

I tried to "make" on Linux Ubuntu and it did not work. I get this:

```
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc option to accept ISO C99... -std=gnu99
checking for windres... no
configure: error: This project is supported for windows only.
```

I am running out of ideas :(.

I am also using a Mac so maybe I could compile it there.

Thank you again for your time.

**Comment by selvanair** [comment]
> So I have the same problem with unicode.
You have an outdated install of mingw or msys. As suggested in that thread I had referred you to, try msys2 

I build on linux but many others build on windows using mingw/msys too. 

> checking for stdint.h... yes
> checking for unistd.h... yes
> checking minix/config.h usability... no
> checking minix/config.h presence... no
> checking for minix/config.h... no
> checking whether it is safe to define __EXTENSIONS__... yes
> checking for gcc option to accept ISO C99... -std=gnu99
> checking for windres... no
> configure: error: This project is supported for windows only.

Yes, this is a Windows program so on linux you need to cross compile for windows. If not familiar with cross-compiling check the docs in the wiki.
