### ISSUE TITLE
OpenVPN Interactive Service not started

### ISSUE THREAD

**Issue by MaxXor** [OpenVPN/openvpn-gui#111]
Hello, I'm using the latest version of OpenVPN v2.4.0 just released a few days ago. I've enabled the option "Launch on Windows startup" in OpenVPN GUI. Once I restart my computer I get the a messagebox 
> "OpenVPNInteractiveService" is not started.
> Tasks requiring administrative access may not work.

Everything is working fine though...
I checked the mentioned service and it gets automatically started. Maybe Windows is starting the GUI and service in the wrong order. Is there any way to fix?

**Comment by selvanair** [comment]
Currently there is no way to disable this check at GUI startup.
The service is supposed to start during boot so this could be a timing issue with user logging in before the service has transitioned to running state. Delaying the login by some seconds may help?

Also, as installed, the service start type is auto, make sure it has not been changed to delayed-auto.

**Comment by MaxXor** [comment]
Thanks for your reply. Yes, the start type is auto. Hm, maybe you could move the check to when you actually connect to a VPN (when pressing "Connect"). Before you don't actually interact with the service anyways?
Delaying the login is no option for me. :/

**Comment by selvanair** [comment]
I'm more inclined towards silencing it if "silent connection" option is selected in settings. Early check is required if any config is set to autostart (say "openvpn-gui.exe --connect config-name" is set to run on logon).

Is the system set to automatically logon as a user on boot?

**Comment by MaxXor** [comment]
Ah okay I understand. Yes, that would be really great!

Yes, correct Windows logs me in automatically. I don't use a password for my user account as I've encrypted the hard drive and enter a password every time I boot.

**Comment by kirillkolesnik123** [comment]
Try to log in with  administator . It had helped me.

**Comment by MaxXor** [comment]
@kirillkolesnik123 It's solved already more than one year ago.

**Comment by Acrossfy** [comment]
But it's still a thing for me. I'm logging as administrator.

**Comment by Acrossfy** [comment]
@MaxXor But it's still a thing for me. I'm logging as administrator.

**Comment by Deantwo** [comment]
@Acrossfy, then open a new issue and reference this issue.
No need to comment on a year old issue that was solved.

**Comment by Acrossfy** [comment]
@Deantwo sure, agree.
