### ISSUE TITLE
Since 2.4.0 update connecting via proxy is not working anymore

### ISSUE THREAD

**Issue by Lightah** [OpenVPN/openvpn-gui#113]
Since updating to 2.4.0 using a NTML proxy doesn't seem to work anymore. Is this a GUI or OpenVPN (configuration) issue?

OpenVPN GUI setting use proxy settings from config file

Config:
http-proxy 10.0.0.1 8080 credentials ntlm
(Also using stdin doesn't work.)

Log:
Wed Jan 04 08:48:55 2017 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jan 04 08:48:55 2017 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jan 04 08:48:55 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]10.58.243.1:8080
Wed Jan 04 08:48:55 2017 Socket Buffers: R=[8192->100000] S=[64512->100000]
Wed Jan 04 08:48:55 2017 Attempting to establish TCP connection with [AF_INET]10.0.0.1:8080 [nonblock]
Wed Jan 04 08:48:55 2017 MANAGEMENT: >STATE:1483516135,TCP_CONNECT,,,,,,
Wed Jan 04 08:48:56 2017 TCP connection established with [AF_INET]10.58.243.1:8080
Wed Jan 04 08:48:56 2017 Send to HTTP proxy: 'CONNECT example.com:443 HTTP/1.0'
Wed Jan 04 08:48:56 2017 Send to HTTP proxy: 'Host: example.com'
Wed Jan 04 08:48:56 2017 Attempting NTLM Proxy-Authorization phase 1
Wed Jan 04 08:48:56 2017 HTTP proxy returned: 'HTTP/1.1 407 Proxy Authentication Required ( Access is denied.  )'
Wed Jan 04 08:48:56 2017 Proxy requires authentication
Wed Jan 04 08:48:56 2017 HTTP proxy returned: 'Via: 1.1 Sxxxxxx'
Wed Jan 04 08:48:56 2017 HTTP proxy returned: 'Proxy-Authenticate: NTLM xxxxxxxx='
Wed Jan 04 08:48:56 2017 auth string: 'xxxxxxxx
Wed Jan 04 08:48:56 2017 Received NTLM Proxy-Authorization phase 2 response
Wed Jan 04 08:48:58 2017 recv_line: TCP port read timeout expired
Wed Jan 04 08:48:58 2017 Send to HTTP proxy: 'CONNECT example.com:443 HTTP/1.0'
Wed Jan 04 08:48:58 2017 Send to HTTP proxy: 'Host: example.com'
Wed Jan 04 08:48:58 2017 Attempting NTLM Proxy-Authorization phase 3
Wed Jan 04 08:48:58 2017 Send to HTTP proxy: 'Proxy-Authorization: NTLM xxxxxxx=='
Wed Jan 04 08:48:59 2017 HTTP proxy returned: 'HTTP/1.1 200 Connection established'
Wed Jan 04 08:49:01 2017 TCP_CLIENT link local: (not bound)
Wed Jan 04 08:49:01 2017 TCP_CLIENT link remote: [AF_INET]10.0.0.1:8080
Wed Jan 04 08:49:01 2017 Server poll timeout, restarting

**Comment by selvanair** [comment]
> Config:
> http-proxy 10.0.0.1 8080 credentials ntlm
> (Also using stdin doesn't work.)

If "credentials" is the file containing the credentials, the authentication is directly done by openvpn by reading that file -- the GUI will not prompt. When starting openvpn from the GUI, stdin will not work as there is no way of prompting from stdin in that case. Try either (i) use 'auto' instead of credentials in which case the GUI should prompt for authentication or (ii) run from command line with stdin instead of credentials. If either of those works it may be something wrong in the credentials file or openvpn itself.

**Comment by Lightah** [comment]
Thank you. Yes that's the credentials file indeed.

I think the problem is OpenVPN itself. Up to 2.3.14 it works without issues.
With 2.4.0 none of the ntlm proxies I tried work anymore. Normal proxies do work.

**Comment by cron2** [comment]
Hi,

On Mon, Jan 30, 2017 at 06:04:37AM -0800, Lightah wrote:
> Closed #113.

Uh, why?  Did you find a workaround?

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by Lightah** [comment]
I'm assuming it's not GUI related.

My current workaround is running a cntlm local proxy which forwards to the real proxy. This way I don't have to use the OpenVPN ntlm feature.

**Comment by AthosXtreme** [comment]
Almost the same log here using OpenVPN Client 2.4.6.
I sniffed the traffic and comparing with browser packets (working correctly), I find the following difference after phase 3 message (user details edited for security):

**BROWSER HTTP REQUEST PACKET:**
_Wireshark_
![image](https://user-images.githubusercontent.com/1511711/46318858-4953a500-c5ae-11e8-9472-bd864a68a502.png)
_Hex Dump_
![image](https://user-images.githubusercontent.com/1511711/46318969-afd8c300-c5ae-11e8-8db2-7e7c64620d96.png)

**OPENVPN CLIENT HTTP REQUEST PACKET:**
_Wireshark_
![image](https://user-images.githubusercontent.com/1511711/46319062-0e05a600-c5af-11e8-8277-00f576703d3f.png)
_Hex Dump_
![image](https://user-images.githubusercontent.com/1511711/46319081-1b229500-c5af-11e8-81e9-826def76c525.png)

Prior to this scenario I had to recompile client to change "TlRMTVNTUAABAAAAAgIAAA==" Proxy-Authorization header string  (NTLMSSP signature) for "TlRMTVNTUAABAAAAB4IIogAAAAAAAAAAAAAAAAAAAAAFASgKAAAADw==" (in ntlm.c).

Hope this helps to correct NTLM soon.
