### ISSUE TITLE
Write in an UV variable the status of the "save password" box.

### ISSUE THREAD

**Issue by serge16** [OpenVPN/openvpn-gui#120]
In my organization we do not want the user to be able to save his password because we are never very sure of his environment. For example, who has access to his machine and what happens if he loses it or if someone steals it. In these cases it is easy to open the GUI to have directly access to the network of the establishment. This is why we want the connection to be made only if a secret (password) has been explicitly provided.
The disable-save-passwords option or scripts that remove the auth-data key are fine but a user can quite easily bypass this.
For me the best and simple solution would be for the server to know if the "save password" box has been checked and accept or decline the connection according to its state.
It seems to me that this information could go back to the server via a variable UV_ .… usable with peer-info
Is this implementation feasible?

**Comment by chipitsine** [comment]
well, there are actually other options to consider:

1) usb tokens (supported by openvpn)
2) 2FA (second factor auth)

**Comment by cron2** [comment]
Hi,

On Thu, Jan 12, 2017 at 02:23:29AM -0800, serge16 wrote:
> It seems to me that this information could go back to the server via a variable UV_ .??? usable with peer-info

If you do not trust that your users are doing the right thing, you can't
trust user-provided variables either...

> Is this implementation feasible?

Not really.  If you want to secure yourself against stealing of a laptop
with credentials on it, use two-factor-authentication, like Yubikeys.

gert

-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by serge16** [comment]
Thank you for this quick answer.
Unfortunately this does not solve the problem.
On the one hand it is not possible to use USB token because the user should have in addition this material all the time with him.
On the other hand, we already use double-factor authentication. Each machine has a certificate that identifies the machine and the password is the 2nd factor that confirms that it is the user because he knows the secret. But that does not change the problem. If you have the machine in hand, and the password is saved, you can connect without knowing the secret.
It is for this reason that I think it is up to the server to decide whether the connection is conforms to the desired security policy. And it seems to me that the use of UV variables is really very simple. No cost, no additional user constraints.

Serge

**Comment by serge16** [comment]
Sorry, I wanted to say IV variable, not UV

**Comment by cron2** [comment]
Hi,

On Thu, Jan 12, 2017 at 03:00:58AM -0800, serge16 wrote:
> It is for this reason that I think it is up to the server to decide whether the connection is conforms to the desired security policy. And it seems to me that the use of UV variables is really very simple. No cost, no additional user constraints.

Every user can add "setenv UV_passwordsave=off" to his config, and still
click on "save password".

Is that what you want?

You can not trust information coming from client PCs that are used by 
users that do not want to follow corporate guidelines - at least not
unless you can ensure that the users never run software or configs
not approved by the admins.

In which case you can just compile your own openvpn gui that does not
do password saving at all, and signals that in a special version string
(and you disallow usage of "standard openvpn").

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by cron2** [comment]
Hi,

On Thu, Jan 12, 2017 at 03:05:23AM -0800, serge16 wrote:
> Sorry, I wanted to say IV variable, not UV

IV cannot be set from the command line, so GUI cannot set it (and
openvpn.exe does not know what settings are active in the GUI).

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by mattock** [comment]
@serge16 : if the "what happens if he loses it or if someone steals it" is the main issue, I would suggest full-disk encryption. That solves the problem way more elegantly than meddling with settings of <n> different applications.

**Comment by serge16** [comment]
I do not want the GUI to set a variable IV, I would like openvpn to set a variable IV as it does for example with variable IV_UI_VER.
It seems to me, according to issue # 117, that you are going to add in a next release for windows the registry key disable_saved_passwords. What would be interesting is that openvpn return a variable of the type IV_DISABLE_SAVED_PASSWORD that would contain the value of the key and that the server could process in a connect-script.
This does not depend off the user but on the openvpn software only. And so we can trust him. 

Serge

**Comment by cron2** [comment]
Hi,

On Thu, Jan 12, 2017 at 04:16:16AM -0800, serge16 wrote:
>  I do not want the GUI to set a variable IV, I would like openvpn to set a variable IV as it does for example with variable IV_UI_VER.

openvpn.exe does not know the GUI settings, whether or not the GUI is
saving the password, or what is in the registry.  All the windows and
user interaction bits are handled by the GUI process.

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by serge16** [comment]
> openvpn.exe does not know the GUI settings, whether or not the GUI is saving the password, or what is in the registry. All the windows and user interaction bits are handled by the GUI process.

yes, but openvpn kwown registry and the disable_saved_password key will be in openvpn keys not GUI. that's correct ?
Serge

**Comment by cron2** [comment]
Hi,

On Thu, Jan 12, 2017 at 05:16:37AM -0800, serge16 wrote:
> > openvpn.exe does not know the GUI settings, whether or not the GUI is saving the password, or what is in the registry. All the windows and user interaction bits are handled by the GUI process.
> 
> yes, but openvpn kwown registry and the disable_saved_password key will be in openvpn keys not GUI. that's correct ?

No.  "openvpn.exe does not know... what is in the registry", exactly
as I wrote above.

gert

-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by serge16** [comment]
Ok, from source code I understand GUI call openVPN like that :

sntprintf_0(cmdline, _T("openvpn --log%s \"%s\" --config \"%s\" "
        "--setenv IV_GUI_VER \"%S\" --service %s 0 --auth-retry interact "
        "--management %S %hd stdin --management-query-passwords %s"

If this is the case, it is possible to add --setenv IV_DISABLED_SAVED_PASSWORDS value where value is the value of the disable_saved_passwords key (and GUI knowns it)
Serge

**Comment by selvanair** [comment]
On Thu, Jan 12, 2017 at 10:00 AM, serge16 <notifications@github.com> wrote:

> sntprintf_0(cmdline, _T("openvpn --log%s "%s" --config "%s" "
> "--setenv IV_GUI_VER "%S" --service %s 0 --auth-retry interact "
> "--management %S %hd stdin --management-query-passwords %s"
>
> If this is the case, it is possible to add --setenv
> IV_DISABLED_SAVED_PASSWORDS value where value is the value of the
> disable_saved_passwords key (and GUI knowns it)
>

I fail to understand your conundrum.. Does the user have admin access to
the client machine? If so, he can send anything to the server -- you
wouldn't even know whether he is using a custom compiled GUI and openvpn or
entirely something else that speaks openvpn protocol. He can also take the
certificate key, remove the password and save it back. Or upload the key to
the system store and then use it without having to provide password.

If he doesn't have admin access the proposed registry key will ensure that
password is not saved if he uses the official GUI. Only users with admin
access can change that key. If he uses something else we cannot guarantee
even that. Use some form of two-factor auth for extra security.

That said if someone has physical access to a machine there are ways to get
admin access. I can understand user's will be tempted to click "save
password" if an easy to choose option is available. But if you cant trust
users not to tinker with registry setting when told not to, you have a
bigger problem.

Selva

**Comment by cron2** [comment]
Hi,

On Thu, Jan 12, 2017 at 07:00:10AM -0800, serge16 wrote:
> Ok, from source code I understand GUI call openVPN like that :
> 
> sntprintf_0(cmdline, _T("openvpn --log%s \"%s\" --config \"%s\" "
>         "--setenv IV_GUI_VER \"%S\" --service %s 0 --auth-retry interact "
>         "--management %S %hd stdin --management-query-passwords %s"
> 
> If this is the case, it is possible to add --setenv IV_DISABLED_SAVED_PASSWORDS value where value is the value of the disable_saved_passwords key (and GUI knowns it)

IV_ values are not command-line settable (except for IV_GUI_VER).

gert

-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by serge16** [comment]
Le 12/01/2017 à 16:31, Selva Nair a écrit :
> On Thu, Jan 12, 2017 at 10:00 AM, serge16 <notifications@github.com> 
> wrote:
>
> > sntprintf_0(cmdline, _T("openvpn --log%s "%s" --config "%s" "
> > "--setenv IV_GUI_VER "%S" --service %s 0 --auth-retry interact "
> > "--management %S %hd stdin --management-query-passwords %s"
> >
> > If this is the case, it is possible to add --setenv
> > IV_DISABLED_SAVED_PASSWORDS value where value is the value of the
> > disable_saved_passwords key (and GUI knowns it)
> >
>
> I fail to understand your conundrum.. Does the user have admin access to
> the client machine? If so, he can send anything to the server -- you
> wouldn't even know whether he is using a custom compiled GUI and 
> openvpn or
> entirely something else that speaks openvpn protocol. He can also take the
> certificate key, remove the password and save it back. Or upload the 
> key to
> the system store and then use it without having to provide password.

For various reasons the users are adminsitrators. I'm not trying to 
combat the risk that users recompile openvpn. Very few are able to do 
this and the probability that this happens is really very low and near 
zero. On the other hand, in my environment, some are able to deletea 
registry key and communicate the trick to others, without necessarily 
realizing the consequences and thus weakening the principles of 
security. There are various other constraints that I would not explain here.

>
> If he doesn't have admin access the proposed registry key will ensure that
> password is not saved if he uses the official GUI. Only users with admin
> access can change that key. If he uses something else we cannot guarantee
> even that. Use some form of two-factor auth for extra security.
>
> That said if someone has physical access to a machine there are ways 
> to get
> admin access. I can understand user's will be tempted to click "save
> password" if an easy to choose option is available. But if you cant trust
> users not to tinker with registry setting when told not to, you have a
> bigger problem.

It is well known that security does not depend solely on trust in users 
but in procedures that locks when things derive from the desired 
situation. I think a lot of people have this type of problem, and that's 
actually a big problem. Hence my request that will minimize the risks.

But the question is : why refuse the VPN server the opportunity to check 
certain elements of the client configuration when possible, and 
especially if it is simple. A variable like IV_DISABLE_SAVED_PASSWORD is 
much more useful and relevant than a variable like IV_GUI_VER, which in 
my eyes is very far from having the utility of 
IV_DISABLE_SAVED_PASSWORD, and yet is there.

It is the principle of Network Access Protection (NAP) that verify that 
the machine complies with the policy. In that case we do not care about 
the confidence we have in users, we have a control tool.
I'm not asking that OpenVPN turn into NAP but just add the ability to 
check the password situation (unless I'm told it's really complicated).


Serge


>

**Comment by chipitsine** [comment]
if you are talking abount Microsoft NAP, it is deprecated in windows 2012R2 and removed from Windows 2016

**Comment by chipitsine** [comment]
If you are familiar with NAP, you may also have heard of AppLocker, so you may compile your own openvpn-gui.exe and prohibit running original gui.

**Comment by selvanair** [comment]
> But the question is : why refuse the VPN server the opportunity to check
> certain elements of the client configuration when possible, and
> especially if it is simple. A variable like IV_DISABLE_SAVED_PASSWORD is
> much more useful and relevant than a variable like IV_GUI_VER, which in
> my eyes is very far from having the utility of
> IV_DISABLE_SAVED_PASSWORD, and yet is there.

Ok, suppose we implement this: have openvpn.exe itself check whether the registry key is set to disable password save and pass IV_DISABLE_SAVED_PASSWORD to the server. What good does it do? Consider this

- User unsets disable_save_password key and thus saves passwords --> server refuses to authenticate.

- Then someone gets into users machine with user logged in and steals the saved (encrypted) password blob, uses a hacked version of openvpn  and/or GUI and connects successfully. 

Works if the machine can be accessed by third parties when the user is logged in. So this offers no security.

If the user has admin access the simplest thing they can do to circumvent password prompt is to edit the config to use cryptoapicert and load the key and cert to the Windows cert store. No more password prompts. The setting of IV_DISABLE_PASSWORD_SAVE  will not mean anything.

Why stop at one particular setting on the client --- we can send a hash of the whole config file + registry settings to the server. But it provides no security: anyone can generate the hash of the original settings, edit the config or registry and still send the original hash to the server.

>It is the principle of Network Access Protection (NAP) that verify that the machine complies with the policy. 

If user has admin access how can NAP or AppLocker be useful? Your particular user may not be able to recompile the GUI but someone who gets hold of the machine when user leaves it logged in would be. 

You need to implement some kind of challenge response.

**Comment by serge16** [comment]
Hi,

Le 12/01/2017 à 18:30, Selva Nair a écrit :
>
> Ok, suppose we implement this: have openvpn.exe itself check whether 
> the registry key is set to disable password save and pass 
> IV_DISABLE_SAVED_PASSWORD to the server. What good does it do? 
> Consider this
>
>  *
>
>     User unsets disable_save_password key and thus saves passwords -->
>     server refuses to authenticate.
>
Yes, and the server can lock the account until the administrator 
analyzesthe situation.

>  *
>
>
>  *
>
>     Then someone gets into users machine with user logged in and
>     steals the saved (encrypted) password blob, uses a hacked version
>     of openvpn and/or GUI and connects successfully.
>
Precisely not, since the account is locked. The hacker can do what he 
wants he will not be able to connect without knowing the password and 
also because the account is locked. On the other hand, if the password 
is saved, there is no need to be a super hacker to activate the VPN 
connection.

 From the moment that we consider that the user himself will not 
recompile OpenVPN, the state of disable_saved_passwords is useful 
information. Not only in case the user makes a modification but also in 
case of incorrect configuration during the installation. Rather than 
leaving a risk machine in the wild, the server immediately has the 
opportunity to inform the administrator that something is wrong.
That's why I believe a variable like IV_DISABLE_SAVED-PASSWORD is 
relevant and it will give interesting information.
If you think otherwise, why does the variable IV_HWADDR exists in 
OpenVpn? The MAC address is not a very reliable information. And yet it 
can be useful crossed with other elements. You only need to know the 
limits. The administrators know what they are doing, they know the 
terrain, they know the users and their profile.
When you have introducethe "save password" box you have given the user 
to go very simply against the local security policy. You will introduce 
disable_saved_passwords and this is fine but if this info could go back 
to the server it would be even better. And once again we know what we 
are doing, we have considered the cases and the sub-cases that you 
quote, but in the end, more information = more security.

Serge

**Comment by chipitsine** [comment]
if I were a hacker, I would replace the binary, so it would have been mimic "password save disabled". you can trust users, but can you trust hackers ?

**Comment by selvanair** [comment]
By the way the user gave up on regedit and googled to find this:

openssl rsa -in myvpn.key -out myvpn.key

Typed in the password once and lived in bliss thereafter.

We all wish we can have an IV_XXX_USER_BEHAVIOUR_DETECTED pushed to every server. As a user I wish the opposite too -- IV_XXX_ADMIN_BEHAVIOUR_...

**Comment by mattock** [comment]
Basically you want to monitor generic things like the value of a registry key or a cryptographic hash of an executable. Doing this through OpenVPN and IV_* variables would (kind of) solve the problem for OpenVPN, but not for any other apps that might allow password saving. Adding such functionality would also bloat the codebase of both OpenVPN and OpenVPN GUI. Why not just enforce and monitor the local security policy using more generic tools?

As OpenVPN GUI will get a option to disable password saving, the problem will soon solved for the "user is not admin" case. For the "user is admin" there's nothing we can do that can't be circumvented one way or the other, as discussed above.

If you're concerned about passwords getting stolen along with a laptop, just use full-disk encryption. The remaining problem is to ensure that the desktop gets locked after a few minutes of inactivity, so that the thief won't be able to access any files on the computer.

**Comment by Deantwo** [comment]
Once #117 is merged, this will be a none issue unless your users explicitly goes against cooperate policy.

There is already a million ways for a user to save their OpenVPN secret (password) on the computer: 

- Writing it on a postit
- Writing it in a .txt file
- Including it in the .ovpn config file (see [`--auth-user-pass [up]` in the manual](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage))
- 3rd-party applications that override login prompts
- And so on...

The best you can do to prevent misuse of a stolen computer that may have a saved password on it, is to change the user's OpenVPN password on the server.
