### ISSUE TITLE
Problem with domain-user and "%USERPROFILE%\OpenVPN\config" folder

### ISSUE THREAD

**Issue by walx666** [OpenVPN/openvpn-gui#122]
It is not possible to use the "%USERPROFILE%\OpenVPN\config" folder for openvpn, if the user/computer is a member of a domain. But if the config is stored in the Program-Folder everything is ok.

![image](https://cloud.githubusercontent.com/assets/25054727/21899174/9e6cc5ec-d8ef-11e6-8cad-d0f7d191884f.png)

Following Errors in EventLog:
--------------------------------------------------------------------------------
openvpnserv error: 
0x20000001
You have specified a config file location (xxxxxxx_VPN1.ovpn relative to C:\Users\alexander.weber\OpenVPN\config) that requires admin approval. This error may be avoided by adding your account to the "OpenVPN Administrators" group 
--------------------------------------------------------------------------------
openvpnserv error: Der Benutzername konnte nicht gefunden werden. (0x8ad)
NetUserGetLocalGroups
--------------------------------------------------------------------------------

But I allready added the user to the "OpenVPN Administrators" group. A Test with a local user
does not have a problem.

PS:
Tested on Windows 7 X64 Pro

**Comment by selvanair** [comment]
This is a known issue: See https://community.openvpn.net/openvpn/ticket/810 for more details.

comment:16 at the above link has links to test executables that fixes this except for nested group memberships. A fix for the latter case is in the works.

**Comment by amyers2301** [comment]
The ticket linked here has been closed but as of today (June 9, 2017) we're still seeing this issue with the latest 2.4.2-I601 installer.

**Comment by selvanair** [comment]
As discussed in  https://community.openvpn.net/openvpn/ticket/810 group membership check is now supposed to work for domain users. For domain users, make sure the user is a local administrator or is in a localgroup named "OpenVPN Administrators" -- the GUI should prompt to add the user to this group if it doesn't exit. 

If it still doesn't work, please provide logs/screenshots.

**Comment by amyers2301** [comment]
Well, I can only get this happening on one system. Others aren't showing this behavior. I have a feeling it must be something else going on. Sorry for the headache.

**Comment by jupsoleil** [comment]
This issue really is fixed.
