### ISSUE TITLE
Password Caching on multiple http-proxies 

### ISSUE THREAD

**Issue by appunnicer13** [OpenVPN/openvpn-gui#127]
I use openVPN GUI in my windows 10 computer. There is a problem with it, I am trying to use multiple HTTP proxies using connection tags , our connections are limited by TCP 80 , 443 ports so I used same remote host for all my connections , then i had 5 -6 http proxies through which i wanted the OPENVPN to iterate, but the problem is that it is not iterating the credentials as well while iterating the connection . HTTP proxy Credentials are somehow cached and not iterated through. . I believe that this is not an intended behaviour and caused while trying to Cache Credentials of the openvpn-gui .

https://drive.google.com/file/d/0BwlvQ0O2HFzzVUVZYjZSQ05FY3pnb0U0VUNrUUpLTnN5bG1J/view?usp=sharing here is the typical config.

**Comment by appunnicer13** [comment]
This is a GUI problem I guess because , access server is not remembering proxies , they are cached locally . The problem is that , it doesn't load multiple password files , each proxy has each file . And every time one proxy fails , now i have to change the order of proxies so that the proxy i want comes first in the list. And further iterations on connect attempts uses same username password

**Comment by selvanair** [comment]
Currently the GUI does not save the proxy password (not yet implemented) so what you see is not due to the GUI. Likely its openvpn core that is caching the password. You may want to open a ticket in openvpn trac (https://community.openvpn.net/openvpn/newticket).

**Comment by appunnicer13** [comment]
I am opening a ticket there.

**Comment by selvanair** [comment]
Not GUI-related. Discussion moved to [Trac # 836](https://community.openvpn.net/openvpn/ticket/836)
