### ISSUE TITLE
Change Password option lost with 2.4.0

### ISSUE THREAD

**Issue by aehrlich** [OpenVPN/openvpn-gui#134]
OpenVPN GUI bundled with pre-2.4.0 version of OpenVPN (e.g. GUI v10) has the option in context menu to set/change password of the private key. The one with OpenVPN 2.4.0 (GUI v11.4.0.0) does not have this option anymore, although it properly prompts for password of encrypted private keys.
Can the "Change Password" option be restored please?

**Comment by selvanair** [comment]
Change password option is now shown only if that action can potentially succeed: (i) the private key file is writable by the user and (ii) the private key is not inlined. In 2.3 this was not checked but (i) was almost always true as most users started the GUI as admin, not so in 2.4. Changing password with inline keys is not supported by 2.3, nor by 2.4. 

If you have config in user's profile with key files writable by the user, the change password menu should show up. Please check.

**Comment by aehrlich** [comment]
Even if running as member of Administrators group there is no password change option; not even if starting GUI with privilege elevation; not even when permissions for file modification is granted to Users.
BUT the (only available) key is stored in C:\Program Files\OpenVPN\config (the "old legacy way"), not somewhere in the user-profile. Maybe this is the reason - checks and decisions made differently for this "generic" location?

**Comment by selvanair** [comment]
Are you running a custom build where password change is disabled?

Otherwise, password change should work even if key is in the global config directory provided the user has right access to the key file. Although the key write access check is new, the way key file is identified is still the same legacy code which has many limitations --- only the first instance of key or pkcs12 entry in the config file is checked, options in the form --key, --pkcs12 will not work etc.

To make sure the feature is not disabled at build time check whether the change password menu shows up if you copy the config and dependent files to OpenVPN\config in user profile.
 
If still unresolved please file a bug report in Trac: https://community.openvpn.net/openvpn/newticket

**Comment by rajanshrivastav** [comment]
Hi,
I'm new to OpenVPN. I've recently purchased a license of 10 users. I'm running OpenVPN Version -2.6.1, on centos 7.
Now, Once I've created username & password for the clients, I'm not seeing any option to let them change their password on first time login , or users can change their password on their own.
Is there any way, where users can change their password without taking help from admin.
Authentication mode is set to local

Also, please suggest me any other way, where users can change their password.

Thanks,

**Comment by cron2** [comment]
Hi,

On Tue, Jul 09, 2019 at 09:58:52PM -0700, Rajan Shrivastav wrote:
> I'm new to OpenVPN. I've recently purchased a license of 10 users. I'm running OpenVPN Version -2.6.1, on centos 7.
> Now, Once I've created username & password for the clients, I'm not seeing any option to let them change their password on first time login , or users can change their password on their own.
> Is there any way, where users can change their password without taking help from admin.
> Authentication mode is set to local
> 
> Also, please suggest me any other way, where users can change their password.

Please contact OpenVPN Inc. support for these questions.

*This* is the issue tracker for the OpenVPN open source GUI, which has nothing
whatsoever to do with the commercial offerings of a similar name.

gert


-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de
