### ISSUE TITLE
ID_TXT_KEYFILE all zero? is it what we want?

### ISSUE THREAD

**Issue by Huangdong2** [OpenVPN/openvpn-gui#144]
on line \openvpn-gui\res\openvpn-gui-res-en.rc(115 and line 116):
    LTEXT "", ID_TXT_KEYFORMAT, 0, 0, 0, 0
    LTEXT "", ID_TXT_KEYFILE, 0, 0, 0, 0

and in
 \openvpn-gui\passphrase.c(162):  GetDlgItemText(hwndDlg, ID_TXT_KEYFILE, keyfile, _countof(keyfile) - 1);
 \openvpn-gui\passphrase.c(266):  GetDlgItemText(hwndDlg, ID_TXT_KEYFILE, keyfile, _countof(keyfile) - 1);
\openvpn-2.4.0\openvpn-gui\passphrase.c(405):          GetDlgItemText(hwndDlg, ID_TXT_KEYFILE, keyfile, _countof(keyfile) - 1);
 \openvpn-gui\passphrase.c(699):  SetDlgItemText(hwndChangePSW, ID_TXT_KEYFILE, keyfilename); 
so my question is: how can we get or set the dialog item text?

and GetDlgItemText and GetDlgItemTextW mixed, not consistant

**Comment by selvanair** [comment]
>\openvpn-gui\passphrase.c(699): SetDlgItemText(hwndChangePSW, ID_TXT_KEYFILE, keyfilename);
so my question is: how can we get or set the dialog item text?

Those items are used to pass the keyfile format and name to the change password thread and are set as above. Those are not text displayed to the user so 0,0,0,0 in the resource file is fine..

I prefer to use explicit function names with A or W (and char or wchar_t/WCHAR) but the legacy code has TCHAR and generic calls. We no longer support non-unicode builds so both resolve to the same. For new code I suggest to  be explicit about ascii and wide char calls.

**Comment by Huangdong2** [comment]
thanks for the explanation, i spent a lot of time translating the resource into vs2013 editable form, the big issue is vs2013 resource editor does not allow line concatenation, and it always puts a resource.h to replace openvpn-gui-res.h, that totally made me a mess

**Comment by selvanair** [comment]
Though it would be useful to get this compile under VS, its a lot of work to get the current resource files into a VS compliant form.The resource compiler in mingw is pretty lenient (smart?)  and allows line continuation by '\' in almost all places, preprocessor macros in strings etc.

If you manage to port the resource files please submit a PR. Other contributions are also most welcome.
