### ISSUE TITLE
[Request] Random Selection

### ISSUE THREAD

**Issue by zero77** [OpenVPN/openvpn-gui#152]
When open vpn starts theres an option to select which vpn profile to use, can you please add an additional option to automatically select a random one.

Also, if one fails can you get it to automatically try a different one, if this isn't already the case.
Thanks

**Comment by chipitsine** [comment]
You may put as many "remote" statements into ovpn file as you want.

Also, you can specify either round robin or random "remote" selection

Why do you need it on openvpn-gui level?

**Comment by zero77** [comment]
Because, it is easier and more officiant to manage all profiles from one place and also it can be easier when fixing problems instead of having to go through all the configs.

**Comment by chipitsine** [comment]
usually config is distributed by "vpn service provider" (either corporate or public).
end users do not usually edit config manually

**Comment by zero77** [comment]
I am sorry I misunderstood what you meant, and I didn’t realize this was already implemented.
Where can I find the cli options listed.

**Comment by selvanair** [comment]
What you were asking for is not currently supported. You can automatically connect one or more configs in parallel when the GUI starts, not random ones. Some users want multiple VPN tunnels active at a time, and not everyone uses multiple configs as alternatives. So allowing a random config to be started and rotating among configs etc. have to take into account different usage requirements. 

Its much easier to put multiple remotes into one config as @chipitsine pointed out. Multiple connection profiles in a single config are obviously alternatives and rotating among them is already supported by openvpn core. There are some limitations to this approach as some things such as certificate/keys have to be common among all connection profiles (I could be wrong..). I do not know how hard it would be to relax those. You can open a feature wish to allow more flexibility (https://community.openvpn.net/openvpn/newticket)
