### ISSUE TITLE
[Request] IPv4 and IPv6 DNS Support 

### ISSUE THREAD

**Issue by zero77** [OpenVPN/openvpn-gui#154]
Currently open vpn leaks your real DNS IP according to DNS leak tests like https://browserleaks.com/ip and others. 
So, can you please add the option to resolve all IPv4 and IPv6 DNS requests through the VPNs DNS instead of yours.
Thanks

**Comment by selvanair** [comment]
--block-outside-dns (see the manpage of openvpn)
