### ISSUE TITLE
OVPN file association, import instead of notepad/openvpn in terminal

### ISSUE THREAD

**Issue by fkooman** [OpenVPN/openvpn-gui#156]
It seems an OVPN file is somehow associated with OpenVPN, but probably not in the most helpful way:

1. Double click: opens it in notepad;
2. Right click: "Start OpenVPN on this config file" which launches OpenVPN in a terminal...

Would it be possible to associate it in such a way that either/and:

1. Double click is actually the "import" action (as manually with right click on OpenVPN icon, Import...)
2. Right click: add the option to "import".

Not sure if this is related, but what would also be nice is that if you download an OVPN file in your browser, it would offer to open/import it in OpenVPN right away without the need to download it first and search for it in your download folder.

**Comment by selvanair** [comment]
Hi,
On Thu, Apr 13, 2017 at 6:06 PM, François Kooman <notifications@github.com>
wrote:

> It seems an OVPN file is somehow associated with OpenVPN, but probably not
> in the most helpful way:
>
>    1. Double click: opens it in notepad;
>    2. Right click: "Start OpenVPN on this config file" which launches
>    OpenVPN in a terminal...
>
> Would it be possible to associate it in such a way that either:
>
>    1. Double click is actually the "import" action (as manually with
>    right click on OpenVPN icon, Import...)
>    2. Right click: add the option to "import".
>
> See PR 76. Let's move this discussion there so that we can improve it and
get it merged.

>
>
> Not sure if this is related, but what would also be nice is that if you
> download an OVPN file in your browser, it would offer to open/import it in
> OpenVPN
>
Something like this was the original intent of PR 76.

Selva

**Comment by mattock** [comment]
Yeah, let's move this discussion to PR https://github.com/OpenVPN/openvpn-gui/pull/76.
