### ISSUE TITLE
Update About Dialog

### ISSUE THREAD

**Issue by Peppernrino** [OpenVPN/openvpn-gui#166]
the about dialog still says copyright 2016. :)

**Comment by nilswende** [comment]
Note that it is not explicitly neccessary to update the copyright year to reflect the current year.
See for example: https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

**Comment by mattock** [comment]
I don't see the point in updating the copyright year, either. Copyright is automatic - you don't have to explicitly claim copyrights to a work. From version control logs and changelog files it is pretty clear who was the author of the change and when the change was made. So the copyright date can be deduced from that.

Moreover a work will remain copyrighted for a (imho) ridicuously long period, typically 70+ years after author's death. I doubt anyone will have any use for openvpn-gui code we create now after waiting that long 😄.

**Comment by Peppernrino** [comment]
it was more of a cosmetic issue. but thank you for letting me know it isn't explicitly necessary.
