### ISSUE TITLE
The openvpn's "--management IP port" option not working 

### ISSUE THREAD

**Issue by MiCRoPhoBIC** [OpenVPN/openvpn-gui#169]
The option "--management IP port " from OpenVPN 2.3/2.4 is not working when I'm starting the VPN connection by OpenVPN-GUI. It doesn't matter what the IP is (or the option is tunnel instead) - it looks like it simply ignores it. However if I start my config file not by running OpenVPN-GUI, but by openvpn.exe --config myconfig.ovpn the management is working fine. I tried to check 'Run as administrator' boxes and different versions of OpenVPN-GUI but it doesn't work. Tried to put verb 4 but there are no log entries with error or something about it.

**Comment by cron2** [comment]
Hi,

On Sat, Jun 03, 2017 at 10:35:36AM -0700, MiCRoPhoBIC wrote:
> The option "--management IP port " from OpenVPN 2.3/2.4 is not working 
> when I'm starting the VPN connection by OpenVPN-GUI. 

management is a single-use command, and the GUI is using the management
interface to control openvpn.exe - so nobody else can.

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by MiCRoPhoBIC** [comment]
Oh, now I get it why it is ignoring my configuration file parameter. I was not aware that this GUI is using the management and leaving no option for other usage. It's a shame, I'm forced to use very old gui hacked with PIN prompt. I was so happy that finally this GUI has user friendly support for pkcs11 insert prompt and user pin. Thank you.
