### ISSUE TITLE
better handling of auth-failure

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-gui#170]
it is very common "support case" for us

"something went wrong, I do not understand" ... "ok, show your logs" ... "auth-failure"

I suggest to add some window here 

https://github.com/OpenVPN/openvpn-gui/blob/master/openvpn.c#L238-L239

indicating "auth failure happened" or something like that (maybe it makes sense to split login/password and certificate into 3 separate cases)

**Comment by chipitsine** [comment]
maybe colour password box into red ?

**Comment by selvanair** [comment]
Sounds good, and easy to do.

**Comment by selvanair** [comment]
@chipitsine : Please check this out
https://github.com/selvanair/openvpn-gui/commit/1d5df2623a91d14397ebaa4b03d16ceb3fde959b

**Comment by chipitsine** [comment]
thank you, I'll try it very soon.

can you please, enable AppVeyor build ? it stores artefacts across builds (yes, you told me about wrong behaviour of printf under mingw)

**Comment by selvanair** [comment]
> can you please, enable AppVeyor build ? it stores artefacts across builds..

Will do...

Btw, I pushed a commit that copies the dialog changes to all lang files -- so test the latest of my feature branch "warn-auth-failure", please. https://github.com/selvanair/openvpn-gui/tree/warn-auth-failure

**Comment by chipitsine** [comment]
![issue_170](https://user-images.githubusercontent.com/2217296/26895072-2cbd69fe-4be2-11e7-8944-b4273da9c06b.png)


I think, text itself is not neccessary (and we need to translate it to all languages)
by red color I meant password input field

also, username disappeared

**Comment by chipitsine** [comment]
well, red text might be ok. People will pay attention to it, I hope.

**Comment by selvanair** [comment]
See the commit messages to see why username disappeared (in short, auth
failure means either the username or password or both are wrong -- not
erasing the username was an oversight in my original implementation of
password save feature).

I think the text is more user-friendly unless you want the users to come
back and ask why passowrd turns red.. How about doing both -- print
username and password in red and provide the status text as well?

**Comment by chipitsine** [comment]
if user makes some mistake, so let him to fix it.
I think keeping both username and password is more friendly than erasing both of them

ok, let keep the red text (we can test it on users and see how they react to it)

**Comment by chipitsine** [comment]
![issue_170_1](https://user-images.githubusercontent.com/2217296/26895592-dcff3ea4-4be3-11e7-9af6-0805eabb4b31.png)


red message is broken.

also, window caption is broken (it is too long for login/password as well), should we open a separate issue on that?

**Comment by selvanair** [comment]
> if user makes some mistake, so let him to fix it.
> I think keeping both username and password is more friendly than erasing both of them

The password must be erased after ath failure (as we already do) as its a masked text and the user has no idea what is in there.  As for username, I'm ok either way.. The message should refer to both as either could be wrong.

**Comment by chipitsine** [comment]
ok, let us keep username and erase password

**Comment by selvanair** [comment]
> also, window caption is broken (it is too long for login/password as well), should we open a separate issue on that?

Will fix this one as I'm touching it anyway.. This one is way too short, but in general, the config name is appended to the caption at run time so its hard to guess a good value for the window width in resource file. Shall we make these dialog windows resizable?

**Comment by chipitsine** [comment]
I think, we do not need to append config name to caption

**Comment by selvanair** [comment]
I added it a while back as without it its nearly impossible to know what to input  when you have multiple connections. Note that the auth/password dialogs may pop up any time..

**Comment by chipitsine** [comment]
I think, 99.9% it appears in some clear context, i.e. user starts connection ... voila ... enter username/password.

actually, it might appear during re-auth, I beleive it is very rare case. And, I do not think people usually run multiple vpn connections in the same time.

**Comment by selvanair** [comment]
> actually, it might appear during re-auth, I beleive it is very rare case. And, I do not think people usually run multiple vpn connections in the same time.

I do. And reauth is not rare. Add to that mix dynamic challenge and you get the picture.

**Comment by chipitsine** [comment]
is auth-token supposed to resolve re-auth ?

**Comment by selvanair** [comment]
Use auth-token instead of re-auth may be acceptable in some setups. In any case, these are config specific dialogs, so the config name should be there in them.

**Comment by chipitsine** [comment]
I added russian translation

https://github.com/selvanair/openvpn-gui/pull/4/commits/a434e0cb549d4e87d8d892196b404e42418eebeb

@ValdikSS  ?

**Comment by ValdikSS** [comment]
The text looks good for me. Didn't test the alignment.

**Comment by selvanair** [comment]
See PR 171

**Comment by chipitsine** [comment]
awesome :)

I built custom openvpn-gui today. our users approved UX imrovement

**Comment by chipitsine** [comment]
closed after https://github.com/OpenVPN/openvpn-gui/pull/171
