### ISSUE TITLE
connect script is not executed on reconnect

### ISSUE THREAD

**Issue by B16EC302BEFB051D45025E3342E81C** [OpenVPN/openvpn-gui#177]
i'm not sure if this is a bug or as designed. if intentional, i'd like to make a RFE to execute the connect script on reconnect.

i think modifying the following should suffice:
openvpn.c line 198:
```
/* Run Connect Script */
if (c->state == connecting || c->state == resuming || c->state == reconnecting)
    RunConnectScript(c, false);
```

**Comment by ffes** [comment]
We run into this problem as well.

We have two remotes in our .ovpn config file. When the first fails (for instance when that server/line is down), it tries the second remote. The second remote connects, but the connect script is not executed because the `|| c->state == reconnecting` is missing as mentioned above.

When I add it everything works as expected in that situation, but I don't know if it will break other situations. I gladly open a PR for this, but want to discuss any side effects before submitting.

**Comment by selvanair** [comment]
@ffes If connecting to a second remote after failed attempts with another is reported as reconnecting, it looks like a bug in OpenVPN core. The GUI sets the state to `reconnecting` in two instances: (i) on receiving a state change message from the management interface saying `RECONNECTING` (ii) when a SIGHUP restart is triggered on an active connection by clicking the reconnect menu button. I haven't looked at the relevant code in the core, though. It could help if this is reported as a bug in [trac](https://community.openvpn.net/openvpn/newticket) 

@B16EC302BEFB051D45025E3342E81C We currently run the `connect script` only when the state changes from `connecting` to `connected`. The state named `resuming` is a left over from times when we used to disconnect and reconnect during power events like sleep, which is no longer the case. Changing the logic to run the script during re-connections could affect existing installations. We could add a facility for reconnect scripts if felt necessary.

**Comment by ffes** [comment]
@selvanair I create a user account in trac and reported it as you suggested: https://community.openvpn.net/openvpn/ticket/1356

But I messed up the title of that ticket 😕 , and it seems I cannot adjust it myself

**Comment by selvanair** [comment]
Thanks. I've edited the title.

**Comment by selvanair** [comment]
After looking though openvpn sources my conclusion is that we cannot interpret the state change to RECONNECTING as an indication of a restart after a prior successful connection. But, the logic in the GUI is that `state=reconnecting` means the up-script has already run once, tray message for successful connection has been shown etc.

So, I suggest to change processing of the state change message of "RECONNECTING" in the GUI from
`c->state = reconnecting`
to
```
if (c->state == connected)
     c->state = reconnecting
```
(around line 328 in openvpn.c)
Other possible values of the state viz., "connecting" or "resuming" will not be altered.

This should fix the bug reported by @ffes  as well.

**Comment by ffes** [comment]
I have changed the code as you suggested and the first impression is that it indeed solves the problem.

I will let it run for at least the rest of the day and submit a PR any time soon.

**Comment by selvanair** [comment]
If you are submitting a PR please enclose the subsequent tray state changes as well the if clause like:
```
if (state == connected)
{
      c->state = reconnecting;
      CheckAndSetTrayIcon();
      SetDlgItemText(c->hwndStatus, ID_TXT_STATUS, LoadLocalizedString(IDS_NFO_STATE_RECONNECTING));
      SetDlgItemTextW(c->hwndStatus, ID_TXT_IP, L"");
      SetStatusWinIcon(c->hwndStatus, ID_ICO_CONNECTING);
}
```

**Comment by fabiopedrosa** [comment]
@selvanair 
> We could add a facility for reconnect scripts if felt necessary.
Could this be done?
