### ISSUE TITLE
Traffic goes out from VPN when disconnect happens

### ISSUE THREAD

**Issue by gjf** [OpenVPN/openvpn-gui#185]
Sometimes VPN server connection is not stable enough so disconnect happens.
In this case the client shows the message to reconnect providing already stored login and password and waits for the user presses "connect".
In this time when user does not see this message all traffic passes unencrypted outside VPN.

I believe the option (automatically reconnect" would solve this problem, but it is absent.

**Comment by chipitsine** [comment]
I like the way it works in SoftEtherVPN.
it reconnects (and connects) automatically unless user interrupts the connection process

**Comment by gjf** [comment]
Exactly. And also it would be good if the client has a possibility to block all other traffic rather than thru VPN.

**Comment by selvanair** [comment]
> Sometimes VPN server connection is not stable enough so disconnect happens.
In this case the client shows the message to reconnect providing already stored login and password and waits for the user presses "connect".

This should not happen. In case of network glitches openvpn core will reconnect by itself without any prompts unless you have some directives in the config (like --auth-nocache) that interferes with this process.

**Comment by gjf** [comment]
So this feature cannot be done without caching password in memory? OK, will try.

**Comment by selvanair** [comment]
If you want the GUI to automatically use the save password without showing a dialog that is currently not  supported. The assumption is that such prompts are repeated only if --auth-nocache is in use and in such cases the user probably wants to see the prompt.

But it may be a good idea to optionally suppress that prompt: say, if silent_connection is on.

**Comment by gjf** [comment]
Also it would be very nice to be sure there is no possibility to forward traffic through VPN and no way other.
For instance: automatic starting of VPN connection immediately after automatic start of client, blocking other routes etc.

**Comment by selvanair** [comment]
Requirements lik which config, if any, to start automatically or whether to send all traffic through VPN etc vary from user to user, case to case.
- To redirect all traffic through vpn use --redirect-gateway in the config
- To start a connection automatically when the GUI is launched, use --connect <config-file> command line option to the GUI. This may be set on the GUI shortcut.

As for firewalling traffic see also discussion here: #153

**Comment by selvanair** [comment]
PR #186 makes the dialog auto submit after a delay unless interrupted by the user. Should be in next release. This would take care of automatic reconnection.

Closing. Reopen if necessary.
