### ISSUE TITLE
Please produce "scramble edition" version again

### ISSUE THREAD

**Issue by gjf** [OpenVPN/openvpn-gui#189]
Is it possible to produce "scramble edition" releases again?
The last one was 2.3.10 version with such feature.

**Comment by selvanair** [comment]
Not sure what you are referring to. There are no "scramble edition" releases.

**Comment by gjf** [comment]
Please look through attached here: http://dropmefiles.com/z62RU

**Comment by selvanair** [comment]
If you are referring to a release that is not an "official" OpenVPN community edition, this is the wrong place to ask about it. Otherwise post of a link to the release.

**Comment by gjf** [comment]
I believe I found what is it. 
It is a compiled version with scramble option for users in countries where VPN is banned: China, Iran etc. 
The option could be obtained using this patch: https://github.com/clayface/openvpn_xorpatch
So the question is: does community care about users in these countries?

2018 1 24 21:54:03 UTC, Selva Nair <notifications@github.com> пишет:
>If you are referring to a release that is not an "official" OpenVPN
>community edition, this is the wrong place to ask about it. Otherwise
>post of a link to the release.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenVPN/openvpn-gui/issues/189#issuecomment-360286425

--

**Comment by mattock** [comment]
@gjf we've had discussions about obfuscation ("scrambling") support on the openvpn-devel mailing list several times in the past. We've always agreed that we do not want to start playing a cat-and-mouse game with in countries that ban VPN: we simply don't have the resources for it. Also, none of the core OpenVPN developers live in those countries, and thus don't have a personal interest in obfuscation.

So we have agreed that the cat-and-mouse game should be played by a dedicated team/project that actually has an interest in winning it. That dedicated team could produce unofficial OpenVPN installers/packages that include obfuscation patches or integrate other obfuscation tools such as obfsproxy which [can be integrated](https://community.openvpn.net/openvpn/wiki/TrafficObfuscation) with OpenVPN. So far such a team/project has not materialized.

Also, many commercial (Open)VPN providers _do_ play that game on behalf of their customers. I don't want to endorse any provider, but they are out there.
