### ISSUE TITLE
PKCS#11: Localization of token not found dialog

### ISSUE THREAD

**Issue by EugeneKin** [OpenVPN/openvpn-gui#191]
When OpenVPN-GUI starts with no token "Please insert <token label> token" dialog is shown

I found only this message hardcoded in pkcs11.c

openvpn_snprintf(
        token_resp.username,
        sizeof(token_resp.username),
        "Please insert %s token",
        token->label
);

**Comment by selvanair** [comment]
Generally we do not translate any message that comes from openvpn core. In most cases we can ignore the message and show a localized prompt based on the context. 'NEED-OK' requests like this one are special cases where the message contains relevant info (the token name in this case) and is meant to be shown to the user but arrives untranslated.

Could be handled in an adhoc way by parsing the message but I opted to leave it as is. Patches welcome.
