### ISSUE TITLE
Checkbox in the dialog saying "show user authentication dialog on startup"

### ISSUE THREAD

**Issue by AndersBillLinden** [OpenVPN/openvpn-gui#193]
I am using a vpn with a username and password. When I start the openvpn client, a dialog is coming up prompting me for my username and password (already filled in since before).

It would be great if there beside the "save password" checkbox also was a "show user authentication dialog on startup" checkbox, making it possible to start the openvpn client non interactively.

**Comment by selvanair** [comment]
Do you mean "show password dialog" or "do not show password dialog"? See PR #186 -- is that what you are asking for?

**Comment by AndersBillLinden** [comment]
I would prefer the checkbox to be affirmative, so it would initially be checked.

**Comment by AndersBillLinden** [comment]
I think "silent connection" is a bit vague, yet another setting for showing the password dialog would be the best imho.

**Comment by AndersBillLinden** [comment]
The saved password is already used (filled in) so PR 186 has a misleading title.

**Comment by kubco2** [comment]
+1 I was going to fill issue :) ... We start openvpn-gui from script, till now we used to use login.txt but it is readable in directory. So we would like to prefill login, but currently user must confirm dialog.

**Comment by selvanair** [comment]
The just merged PR #186 makes the dialog auto submit after a delay unless interrupted by the user. So, non-interactive connection is now possible if username/password are saved.
