### ISSUE TITLE
Windows: problem with log location very hard to correct

### ISSUE THREAD

**Issue by CottonEaster** [OpenVPN/openvpn-gui#203]
Windows 8.1
OpenVPN: 11.9.0.0

I deleted the folder where my log was kept. Then, upon starting the gui, I got an error about that (good) but no way to correct it or run the gui (bad). I discovered a registry setting. Changing that setting to an extant location worked. Clearing the setting, in the hope that the gui would then allow me to reset it, made the gui, when run, crash completely.

What should happen: the gui should allow a correction, or at least point one towards the reg key.
  
EDITED: a small typo or two.

**Comment by selvanair** [comment]
None of this should happen. 

If you delete the current log directory while GUI is not running, it will be recreated on next startup. If deleted while running, starting a new connection would log a warning to the status window saying that log file could not be opened but that is not a fatal error. Everything should work except that no logs will be written. On restarting the GUI it will recreate the missing log directory and should show no errors.

The only time a fatal error message will  popup is if the log directory is missing and the  GUI fails to create it (say permission denied). In that case the process will exit with an error.  One way to recover from that is to start the GUI with {{{--log_dir xxx}}} command line option where xxx is a complete path. If the path does not exist the GUI will create it. Once started go to the settings menu and make sure the log_dir is correct or change it if needed.

Avoid editing the GUI registry keys in HKCU  -- use command line options if the GUI cant start otherwise or use the settings menu if the GUI can start up but something setting like log dir needs changing.

 > Then, upon starting the gui, I got an error about that (good) but no way to correct it or run the gui (bad).

What error did you get? Was GUI started as the logged in user? Was the previous log directory in a location where GUI has no rights to create a folder?

**Comment by CottonEaster** [comment]
> What error did you get? 

The error was something along the lines of `R:\log not accessible`. 

> Was GUI started as the logged in user?

I don't know. I setup OpenVPN a long time ago. `openvpn-gui.exe` is not in any startup list that I can find, but nonetheless it runs (I am glad to say) on boot (or at least login).

> Was the previous log directory in a location where GUI has no rights to create a folder?

No, but it was on a ramdisk that I'd removed.

**Comment by selvanair** [comment]
If the previous log location is no more accessible, the worst case described above applies. To recover from it exit the GUI, open a command prompt and start the GUI with the option  
`--log_dir %USERPROFILE%\OpenVPN\log`
A new log directory will get created at that location.

Alternatively, if you prefer editing the registry, open a command prompt as user and type
`reg delete HKCU\Software\OpenVPN-GUI /v log_dir`
That will delete the registry setting and log location will revert to default. Restart the GUI. 

In either case if you want to change the log location from the default, edit it in the settings menu after the restart.

**Comment by CottonEaster** [comment]
selvanair: thanks, but perhaps I was not clear. I meant to convey (as is indeed the case) that I've recovered. I wasn't asking for technical support but instead reporting what I took to me a bug. Still, your instructions will prove useful to others (or to me if I get in this mess again).

**Comment by selvanair** [comment]
>selvanair: thanks, but perhaps I was not clear. I meant to convey (as is indeed the case) that I've recovered. 

But you wrote:

> Clearing the setting, in the hope that the gui would then allow me to reset it, made the gui, when run, crash completely.

I do not think that should happen at all and want to fix if it does. If you clear the log_dir registry value the log location will just revert to the default, the GUI should start without error, and then the new location could be checked and changed from the settings menu.

**Comment by CottonEaster** [comment]
But I wrote also that

> I discovered a registry setting. Changing that setting to an extant location worked. 

Anyhow: I've told you what happened, you've told me what should have happened, you are not asking me for any more information, and so I'll leave matters here.

**Comment by cron2** [comment]
Hi,

On Fri, Jan 05, 2018 at 11:38:57PM +0000, CottonEaster wrote:
> > I discovered a registry setting. Changing that setting to an extant location worked. 
> 
> Anyhow: I've told you what happened, you've told me what should have happened, you are not asking me for any more information, and so I'll leave matters here.

An interesting tidbit would be "which version of OpenVPN GUI exhibited
that behaviour".

The way OpenVPN GUI handles missing registry keys and defaults has changed
a bit over time, so maybe you had an old GUI versiont hat indeed crashes
on missing keys...

gert

-- 
now what should I write here...

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by CottonEaster** [comment]
Gert,

OpenVPN 2.4.4 x86_64-w64-mingw32

Is that the information you need? I find the GUI (the version of it that I have!) not helpful in displaying version information.

**Comment by selvanair** [comment]
FWIW:
The GUI version in the report is 11.9.0.0 in which all registry keys are optional.
Although the OP initially reported the GUI crashed, subsequent discussion shows it just showed an error message saying the log directory is not accessible and exited. This is the current behaviour -- if the log directory is specified in the registry and does not exist, the GUI tries to create it and if that fails it exits with an error message. There was no crash. 
We can improve that error message or forcefully reset the log-dir back to default or  show an option where the user can reset the log directory. But this is a rare incident --- how often one sets the log folder to a temporary disk and them removes it? Not a priority for me -- patches are welcome.

**Comment by cron2** [comment]
Hi,

On Sat, Jan 06, 2018 at 03:17:21PM +0000, CottonEaster wrote:
> OpenVPN 2.4.4 x86_64-w64-mingw32
> 
> Is that the information you need? I find the GUI (the version of it that I have!) not helpful in displaying version information.

Well, the actual installer used would be more helpful ("openvpn-2.4.4-I601"
or something along that lines).  We don't even know if you are using the
official GUI or something bundled by a VPN provider :-)

For 2.4.4 as shipped by us, the effect you have seen should not happen,
as Selva said...

gert

-- 
now what should I write here...

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by CottonEaster** [comment]
The installer I used: `openvpn-install-2.4.4-I601`.
