### ISSUE TITLE
Add traffic stats and other connection info to status window

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn-gui#209]
I'm adding traffic stats (bytes in/out), assigned ip (v4/v6) and GUI and daemon versions to the bottom of the status window. Any suggestions on anything else to include etc.?

**Comment by TinCanTech** [comment]
Will this work on a windows --server ? (Lots of options there) :)

**Comment by selvanair** [comment]
Client only (undefined behaviour on server :). Except that you can start the process without admin rights (as iservice will be used), starting a server through GUI is not really useful right now and it will kill the process on exit.
There is a plan to extend the GUI to allow controlling always on (already started) connections, but stalled for lack of time.. When that is ready, catering to server needs may be of interest.

**Comment by TinCanTech** [comment]
To be fair .. I was just yankin' your chain WRT --server .. 
However, regarding the --client; if all "WARNING:" log msgs could be set at a verb of 1 and therefore be included in all but the most stringent logs then the GUI could highlight those in an unmissable fashion perhaps..

**Comment by selvanair** [comment]
Warnings and errors now display in bright red

commit 23ac3c00bbe47a84a20baa9eca9d5a6284d76173
Author: Selva Nair <selva.nair@gmail.com>
Date:   Tue Sep 19 22:28:26 2017 -0400
    Highlight warning and error messages in status window
           - Change text color of log lines with flags = W, N, F

**Comment by TinCanTech** [comment]
Cutting to the chase .. 
> Any suggestions on anything else to include etc.?

a "Help" button would not go a-miss ..

**Comment by selvanair** [comment]
Provide some helpful content for help, we shall have a button.
Anyway, the question was about adding one or two connection/stat lines to the status window.

**Comment by chipitsine** [comment]
As for "helpful content", I consider it as a bad design.

Proper help is somewhat context related.

Like we can set up a relationship between client profiles. If first connection fail, openvpn-gui will suggest to try second profile.

" help" buttons suck

**Comment by chipitsine** [comment]
Can we consider statistics from VPN provider like privatetunnel or airvpn? Bytes + billing information?

That way openvpn-gui might cover generic VPN provider usage as well

**Comment by mattock** [comment]
@chipitsine I think integrating OpenVPN GUI with proprietary data like billing information would require connecting to proprietary APIs of the VPN service providers. Or manual entering of data (e.g. amount of bytes left in current data package) by the user. We could have "VPN provider profiles" that are in the Git repository, but those would have to be updated constantly to reflect changes in pricing models of the VPN providers. I'm pretty sure this would get pretty messy very fast and/or have to limited to just a few VPN providers with public APIs available. The VPN providers also love to create their own GUIs, which I believe tend to have this info already.

As for UI/UX. I do agree that we should aim at having an UI that does not require help pages for basic usage. That said, actually having documentation that we can link to (e.g. via Help menu) is never a bad idea. We have some pages in Trac and README.md at the root of this repository, but that's about it I believe.

**Comment by chipitsine** [comment]
@mattock - as for Trac or README, I think "Help" is somewhat related to vpn server, i.e. "call that phone number", for example, and guide a user to proper support service

as for billing information - Selva asked "what kind of information should we also include", I answered that question.

from user's point of view, connecting to corporate VPN, public VPN, etc - are somewhat similar. I understand that it might be tricky to achive. So, I'd start with publically avaiable API, like that one

https://github.com/Tunnelblick/Tunnelblick/issues/403

(or privatetunnel, maybe)

for the rest of VPN providers, I think we can discuss the idea of using openvpn-gui in their services instead of proprietary GUI. they might be interested in that as well

**Comment by mattock** [comment]
@chipitsine hmm, on a second though VPN provider integration could be beneficial **if** we can migrate some VPN providers over from their home-grown Windows VPN client to OpenVPN GUI. That would mean they would (have to) participate in OpenVPN GUI development.

That said, at least in our (privatetunnel.com) case we want / have wanted to achieve a unified user experience across all platforms (Windows, Mac, Android, iOS). This is, for us, one reason not to use OpenVPN GUI on Windows. Some of the smaller VPN providers with lesser resources might be interested in participating in this kind of effort, though.

I would first contact some VPN providers first and see if they're interested. The carrot to wave at them is "less maintenance overhead for you". At our end the "compromise" would be some level of generic VPN service provider data integration. If VPN providers are not interested I would just leave things as they are.

@selvanair @cron2 does OpenVPN 2 core allow passing free-form data such as "amount of data left in data package" to the client? Something that OpenVPN GUI could process if present.

**Comment by chipitsine** [comment]
@mattock - I understand the reasoning to have unified user experience across all platforms (for privatetunnel). on the other hand, user have to use different UI if he connects to both privatetunnel and some corporate vpn. It needs to be investigated what is better from user's point of view.

yeah, if some vpn providers will migrate to openvpn-gui, they will invest into openvpn-gui development as well :)

**Comment by cron2** [comment]
Hi,

On Mon, Jan 29, 2018 at 08:10:08AM +0000, Samuli Seppänen wrote:
> @selvanair @cron2 does OpenVPN 2 core allow passing free-form data such as "amount of data left in data package" to the client? Something that OpenVPN GUI could process if present.

push "echo ..."

as far as I understand everything after the "echo" is transported as-is
to the management interface - we'd "just" need to agree on the specific
format.

gert

-- 
now what should I write here...

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by selvanair** [comment]
"echo .." could be used for transferring provider specific info like billing rates etc. But its not going to be I who implements provider-specific stuff into the GUI. I only care about free services and work-place VPNs :) But if we can get some providers to directly participate in development, do review work, that would be a great.

As per private-tunnel docs, it looks possible to connect using the community GUI -- some features like billing info will not be available, but the connection should work. The docs  ask to run the GUI as admin, which I do not like at all... (https://support.privatetunnel.com/kb/article/15-how-do-i-use-the-windows-community-client-to-connect-to-privatetunnel/). Can we get that updated or is there a reason why iservice is not usable for privatetunnel?

**Comment by cron2** [comment]
Hi,

On Mon, Jan 29, 2018 at 08:03:35AM -0800, Selva Nair wrote:
> As per private-tunnel docs, it looks possible to connect using the community GUI -- some features like billing info will not be available, but the connection should work. The docs  ask to run the GUI as admin, which I do not like at all... (https://support.privatetunnel.com/kb/article/15-how-do-i-use-the-windows-community-client-to-connect-to-privatetunnel/). Can we get that updated or is there a reason why iservice is not usable for privatetunnel?

That sounds like a leftover from the past - "OpenVPN Connect" for windows
always had their own service for this...

gert

-- 
now what should I write here...

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by mattock** [comment]
@selvanair for me the gist of provider info in OpenVPN-GUI is to get providers participating in OpenVPN-GUI development. If that fails then I think we should just drop the whole idea. Having a demo of the feature would help get VPN providers interested, though. Perhaps that demo could be done by somebody (else) in the community who has an interest in it.

Another thing the providers will probably want is some sort of theming support - is theming possible / easy at the moment?

As for Private Tunnel: I have never used the official clients except for a few times for testing. I connect to PT from Linux using OpenVPN 2 via console or through systemd. Works fine. I will notify the guys about the obsolete information on the page you [linked to](https://support.privatetunnel.com/kb/article/15-how-do-i-use-the-windows-community-client-to-connect-to-privatetunnel/).

**Comment by chipitsine** [comment]
theming is crap. from user's point of view it is best when single UI is used to connect to both corporate and public vpn. if it is get themed, people will get confused with that.

but,I consider theming if (and only if) people tend to use either corporate or public vpn (not both of them)

**Comment by mattock** [comment]
@chipitsine I agree. But I also *believe* that most of the people who use commercial VPN providers do not use any other VPN connections. I can ask the PT guys to see if they have an idea about this.

I also think that branding is very important for many (big?) VPN providers who try to differentiate themselves from the dozens of others who provide essentially the same service. If we can provide some theming/branding support I believe we're much more likely to get some VPN providers to drop their in-house clients and join OpenVPN-GUI development.

In any case we should try to contact VPN providers and see where that leads. Any suggestions where to start from? I know that Private Tunnel can be ruled out.

**Comment by chipitsine** [comment]
@mattock : I think good time to call for VPN providers is some public announce. I.e. "Hey, openvpn-2.4.5 is released with ..... also, if you are reading this, and you are VPN provider, we want to tell you the following...."


but it might be separate public announce as well

I agree, if there'll be no interest, we will drop the idea

**Comment by selvanair** [comment]
This started as showing bytes in/out in the status window (implemented) and side-tracked into branding and billing requirements of phantom commercial providers. Closing as completed.
