### ISSUE TITLE
1Tap Connect

### ISSUE THREAD

**Issue by xmha97** [OpenVPN/openvpn-gui#215]
I suggest add this feature:
Connect to last server by one click on system tray icon

**Comment by selvanair** [comment]
As right click is linked to opening the popup menu this will have to be wired to left click which could take many users by surprise as left-click is the most common action. That leaves left-button double-click, which currently starts the connection (or shows the status window) if only one connection is found (or active).

What we could do is to extend the left-button double-click behaviour to start the last successful connection if none are active or show the status window of latest connection if multiple connections are active. Would that be useful?

A related feature of interest would be to remember active connections on exit and restart them automatically during next startup. Currently we just warn about existing connections before killing them at exit.

**Comment by mattock** [comment]
I think it would make sense to reconnect (on login) to VPNs that were active when the user logged out. It would make OpenVPN-GUI work like on-demand/login service. This would work as long as a VPN connection is not needed for system login. @mhd4mr would that suit your use-case?

One gotcha is in handling connections that failed due to external reasons. For example, if the user moves to a network where ISP/corporation prevents outbound VPN connections. I think we should track the *intent* of the user when determining which connection was active at logout.

**Comment by chipitsine** [comment]
there's already "automatic start" feature. do you mean also "automatic connect" ?

**Comment by mattock** [comment]
Yes, I think that is the idea. Not just start the OpenVPN-GUI application, but also automatically launch VPN connections that were active when the user logged out the last time.

**Comment by selvanair** [comment]
Precisely. If the user logs out, or just exits the GUI with active connections, we bring them back on during the next startup of the GUI. Irrespective of whether its autostarted at logon or manually started.  If the user explicitly disconnects a connection before exit then its not restarted. Something like a browser offering to restore previous tabs but  without any unnecessary prompts.

We can do better: if the GUI is running at logout automatically restart it next time even if auto-launch-at-logon is not enabled. If the user quits the GUI before logout the auto-start setting will get used as usual. I recall Jonathan mentioning that tunnelblick does this.
 
Not sure what to do if the user has moved to a new network. We can have an option to disable this feature altogether (or on a per config basis ?). Just restarting GUI if it was running at logout should be still ok.
