### ISSUE TITLE
connection dependency ?

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-gui#222]
hi,

I came to an idea that we can add some connection as a redundant (backup) connection.

i.e. "connection to conf1 failed ... try connection to conf2 ?" and so on.

**Comment by selvanair** [comment]
Hi,

On Tue, Feb 20, 2018 at 11:16 PM, Ilya Shipitsin <notifications@github.com>
wrote:

> hi,
>
> I came to an idea that we can add some connection as a redundant (backup)
> connection.
>
> i.e. "connection to conf1 failed ... try connection to conf2 ?" and so on.
>

<connection> lists in the config file already supports that without any
fanfare. You can couple it with management-query-remote if interactive
selection of the remote is needed.

The GUI doesn't yet support management-query-remote but its very easy to
add.

Selva

**Comment by chipitsine** [comment]
do you mean multiple "remote" per config ?

**Comment by selvanair** [comment]
Closing as already supported by openvpn.exe.
