### ISSUE TITLE
Feature Request: GUI Buildable on Linux?

### ISSUE THREAD

**Issue by nate2014jatc** [OpenVPN/openvpn-gui#224]
Howdy, I'd like to know if it's easily (relatively speaking) doable to build the OpenVPN GUI on *NIX (Ubuntu specifically) systems.

Pulling the project to my local machine and attempting to build myself causes the `configure` command to return `configure: error: This project is supported for windows only.`, and I'm not certain if this is correctable.

Any response is appreciated, 
thanks

**Comment by selvanair** [comment]
This GUI is written using win32 API and will run only on Windows. But you can build it on ubuntu (cross compile) using mingw. In fact, that's how the release binaries are made.

So if the goal is to cross-compile, here is a quick rundown (assuming a 64 bit build)
(our BUILD.rst should documents this, but it doesn't)

- Install autoconf, automake, and gcc-mingw-w64
- Clone this git repo and from its source folder and run
```
$ autoreconf -iv
$ /configure --host=x86_64-w64-mingw32 --build=x86_64-pc-linux-gnu --disable-password-change
```
That will create openvpn-gui.exe. Copy to Windows and run with limited user rights (i.e not run-as administrator).

To build with the private key password-change feature enabled, you will need openssl library cross-compiled for Windows. Then define OPENSSL_CRYPTO_LIBS and OPENSSL_CRYPTO_FLAGS to point to the openssl libs and include directory, and leave out the --disable-password-change option. See also ./configure --help.

**Comment by nate2014jatc** [comment]
The build instructions for that portion were clear.
I was however hoping to have a functional OpenVPN GUI running on my Ubuntu machine.
Given that it's written exclusively for win32 APIs, I believe I can safely assume that there's no simple (or intermediate) way to make the existing code-base function properly on Linux.
Is my assumption correct?

**Comment by selvanair** [comment]
Yes, it wont be usable on Linux -- to start with its a tray application, uses Windows named-pipes and is hard coded to start Windows openvpn binary which depends on Windows network stack etc...

**Comment by nate2014jatc** [comment]
That's alright, I figured it was a long shot.
I'll go ahead and close this issue :)
