### ISSUE TITLE
Password field is blank after session expiration

### ISSUE THREAD

**Issue by NullSquatch** [OpenVPN/openvpn-gui#227]
# Main Issue

To provide some background, the server I connect to uses `static-challenge`.  I prefer to leave my connection active during the day and put my workstation into sleep mode each night.  When I wake my workstation the next morning, the OpenVPN connection is no longer active and I'm presented with an authentication popup.  This by itself is not an issue.

The problem is that the `Password` field on the popup is blank, despite the fact that I have the `Save password` option enabled.  I would only expect `Password` to be blank if the authentication failure was specifically due to an incorrect username/password.

The client log shows these relevant lines:

```
MANAGEMENT: >STATE:1520524314,GET_CONFIG,,,,,,
SENT CONTROL [OpenVPN Server]: 'PUSH_REQUEST' (status=1)
AUTH: Received control message: AUTH_FAILED,SESSION: Your session has expired, please reauthenticate
SIGUSR1[soft,auth-failure] received, process restarting
MANAGEMENT: >STATE:1520524314,RECONNECTING,auth-failure,,,,,
```

This shows that the session expired, so it makes sense that the popup is being displayed.   If I had to guess, I'd say that the GUI code isn't differentiating between session expiration failures and failures caused by an incorrect username/password.

# Additional Observations

1) In this particular situation, the cursor is in the `Password` field, but I would expect the cursor to instead be in the `Response` field, as that is the field that requires new input in order to successfully connect.
1) In this particular situation, the bottom of the dialog does not state the reason for the previous disconnection.  I would expect it to show the reason returned by the server, i.e. `Your session has expired, please reauthenticate`.
1) If I happen to enter the correct username and password but use an incorrect value for the `Response` field, the dialog clears the `Password` field and shows `Wrong username or password. Try again...` at the bottom of the popup, despite the log showing that the reason for the failure was `AUTH: Received control message: AUTH_FAILED,Google Authenticator Code is incorrect`.  I would expect this to be handled similar to session expiration, i.e. the `Password` field should not be cleared, the cursor should be in an empty `Response` field, and the message at the bottom should read `Google Authenticator Code is incorrect`.

**Comment by selvanair** [comment]
Thanks for the detailed report. Firstly, the GUI shows "wrong username or password" on auth failure because a reason for AUTH_FAIL is not reported by the server in a majority of cases. Therefore, parsing the AUTH_FAILED message to extract the reason and show it the user is not yet implemented in the GUI. At present its parsed only to detect incoming dynamic challenge.

In fact most server setups wouldn't want to provide detailed feedback like username is correct but password is not, or password is ok, but OTP failed etc., as that leaks info to a attacker. That said, we could do better to parse the AUTH failed reason and present it to the server.

As for clearing of password on auth-failure, we do plan to change that (I have patch in my repo, to be  submitted soon).

What version of openvpn are you running on the server? In the community version of OpenVPN, to send session-expiry or other reasons for failure, the server has to use user-pass verification via the management. This appears to be rarely used in spite of its versatility. Anyway, currently there are on going efforts to improve AUTH_FAILURE reporting in OpenVPN core so we are going to improve the GUI too in this regard.

**Comment by NullSquatch** [comment]
>In fact most server setups wouldn't want to provide detailed feedback...

That makes perfect sense.  Now I have to wonder if the admins of my server turned that bit of detail on, if it was a default provided by Access Server, or if it's even configurable there 🤔

>As for clearing of password on auth-failure, we do plan to change that (I have patch in my repo, to be submitted soon).

I saw an existing issue from you that mentioned something along those lines.  Is that what you're referring to?  If so it would not be much of an improvement in my situation because the password field will continue to be blank.  To take advantage of it I would have to know to click cancel and then right-click the systray icon and click connect.

>What version of openvpn are you running on the server?

I don't have admin access to these details, but I believe it's running OpenVPN Access Server.

**Comment by NullSquatch** [comment]
>Anyway, currently there are on going efforts to improve AUTH_FAILURE reporting in OpenVPN core so we are going to improve the GUI too in this regard.

That sounds promising.  Ideally those future improvements will work in favor of anyone in my situation.  Since you mentioned that most servers probably won't want to send detailed auth failure reasons, I have my doubts as to how much those improvement will help.

In the meantime, allow me to propose a simple alternative.  Always prefill the `Password` field when possible (including on auth failures), but have all the password's characters selected with the cursor at the end of the selection.  This implicitly gives the user the option to either press tab/enter to continue using it or to just start typing (which automatically deletes the selected characters).

If this behavior is too controversial, it could be toggled by a new config option.

**Comment by selvanair** [comment]
Thanks for your comments.

I guessed you are using access server which handles AUTH_FAIL much better (or so I hear).  We should  (and will) improve the GUI to parse those messages.

The improvements suggested includes sending back "AUTH_FAILED,SESSION:reason" on session or auth-token expiry. Also it'll eventually make it possible for verify scripts and plugins to send back a reason for auth failure (how much detail to report back would be up to the script/plugin).  It wouldn't affect you as you are using access server. But the GUI learning to handle those would help your case. We won't be able to localize those messages (at least not easily) -- that could become an issue unless the  server-side script is smart enough to return a localized message.

> In the meantime, allow me to propose a simple alternative. Always prefill the Password field when possible (including on auth failures), but have all the password's characters selected with the cursor at the end of the selection. This implicitly gives the user the option to either press tab/enter to continue using it or to just start typing (which automatically deletes the selected characters).

Using the saved password to prefill the dialog even after an auth failure doesn't look right to me, but I'm open to suggestions like these. If prefilling, I think, we should have a button ("eye")  to reveal the password, but what you suggest could be a short-term compromise.

**Comment by selvanair** [comment]
See PR #228.
