### ISSUE TITLE
--config_dir doesnt work from the terminal

### ISSUE THREAD

**Issue by otaruMendez** [OpenVPN/openvpn-gui#236]
I tried using --config_dir option to specify the config directory from the terminal but didnt work but it worked when I set it via the settings menu.

**Comment by selvanair** [comment]
Hmm..  `openvpn-gui.exe --config_dir path` should work. Which version?

**Comment by otaruMendez** [comment]
2.4.5

**Comment by selvanair** [comment]
I'm unable to reproduce this. For example, `"C:\Program Files\OpenVPN\bin\openvpn-gui.exe" --config_dir C:\Users\me\foo"` sets the local config_dir as `C:\Users\me\foo`. Verified by checking the settings as well as starting a .ovpn from that folder.

Note that you need to give the full path of the config folder and only that folder and its immediate subfolders are searched for .ovpn files.
