### ISSUE TITLE
How can "Restart pause" be set to 0?

### ISSUE THREAD

**Issue by leafcutterant** [OpenVPN/openvpn-gui#239]
I'd like to have no restart pause. How can that be achieved?

**Comment by selvanair** [comment]
The pause is controlled by the option `--connect-retry n` By default n = 5 (seconds) in 2.4.x. So adding --`connect-retry 0` to the config file will eliminate the pause (or n=1 for 1 second pause etc.). However, no pause may not work well in some cases as its there for some reason that I don't clearly understand.

**Comment by leafcutterant** [comment]
Thank you, it seems to work. One note: based on the syntax of the config file, the format is `connect-retry 0`, without the dashes. But maybe it also works with the dashes.

I too wanted to find out the reason behind it, but I was unable to. Curious to hear if someone knows it.
