### ISSUE TITLE
Improve dialogs - add shortcuts to input fields/labels

### ISSUE THREAD

**Issue by woodychuck** [OpenVPN/openvpn-gui#242]
In order to improve dialogs is it possible to add shortcuts (e.g. "&Username") to the input field labels and/or other controls? This would help interaction with Keepass auto typing, for example (an auto type sequence could contain Alt-U to select the username input field first, etc.)

**Comment by selvanair** [comment]
One can already TAB between edit boxes and buttons in the password dialog so not sure why input can't be automated with keypass as is. Say, have a hotkey defined in keypass that outputs username, TAB, password. Then TAB to the username field and press the hotkey combination.

That said binding keys to those fields would be nice to do. This may only need some edits of the resource files --- care to provide a patch?

**Comment by woodychuck** [comment]
I came across this idea when I noticed that some of my OpenVPN client configs do save the username (and then input focus is in the password field when the dialog pops up), and some do not (in which case the input focus is in the username field) - and it is difficult to tackle this with a general auto type sequence. Also, shortcuts are not uncommon in user interfaces so usually no harm in adding them ;-)

I tried a local hack with a resource editor which worked fine, however I am not really familiar with Github so I can try for English and German, the languages I am confident to select the best shortcut letter.
