### ISSUE TITLE
Too little space for translated texts

### ISSUE THREAD

**Issue by farosch** [OpenVPN/openvpn-gui#244]
There is too little space for texts on the options page, so some translated texts cannot be shown.
![openvpn-gui_2018-04-14_14-58-22](https://user-images.githubusercontent.com/22905106/38768973-afa7a132-3ffb-11e8-8968-7313e5e0e7b5.png)

**Comment by selvanair** [comment]
Yeah, there are several such poorly spaced or clipped text in some language resources. If you understand the language, please fix and submit a PR.
