### ISSUE TITLE
Dont prompt for password if saved

### ISSUE THREAD

**Issue by farosch** [OpenVPN/openvpn-gui#246]
When the password for a connection is saved, upon connecting openvpn should not show the password prompt. The following screen should only be seen again when **Clear saved passwords** is used.
![openvpn-gui_2018-04-21_11-19-37](https://user-images.githubusercontent.com/22905106/39082600-102002fc-4556-11e8-97cd-f6a59022863e.png)

**Comment by user18x** [comment]
Ich denke das Passwort bzw. die ganzen Zugangsdaten werden angezeigt, weil es könnte ja sein, dass du von x-Servern den falschen ausgewählt hast mit dem du dich nicht verbinden möchtest.

Beispiel:
Du hast 5 Server und wählst aus Versehen den falschen an, dann würde OpenVPN dich automatisch verbinden und du müsstest dich manuell trennen.
So werden dir erst die Zugangsdaten angezeigt, bevor du dich mit "OK" auch zu dem Server verbindest.

**Comment by selvanair** [comment]
Yes the dialog is showed for what user18x said (based on my google translate understanding :) and some similar reasons.

Upgrade to 2.4.5 and you will get automatic (delayed) submission of username password. The dialog is not skipped but if left unattended the connection will complete using the saved values.

**Comment by farosch** [comment]
> Upgrade to 2.4.5 and you will get automatic (delayed) submission of username password. The dialog is not skipped but if left unattended the connection will complete using the saved values.

This does not work for me. Im on 2.4.5 and using Windows 10 17133.73

**Comment by selvanair** [comment]
GUI version 11.10.0.0 included with 2.4.5 release should show the dialog like this:

![capture](https://user-images.githubusercontent.com/3981391/39096000-83b3541e-4617-11e8-822f-c1a21f6cb193.PNG) ![capture](https://user-images.githubusercontent.com/3981391/39095857-4f068b48-4615-11e8-991c-2b5e2a4f8570.PNG)

Will get submitted after a delay (~5 seconds) as in the images above (or silently with no delay if silent_connection is on).

**Comment by farosch** [comment]
seems like something went worng during my last update from 2.4.4 to 2.4.5.
Just reinstalled 2.4.5 and everything works as expected now. Thanks a lot for the explaination @selvanair !!
