### ISSUE TITLE
Docs for registry keys are no longer valid?

### ISSUE THREAD

**Issue by pszafer** [OpenVPN/openvpn-gui#250]
Hi,

Following the docs here https://community.openvpn.net/openvpn/wiki/OpenVPN-GUI

```
If desired, this can be changed via registry key at HKLM\SOFTWaRE\OpenVPN-GUI under the key config_dir.
```

It seems that OpenVPN-GUI is no longer looking for HKLM, but for HKCU instead.
Is that correct?

**Comment by selvanair** [comment]
That document is totally outdated (like the need to run as administrator etc.). We have been look for help to bring the docs up to date.

That said that particular statement is not totally wrong -- we now look for configs in two locations: a global one that can be changed using that HKLM key mentioned there and a user-profile one which defaults to OpenVPN\config in user's profile. The latter may be changed from the settings menu of the GUI.

**Comment by pszafer** [comment]
Ok, now I know everything
IMO, it would be better if OpenVPN GUI would lookup up for HKLM and HKCU key in Software\OpenVPN-GUI.

Since openvpnserv2 settings cannot be changed for us it was better that we could set up service via HKLM\OpenVPN and standalone application via HKLM.

With HKCU we have problems, that there are laptops which are used by multiple users and because of it we have to prepare HKCU for everybody...
We don't want user to see config for openvpnserv2 and same time we would like to have openvpn configs for multiple users. Do you think is that possible somehow?

**Comment by selvanair** [comment]
> We don't want user to see config for openvpnserv2 and same time we would like to have openvpn configs for multiple users. Do you think is that possible somehow?

This is currently not possible, but I too would like to see auto-started and user-started configs separated. An option is to introduce a new registry entry, say, config_dir_auto and have openvpnserv2 scan that location, falling back to current behaviour if that value is not present. 

Alternatively, we can add HKLM\Software\OpenVPN-GUI\config_dir as the global location of configs for the GUI and fall back to HKLM\OpenVPN\config_dir if that's not found. I'm concerned whether this will break any existing setups, though -- setups where that registry key exists but currently unused may get affected.

**Comment by selvanair** [comment]
On further thought, its important for the interactive service and the GUI to agree on the location of global configs. So having an optional reserved location for openvpnserv2 configs looks like the best option -- patching that service should be very easy.

**Comment by pszafer** [comment]
I think one of the best option would be to run openvpnserv2 with --config parameter and run one config per service (install same service with different name wouldn't be that hard).
In that case you don't care about registry and if you want single openvpnserv2 you delete service created automatically and create your own service with --config param for single ovpn client.

But it would be cool if you implement any of the ideas above. All are good for me, don't know which is the easiest to write :)

**Comment by TinCanTech** [comment]
@pszafer much of what you want can be done with [NSSM](https://community.openvpn.net/openvpn/wiki/IntegratingOpenvpnWithNssm)

**Comment by selvanair** [comment]
> @pszafer much of what you want can be done with NSSM
Excellent point -- NSSM works so well that I even completely forgot about it though I've been running a couple of instances using it.
See https://community.openvpn.net/openvpn/wiki/IntegratingOpenvpnWithNssm to get started.

**Comment by TinCanTech** [comment]
> NSSM works so well that I even completely forgot about it though I've been running a couple of instances using it.

I have not tried it with W10 yet, have you ?

**Comment by selvanair** [comment]
> I have not tried it with W10 yet, have you ?

I hadn't till just now. It claims and seems to work fine on Win10.

**Comment by pszafer** [comment]
Ok, thank you for your support, I will try to integrate that

**Comment by pszafer** [comment]
Just to inform.
I ended up using NSSM, with ansible it is pretty straight forward

```
- name: Create Win NSSM
  win_nssm:
    name: vpn
    application: "C:\\Program Files\\OpenVPN\\bin\\openvpn.exe"
    app_parameters_free_form: "--config {{ config_file }}.ovpn"
    state: started
    start_mode: auto
    dependencies: 'Dhcp, tap0901'
    stdout_file: "{{ logfile }}.log"
    stderr_file: "{{ logfile }}.log"
