### ISSUE TITLE
Option to save UserName and PassWord globally

### ISSUE THREAD

**Issue by JacobC1921w** [OpenVPN/openvpn-gui#251]
Just thought that it would be a good idea for lazy people like me.
I use GetFlix VPN, which comes with HEAPS (1312) of config files, which all use the same username and password.

**Comment by stevelex-elex** [comment]
I have the same idea but i dont know why no one is interested to this part !
if developer team could help me about where this program saving the username and passwords i can write some python script to do that .

**Comment by selvanair** [comment]
username and password are saved in HKCU\Software\OpenVPN-GUI\<config-name> as binary values named "username", "auth-data" and "entropy". Here <config-name> is the name of your config file not including .ovpn.  If the certificate private key has a password, that's saved as "key-data". 

Although auth- and key-data are kept encrypted using data-protect API, copying the blobs over for other configs will work as long as its under the same Windows user.

**Comment by MollyBe** [comment]
Here is a simple work around. 

You can place a line in each .opvn configuration file that points to a file where your username and password is stored. 

For example, if the file _mysecretpassword.txt_ was in the same folder as all your other .ovpn files you would need to add this line.
```
auth-user-pass mysecretpasssword.txt
```

_mysecretpassword.txt_ would look like
```
JacobC1926@getflix
password123
```

You can easily edit all the configuration files at once with a simple powershell script

```
$InputFiles = Get-Item "C:\Users\[JacobC1926]\OpenVPN\config\[GetFlix VPN]\*.ovpn"
$OldString  = 'auth-user-pass.*'
$NewString  = 'auth-user-pass mysecretpasssword.txt'
$InputFiles | ForEach {
    (Get-Content -Path $_.FullName) -Replace($OldString,$NewString) | Set-Content -Path $_.FullName
}
```
