### ISSUE TITLE
User/Pass dialogue not displayed when 'up-file' only contain username

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/openvpn-gui#262]
As per the manual:
> --auth-user-pass [up]
Authenticate with server using username/password. up is a file containing username/password on 2 lines. **If the password line is missing, OpenVPN will prompt for one**. 

If the password line is missing then the GUI does **not** display the input dialogue.

Also, the GUI LOG window stops at `MANAGEMENT: CMD 'hold release'` 
but the _actual_ log file also contains `Enter Auth Password:`

**Comment by selvanair** [comment]
If you specify --auth-user-pass [up], then --management-query-passwords is ineffective. So there is no way to support username from file but password from management without altering openvpn core. And, GUI sees only what is queried over the management interface. IMO, supporting this is not worth the trouble as GUI can save username and, optionally, password.

Sounds familiar: for more details see Trac 757: https://community.openvpn.net/openvpn/ticket/757

**Comment by TinCanTech** [comment]
Hi Selva, thanks for the information .. I thought I had seen this somewhere before but could not remember where. If openvpn core is the root cause of this inconsistency then I guess this is not a bug in the GUI.  Closed.

**Comment by TinCanTech** [comment]
Does it sound reasonable to add a Note to doc/openvpn.8 ? 
Along the lines of:
`The openvpn-Gui.exe for Winndows should not be configured with this option, instead use the GUI's built in username/password save functionality.`

**Comment by mattock** [comment]
Here's what we have on the man-page of both "master" and "2.4.6" now:
```
--management-query-passwords
       Query  management channel for private key password and --auth-user-pass
       username/password.  Only query the management channel for inputs which
       ordinarily would have been queried from the console.
```
@selvanair the above implies that --management-query-passwords should be able to co-existing and work with --auth-user-pass. That said, I assume that statement is only valid if a [up] file is not defined.

I think @TinCanTech's suggestion makes sense, but imho openvpn-gui's documentation (e.g. README.md) would be the more correct place. However, I think OpenVPN's man-page should be made more clear about these limitations.

**Comment by selvanair** [comment]
@mattock Yes, that statement in the man could be augmented with: "If a file is specified as the source of username (and optionally password) using the [up] argument to --auth-user-pass, the management will not be queried. In particular, user interfaces that use the management channel (e.g., OpenVPN Windows GUI) will not prompt for username or password if [up] file is specified."

And, agreed the GUI docs should mention this and that the GUI has facility for securely saving credentials without using an "up" file . Adding it to README.rst sounds useful.

But most people who search for such info would end up with the link to the GUI docs: https://community.openvpn.net/openvpn/wiki/OpenVPN-GUI Any volunteers for bringing this page up to date?   It should reflect the suggested best practices in 2.4 release (i.e., do not run as admin, use iservice, don't even mention the registry etc.,) and make the older 2.3 specific instructions less prominent.

**Comment by TinCanTech** [comment]
> Any volunteers for bringing this page up to date?

I am sure I could find time to write something. What I will probably do is start a new page for 2.4 and change that page back to 2.3 only.

**Comment by selvanair** [comment]
Sounds good. Eventually we can even embed or link to that as the help page for the GUI.

**Comment by TinCanTech** [comment]
https://community.openvpn.net/openvpn/wiki/OpenVPN-GUI-New

It's only a first draught .. but it does sum things up ;)

**Comment by mattock** [comment]
Well that is a start :smile:.

**Comment by TinCanTech** [comment]
I had to :rofl: 

I have added some more details .. 
I have kept it deliberately basic so as not to confuse new users with too much information. So it is only GUI specific and very basic.  Let me know of any improvements .. feel free to edit and rename the page at will.

**Comment by TinCanTech** [comment]
@selvanair .. would it be possible to get a "Help" button or menu item (anything you prefer) into the GUI before the next release (currently blocked by TAP driver signing) linking to the page I made ? That page has "Additional notes" at each stage where we can add important notes and, of course, we can append more information as desired.

**Comment by selvanair** [comment]
Just adding a link would be easy to do but I wanted to:

Make a window that shows a clickable link to your wiki write-up followed by all command line options. And link it to a help button/menu/tab as well as show the same for "openvpn-gui --help"

**Comment by TinCanTech** [comment]
Just a wee nudge ;) .. what ever you prefer.
