### ISSUE TITLE
Registry key service_only is ignored

### ISSUE THREAD

**Issue by Ninja101** [OpenVPN/openvpn-gui#264]
We were testing a deployment of OpenVPN for a few of our remote employees still using Windows 7, we have a GPO in place that pushes the necessary settings for the OpenVPN-GUI to pick out the user's config, and auto-connect on login.

We noticed one registry key we set via GPO "HKCU\Software\OpenVPN-GUI\service_only" was set to 1, however in the options the checkbox is not checked, when checking it and clicking "Ok" the registry key is updated, however it is always set to 0 regardless of the checkbox value.

**Comment by Ninja101** [comment]
After a closer look, the registry key _is_ being read and used. The checkbox on the settings page just doesn't reflect the true value.

**Comment by mattock** [comment]
@selvanair any reason not to remove service_only from the "master" branch altogether?

**Comment by selvanair** [comment]
I would love to if no one objects :)

Just checked the code: the service_only entry in the advanced menu is not wired to anything, so it has no effect. Any value in the registry or command line should be respected, though. Even if we retain this feature, I think we could just remove that checkbox from the settings menu.
