### ISSUE TITLE
[Feature request] Extend the GUI to allow controlling always on (already started) connections

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/openvpn-gui#266]
Not expecting anything now ;-) just starting a thread for it.

[Referenced here](https://github.com/OpenVPN/openvpn-gui/issues/209#issuecomment-360911599) by @selvanair

**Comment by selvanair** [comment]
Thanks for the reminder..:)

**Comment by yegors** [comment]
Just use the Windscribe app, it has this feature: https://blog.windscribe.com/windscribe-1-83-win-mac-changelog-6ae00c0e07cd

**Comment by jjakob** [comment]
If you mean controlling which connections can get auto-started on the launch of the program, that would be very useful.

**Comment by selvanair** [comment]
We now have support for connecting to and controlling openvpn.exe processes pre- started by the automatic service. See #512
