### ISSUE TITLE
Portable Version?

### ISSUE THREAD

**Issue by jaydee9296** [OpenVPN/openvpn-gui#27]
Is there any way to create a portable version using the openvpn-gui? Because I want to create a portable version using this kind of GUI. Thank you!

**Comment by leobasilio** [comment]
Could you tell us a little bit more about it?

**Comment by jaydee9296** [comment]
I'll give you a sample file sir. :) Just look at it though if it is possible

http://www.mediafire.com/download/ycc92h1nu6d17ly/BufferedVPN.zip

**Comment by leobasilio** [comment]
If there's already this portable version, why should we make another one?

**Comment by jaydee9296** [comment]
Yes there is but maybe it is the version 1. We want the latest openvpn-gui version for us to use it too anywhere. :)

**Comment by selvanair** [comment]
The zip you posted is an "unofficial" packaging of openvpn (2.3.6) with a very old version of openvpn-gui, possibly distributed by some VPN provider. If you want to use the latest release, just download it from https://openvpn.net/index.php/open-source/downloads.html

**Comment by selvanair** [comment]
Thread gone cold and no relevant point being raised here. Closing.
