### ISSUE TITLE
Is there a way to install OpenVPN-GUI where it doesn't automatically add itself to launch on startup?

### ISSUE THREAD

**Issue by jmol123** [OpenVPN/openvpn-gui#273]
I have an issue where I am trying to deploy OpenVPN-GUI remotely via Command Prompt and the program tries to run on first Windows login, but I don't want it to run at startup.  Can I specify an install switch or write a .bat file or something to programatically change the setting during the deployment process?  Thanks!!

**Comment by selvanair** [comment]
For silent install, use the switch /SELECT_LAUNCH=0 (default is 1)
For manual install there is a check-box for the same in the "Choose Components" dialog.

@mattock  Is there a place where we document all installer options?
