### ISSUE TITLE
GUI Tray Icon dissapears after laptop sleep/unsleep action Windows 10

### ISSUE THREAD

**Issue by 77cc33** [OpenVPN/openvpn-gui#276]
I found that almost every time when I close lid of my laptop, I don't find GUI tray icon anymore to connect/disconnect any connections. 

After that I should close OpenVPN daemons with taskmanager, start Openvpn GUI again, and reconnect all connections I need. Do you have any ideas how to solve it?

**Comment by xrysf03** [comment]
Have you checked the config of "visibility options for icons in the notification area" ? Does the GUI program actually die?

**Comment by 77cc33** [comment]
yes right now visibility set to always show, and issue still exists. So when I open laptop after sleep, it disappear in 2-3 seconds, and I don't see it in processes, but connections still running fine. 

But I start it again as admin or as user, I can't connect to my connections any more and they marked as not active

![image](https://user-images.githubusercontent.com/2612157/45234876-b8a3e500-b2df-11e8-9016-a6192cd81ea2.png)

**Comment by 77cc33** [comment]
and seems I have this log in windows event viewer 

```
The description for Event ID 0 from source openvpnserv cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

openvpnserv error: 
0x20000000
OpenVPN exited with error: exit code = 1
```

**Comment by selvanair** [comment]
The error you get is expected if the connection is active and you are trying to start another instance possibly using the same log file and same tap adapter. Instead, you will have to manually kill any running openvpn process(es) before attempting a restart. Just as you posted on Aug 5.

But the real question is why the GUI is abnormally terminating on suspend.  I have not seen it before but can try to reproduce given more details: Windows version, GUI and openvpn versions,  and verb = 4 log file of the openvpn process that remains active after the resume. Does a clean reinstall help? -- by clean I mean uninistall and clear the HKCU/Software/OpenVPN-GUI registry key. Note that will also delete any saved encrypted password blobs.

**Comment by 77cc33** [comment]
Ok I will try reinstall, enable verb 4 logs and will back to you.

As for now, I'am starting GUI autoconnect with Task Scheduler at system logon C:\Program Files\OpenVPN\bin\openvpn-gui.exe --connect dev.ovpn

Maybe it's the reasons of these crashes? Maybe there is some other Official way to autoconnect with gui on system startup?

**Comment by selvanair** [comment]
By "at system logon" if you mean on bootup before any user has logged in, that will definitely not work. With proper flags (interactive, run only when user is logged on etc.) it should work, though I haven't tried.

Anyway try first by adding the GUI to the startup menu (see settings) to automatically start the GUI on logon and then manually start the connection. If that works without issues you know where the problem lies. For auto connect making a shortcut with --connect dev.ovpn as the argument and adding that to launch on logon may be better than using task scheduler.

**Comment by 77cc33** [comment]
I used this one

![image](https://user-images.githubusercontent.com/2612157/45244728-bf435400-b301-11e8-9eb6-bf0820590ad7.png)

but will try all your suggestions, and return back to you

**Comment by selvanair** [comment]
This may not fix your problem, but do not run the GUI with "highest privileges" -- just run with the usual limited privileges. That is how GUI shipped with 2.4 is supposed to be used.

**Comment by 77cc33** [comment]
Problem solved after moving startup to shell:startup shortcut. So it seems was some Task Scheduler issue. Thank you for your help!

**Comment by LinuxOnTheDesktop** [comment]
Judging by my experience, this issue needs re-opening. Here is why.

* Running the GUI at boot, via the _Scheduler_ and with _elevated privileges_, makes the OpenVPN icon disappear after sleep

* Running the GUI at boot, via the _Scheduler_ and with _normal privileges_, fails to launch the GUI and instead gives an error message (that I thought I'd captured but I haven't; I can capture it if need be).

* Running the GUI at boot _without the Scheduler_, _requires Admin_ (and even then, at boot, doesn't work).

Windows 10 (upgraded from 8.1).
OpenVPN version: 2.4.7.I601 (sic, I think; the GUI may be a different version)
