### ISSUE TITLE
VPN config doesn't work on Netgear D6400 (Windows)

### ISSUE THREAD

**Issue by polkwan** [OpenVPN/openvpn-gui#279]
![vpn error](https://user-images.githubusercontent.com/13006816/47860706-7d122c80-ddf1-11e8-9b32-582394e8364b.png)
Hello,

I'm struggling to start using the VPN option in a D6400.

I think I do everything as asked in the instructions.

To make sure, I even checked this video and I do everything like it's told.

--> https://www.youtube.com/watch?v=2yUwjvrv2Qo

Even though it's not the same rooter, it's the same GUI.

 

Instead, I always get a notifying message from the the OpenVPN :

"Connection to Client1 has failed"

 

> Options error: --ca fails with 'ca.crt': No such file or directory (errno=2)
> Options error: --cert fails with 'client.crt': No such file or directory (errno=2)
> Thu Nov 01 15:39:43 2018 us=23726 WARNING: cannot stat file 'client.key': No such file or directory (errno=2)
> Options error: --key fails with 'client.key'
> Options error: Please correct these errors.
> Use --help for more information.

I don't understand because all these files are present in that folder.

Do you know what's wrong ?

**Comment by selvanair** [comment]
Are those errors on the D6400 router or on a Windows client running OpenVPN Windows GUI? If its former, please ask in openvpn-users list (post to openvpn-users@lists.sorceforge.net) or OpenVPN forum (https://forums.openvpn.net/)

If Windows GUI is showing those errors in the logs, you are most likely starting a config different from the one for which ca cert, key etc are present as shown. Note that the GUI reads configs (.ovpn files) from two locations: usually, C:\Program Files\OpenVPN\config\ and C:\Users\<username>\OpenVPN\config, and the latter gets precedence over the former. So, check whether a config with the same name exists in the latter location or any of its sub-folders -- if yes, ensure the key and cert files are also copied to the same folder as that .ovpn file.

Its better to inline keys and certificates in the config file to eliminate such dependencies.

**Comment by polkwan** [comment]
Thank you selvanair !

It did help for sure ! Indeed, OpenVpn was looking in the wrong folder.
Now, in my case, the latest build OpenVpn (2.4.6) wasn't able to work properly with my D6400 rooter.
I had to download the 2.4.4 so that it runs properly with the rooter.

**Comment by selvanair** [comment]
In such cases (same config name in two locations) the GUI will issue a duplicate config warning when it starts up. Do not ignore warnings!

Latest release (2.4.6) not working and need to downgrade to 2.4.4 is not a good thing. Report to whoever is supplying the build. If building yourself from official sources please file a bug report in OpenVPN  trac with details. On Windows do use the latest (2.4.6) -- there are some important bug fixes in it.
