### ISSUE TITLE
Insufficient permissions to route the traffic

### ISSUE THREAD

**Issue by gjf** [OpenVPN/openvpn-gui#281]
Latest OpenVPN client, Windows 10 Pro x64 1809.

After install with default settings when running with service the client cannot perform routing:
Wed Nov 21 14:20:51 2018 open_tun
Wed Nov 21 14:20:51 2018 TAP-WIN32 device [Ethernet 2] opened: \\.\Global\{F3029CBA-57CA-44D1-88F6-8E5CC53220A7}.tap
Wed Nov 21 14:20:51 2018 Successful ARP Flush on interface [24] {F3029CBA-57CA-44D1-88F6-8E5CC53220A7}
Wed Nov 21 14:20:51 2018 Blocking outside dns using service succeeded.
Wed Nov 21 14:20:56 2018 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Nov 21 14:20:56 2018 ERROR: Windows route add command failed: returned error code 1
Wed Nov 21 14:20:56 2018 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Nov 21 14:20:56 2018 ERROR: Windows route add command failed: returned error code 1
Wed Nov 21 14:20:56 2018 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Nov 21 14:20:56 2018 ERROR: Windows route add command failed: returned error code 1
Wed Nov 21 14:20:56 2018 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Nov 21 14:20:56 2018 ERROR: Windows route add command failed: returned error code 1
Wed Nov 21 14:20:56 2018 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Nov 21 14:20:56 2018 ERROR: Windows route add command failed: returned error code 1
Wed Nov 21 14:20:56 2018 Initialization Sequence Completed

When running client as admin everything works.

**Comment by cron2** [comment]
Hi,

On Wed, Nov 21, 2018 at 03:28:03AM -0800, gjf wrote:
> Latest OpenVPN client, Windows 10 Pro x64 1809.
> 
> After install with default settings when running with service the client cannot perform routing:
> Wed Nov 21 14:20:51 2018 open_tun
> Wed Nov 21 14:20:51 2018 TAP-WIN32 device [Ethernet 2] opened: \\.\Global\{F3029CBA-57CA-44D1-88F6-8E5CC53220A7}.tap
> Wed Nov 21 14:20:51 2018 Successful ARP Flush on interface [24] {F3029CBA-57CA-44D1-88F6-8E5CC53220A7}
> Wed Nov 21 14:20:51 2018 Blocking outside dns using service succeeded.
> Wed Nov 21 14:20:56 2018 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
> Wed Nov 21 14:20:56 2018 ERROR: Windows route add command failed: returned error code 1

This looks like you have "--route-method netsh" configured in your
client conf.  Get rid of all "route-method" lines in there.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by TinCanTech** [comment]
Which version of OpenVPN did you install .. 2.3.18 or 2.4.6 ?

**Comment by cron2** [comment]
Hi,

On Wed, Nov 21, 2018 at 05:03:46AM -0800, Richard Bonhomme wrote:
> Which version of OpenVPN did you install .. 2.3.18 or 2.4.6 ?

Since the log is talking about "service" in other places, it must
be 2.4.x

gert


-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by gjf** [comment]
openvpn-install-2.4.6-I602.exe

**Comment by TinCanTech** [comment]
Using 2.4.6 as normal user, the prerequisite is that your user is a member of the `OpenVPN-Administrators` group.  However, if you run the install when logged in as Local Administrator then the step to create the group is omitted.  
See: https://community.openvpn.net/openvpn/wiki/OpenVPN-GUI-New#gui-group
I'm not sure of the recommended way to resolve this but what you can do is:

- As Local-Admin, uninstall openvpn.
- Login as your user and re-install openvpn.
- At the UAC enter the Local-Admin password.

This _should_ create the group and add your user to it.
Let us know if  that works as expect, thanks.

**Comment by gjf** [comment]
I am already a member of OpenVPN-Administrators group - see attached.

**Comment by TinCanTech** [comment]
As @cron2 points out above, the `InteractiveService` is in use (`Blocking outside dns using service succeeded`), so your installation maybe setup correctly.  The question now is "Why does openvpn fall back to `route` when trying to configure routes?"

**Comment by TinCanTech** [comment]
Can you post the successful log when running as admin please.

**Comment by TinCanTech** [comment]
I should have said, at `verb 4` please :) (Which is add `verb4` to your client config and start the connection again)

**Comment by gjf** [comment]
Wed Nov 21 18:03:49 2018   pkcs11_protected_authentication = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_private_mode = 00000000
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_cert_private = DISABLED
Wed Nov 21 18:03:49 2018   pkcs11_pin_cache_period = -1
Wed Nov 21 18:03:49 2018   pkcs11_id = '[UNDEF]'
Wed Nov 21 18:03:49 2018   pkcs11_id_management = DISABLED
Wed Nov 21 18:03:49 2018   server_network = 0.0.0.0
Wed Nov 21 18:03:49 2018   server_netmask = 0.0.0.0
Wed Nov 21 18:03:49 2018   server_network_ipv6 = ::
Wed Nov 21 18:03:49 2018   server_netbits_ipv6 = 0
Wed Nov 21 18:03:49 2018   server_bridge_ip = 0.0.0.0
Wed Nov 21 18:03:49 2018   server_bridge_netmask = 0.0.0.0
Wed Nov 21 18:03:49 2018   server_bridge_pool_start = 0.0.0.0
Wed Nov 21 18:03:49 2018   server_bridge_pool_end = 0.0.0.0
Wed Nov 21 18:03:49 2018   ifconfig_pool_defined = DISABLED
Wed Nov 21 18:03:49 2018   ifconfig_pool_start = 0.0.0.0
Wed Nov 21 18:03:49 2018   ifconfig_pool_end = 0.0.0.0
Wed Nov 21 18:03:49 2018   ifconfig_pool_netmask = 0.0.0.0
Wed Nov 21 18:03:49 2018   ifconfig_pool_persist_filename = '[UNDEF]'
Wed Nov 21 18:03:49 2018   ifconfig_pool_persist_refresh_freq = 600
Wed Nov 21 18:03:49 2018   ifconfig_ipv6_pool_defined = DISABLED
Wed Nov 21 18:03:49 2018   ifconfig_ipv6_pool_base = ::
Wed Nov 21 18:03:49 2018   ifconfig_ipv6_pool_netbits = 0
Wed Nov 21 18:03:49 2018   n_bcast_buf = 256
Wed Nov 21 18:03:49 2018   tcp_queue_limit = 64
Wed Nov 21 18:03:49 2018   real_hash_size = 256
Wed Nov 21 18:03:49 2018   virtual_hash_size = 256
Wed Nov 21 18:03:49 2018   client_connect_script = '[UNDEF]'
Wed Nov 21 18:03:49 2018   learn_address_script = '[UNDEF]'
Wed Nov 21 18:03:49 2018   client_disconnect_script = '[UNDEF]'
Wed Nov 21 18:03:49 2018   client_config_dir = '[UNDEF]'
Wed Nov 21 18:03:49 2018   ccd_exclusive = DISABLED
Wed Nov 21 18:03:49 2018   tmp_dir = 'C:\Users\User\AppData\Local\Temp\'
Wed Nov 21 18:03:49 2018   push_ifconfig_defined = DISABLED
Wed Nov 21 18:03:49 2018   push_ifconfig_local = 0.0.0.0
Wed Nov 21 18:03:49 2018   push_ifconfig_remote_netmask = 0.0.0.0
Wed Nov 21 18:03:49 2018   push_ifconfig_ipv6_defined = DISABLED
Wed Nov 21 18:03:49 2018   push_ifconfig_ipv6_local = ::/0
Wed Nov 21 18:03:49 2018   push_ifconfig_ipv6_remote = ::
Wed Nov 21 18:03:49 2018   enable_c2c = DISABLED
Wed Nov 21 18:03:49 2018   duplicate_cn = DISABLED
Wed Nov 21 18:03:49 2018   cf_max = 0
Wed Nov 21 18:03:49 2018   cf_per = 0
Wed Nov 21 18:03:49 2018   max_clients = 1024
Wed Nov 21 18:03:49 2018   max_routes_per_client = 256
Wed Nov 21 18:03:49 2018   auth_user_pass_verify_script = '[UNDEF]'
Wed Nov 21 18:03:49 2018   auth_user_pass_verify_script_via_file = DISABLED
Wed Nov 21 18:03:49 2018   auth_token_generate = DISABLED
Wed Nov 21 18:03:49 2018   auth_token_lifetime = 0
Wed Nov 21 18:03:49 2018   client = ENABLED
Wed Nov 21 18:03:49 2018   pull = ENABLED
Wed Nov 21 18:03:49 2018   auth_user_pass_file = 'stdin'
Wed Nov 21 18:03:49 2018   show_net_up = DISABLED
Wed Nov 21 18:03:49 2018   route_method = 0
Wed Nov 21 18:03:49 2018   block_outside_dns = DISABLED
Wed Nov 21 18:03:49 2018   ip_win32_defined = DISABLED
Wed Nov 21 18:03:49 2018   ip_win32_type = 3
Wed Nov 21 18:03:49 2018   dhcp_masq_offset = 0
Wed Nov 21 18:03:49 2018   dhcp_lease_time = 31536000
Wed Nov 21 18:03:49 2018   tap_sleep = 0
Wed Nov 21 18:03:49 2018   dhcp_options = DISABLED
Wed Nov 21 18:03:49 2018   dhcp_renew = DISABLED
Wed Nov 21 18:03:49 2018   dhcp_pre_release = DISABLED
Wed Nov 21 18:03:49 2018   domain = '[UNDEF]'
Wed Nov 21 18:03:49 2018   netbios_scope = '[UNDEF]'
Wed Nov 21 18:03:49 2018   netbios_node_type = 0
Wed Nov 21 18:03:49 2018   disable_nbt = DISABLED
Wed Nov 21 18:03:49 2018 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 24 2018
Wed Nov 21 18:03:49 2018 Windows version 6.2 (Windows 8 or greater) 64bit
Wed Nov 21 18:03:49 2018 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
Wed Nov 21 18:03:49 2018 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25342
Wed Nov 21 18:03:49 2018 Need hold release from management interface, waiting...
Wed Nov 21 18:03:49 2018 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25342
Wed Nov 21 18:03:49 2018 MANAGEMENT: CMD 'state on'
Wed Nov 21 18:03:49 2018 MANAGEMENT: CMD 'log all on'
Wed Nov 21 18:03:50 2018 MANAGEMENT: CMD 'echo all on'
Wed Nov 21 18:03:50 2018 MANAGEMENT: CMD 'bytecount 5'
Wed Nov 21 18:03:50 2018 MANAGEMENT: CMD 'hold off'
Wed Nov 21 18:03:50 2018 MANAGEMENT: CMD 'hold release'
Wed Nov 21 18:03:51 2018 MANAGEMENT: CMD 'username "Auth" "maverick"'
Wed Nov 21 18:03:51 2018 MANAGEMENT: CMD 'password [...]'
Wed Nov 21 18:03:51 2018 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Wed Nov 21 18:03:51 2018 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Nov 21 18:03:51 2018 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Wed Nov 21 18:03:51 2018 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Nov 21 18:03:51 2018 LZO compression initializing
Wed Nov 21 18:03:51 2018 Control Channel MTU parms [ L:1654 D:1156 EF:94 EB:0 ET:0 EL:3 ]
Wed Nov 21 18:03:51 2018 MANAGEMENT: >STATE:1542812631,RESOLVE,,,,,,
Wed Nov 21 18:03:51 2018 Data Channel MTU parms [ L:1654 D:1450 EF:122 EB:411 ET:32 EL:3 ]
Wed Nov 21 18:03:51 2018 Local Options String (VER=V4): 'V4,dev-type tap,link-mtu 1590,tun-mtu 1532,proto UDPv4,comp-lzo,cipher AES-256-CBC,auth SHA1,keysize 256,key-method 2,tls-client'
Wed Nov 21 18:03:51 2018 Expected Remote Options String (VER=V4): 'V4,dev-type tap,link-mtu 1590,tun-mtu 1532,proto UDPv4,comp-lzo,cipher AES-256-CBC,auth SHA1,keysize 256,key-method 2,tls-server'
Wed Nov 21 18:03:51 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]xxx.xxx.xxx.xxx:23241
Wed Nov 21 18:03:51 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Nov 21 18:03:51 2018 UDP link local: (not bound)
Wed Nov 21 18:03:51 2018 UDP link remote: [AF_INET]xxx.xxx.xxx.xxx:23241
Wed Nov 21 18:03:51 2018 MANAGEMENT: >STATE:1542812631,WAIT,,,,,,
Wed Nov 21 18:03:51 2018 MANAGEMENT: >STATE:1542812631,AUTH,,,,,,
Wed Nov 21 18:03:51 2018 TLS: Initial packet from [AF_INET]xxx.xxx.xxx.xxx:23241, sid=68daf1c8 0b2c2099
Wed Nov 21 18:03:51 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Nov 21 18:03:51 2018 VERIFY OK: depth=1, .....
Wed Nov 21 18:03:51 2018 VERIFY KU OK
Wed Nov 21 18:03:51 2018 Validating certificate extended key usage
Wed Nov 21 18:03:51 2018 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Nov 21 18:03:51 2018 VERIFY EKU OK
Wed Nov 21 18:03:51 2018 VERIFY OK: depth=0, .....
Wed Nov 21 18:03:51 2018 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Wed Nov 21 18:03:51 2018 [Base] Peer Connection Initiated with [AF_INET]xxx.xxx.xxx.xxx:23241
Wed Nov 21 18:03:52 2018 MANAGEMENT: >STATE:1542812632,GET_CONFIG,,,,,,
Wed Nov 21 18:03:52 2018 SENT CONTROL [Base]: 'PUSH_REQUEST' (status=1)
Wed Nov 21 18:03:52 2018 PUSH: Received control message: 'PUSH_REPLY,route 0.0.0.0 255.255.255.255 net_gateway,dhcp-option DNS 192.168.111.1,route-gateway 192.168.111.1,redirect-gateway def1,redirect-gateway def1 bypass-dhcp,route-method exe,route 192.168.111.1 255.255.255.0,dhcp-option DNS 192.168.111.1,block-outside-dns,dhcp-option WINS 192.168.111.1,route-gateway dhcp,ping 15,ping-restart 60,peer-id 0,cipher AES-128-GCM'
Wed Nov 21 18:03:52 2018 OPTIONS IMPORT: timers and/or timeouts modified
Wed Nov 21 18:03:52 2018 OPTIONS IMPORT: route options modified
Wed Nov 21 18:03:52 2018 OPTIONS IMPORT: route-related options modified
Wed Nov 21 18:03:52 2018 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed Nov 21 18:03:52 2018 OPTIONS IMPORT: peer-id set
Wed Nov 21 18:03:52 2018 OPTIONS IMPORT: adjusting link_mtu to 1657
Wed Nov 21 18:03:52 2018 OPTIONS IMPORT: data channel crypto options modified
Wed Nov 21 18:03:52 2018 Data Channel: using negotiated cipher 'AES-128-GCM'
Wed Nov 21 18:03:52 2018 Data Channel MTU parms [ L:1585 D:1450 EF:53 EB:411 ET:32 EL:3 ]
Wed Nov 21 18:03:52 2018 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Wed Nov 21 18:03:52 2018 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Wed Nov 21 18:03:52 2018 interactive service msg_channel=0
Wed Nov 21 18:03:52 2018 ROUTE_GATEWAY 192.168.61.1/255.255.255.0 I=16 HWADDR=7c:2a:31:38:80:8d
Wed Nov 21 18:03:52 2018 open_tun
Wed Nov 21 18:03:52 2018 TAP-WIN32 device [Ethernet 2] opened: \\.\Global\{F3029CBA-57CA-44D1-88F6-8E5CC53220A7}.tap
Wed Nov 21 18:03:52 2018 TAP-Windows Driver Version 9.22 
Wed Nov 21 18:03:52 2018 TAP-Windows MTU=1500
Wed Nov 21 18:03:52 2018 Successful ARP Flush on interface [24] {F3029CBA-57CA-44D1-88F6-8E5CC53220A7}
Wed Nov 21 18:03:52 2018 Blocking outside DNS
Wed Nov 21 18:03:52 2018 Block_DNS: WFP engine opened
Wed Nov 21 18:03:52 2018 Block_DNS: Using existing sublayer
Wed Nov 21 18:03:52 2018 Block_DNS: Added permit filters for exe_path
Wed Nov 21 18:03:52 2018 Block_DNS: Added block filters for all interfaces
Wed Nov 21 18:03:52 2018 Block_DNS: Added permit filters for TAP interface
Wed Nov 21 18:03:52 2018 Extracted DHCP router address: 192.168.111.1
Wed Nov 21 18:03:57 2018 TEST ROUTES: 3/3 succeeded len=2 ret=1 a=0 u/d=up
Wed Nov 21 18:03:57 2018 C:\WINDOWS\system32\route.exe ADD xxx.xxx.xxx.xxx MASK 255.255.255.255 192.168.61.1
Wed Nov 21 18:03:57 2018 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Nov 21 18:03:57 2018 C:\WINDOWS\system32\route.exe ADD 0.0.0.0 MASK 128.0.0.0 192.168.111.1
Wed Nov 21 18:03:57 2018 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Nov 21 18:03:57 2018 C:\WINDOWS\system32\route.exe ADD 128.0.0.0 MASK 128.0.0.0 192.168.111.1
Wed Nov 21 18:03:57 2018 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Nov 21 18:03:57 2018 MANAGEMENT: >STATE:1542812637,ADD_ROUTES,,,,,,
Wed Nov 21 18:03:57 2018 C:\WINDOWS\system32\route.exe ADD 0.0.0.0 MASK 255.255.255.255 192.168.61.1
Wed Nov 21 18:03:57 2018 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Nov 21 18:03:57 2018 C:\WINDOWS\system32\route.exe ADD 192.168.111.1 MASK 255.255.255.0 192.168.111.1
Wed Nov 21 18:03:57 2018 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Nov 21 18:03:57 2018 Initialization Sequence Completed
Wed Nov 21 18:03:57 2018 MANAGEMENT: >STATE:1542812637,CONNECTED,SUCCESS,,xxx.xxx.xxx.xxx,23241,,
Wed Nov 21 18:03:58 2018 PID_ERR replay [0] [SSL-0] [0000000011111111122222222222223333444444444444444444555555555555] 0:80 0:80 t=1542812638[0] r=[-1,64,15,0,1] sl=[48,64,64,528]

**Comment by cron2** [comment]
Hi,

On Wed, Nov 21, 2018 at 07:06:44AM -0800, gjf wrote:
> Wed Nov 21 18:03:52 2018 PUSH: Received control message: 'PUSH_REPLY,route 0.0.0.0 255.255.255.255 net_gateway,dhcp-option DNS 192.168.111.1,route-gateway 192.168.111.1,redirect-gateway def1,redirect-gateway def1 bypass-dhcp,route-method exe,route 192.168.111.1 255.255.255.0,dhcp-option DNS 192.168.111.1,block-outside-dns,dhcp-option WINS 192.168.111.1,route-gateway dhcp,ping 15,ping-restart 60,peer-id 0,cipher AES-128-GCM'

There's the problem: the server is pushing "route-method exe", which
doesn't make any sense whatsoever.

If you control the server, please remove this push statement.  It does not
server a useful purpose - never did, but with 2.4.x it actually breaks
stuff.

If you do not control the server, and the admin is not willing to 
change his config, add

  pull-filter ignore route-method

to your client config - this will make the client ignore this option if
sent from the server.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by gjf** [comment]
I control the server so I can change settings. Actually they are:
push "redirect-gateway def1 bypass-dhcp"
push "route-method exe"
push "route 192.168.111.1 255.255.255.0"
push "dhcp-option DNS 192.168.111.1"
push "block-outside-dns" 
push "dhcp-option WINS 192.168.111.1"

The main idea is to use windows network and shares for all VPN users as well as force change dns into the router one.

Do you mean only
push "route-method exe"
should be removed?

**Comment by cron2** [comment]
Hi,

On Wed, Nov 21, 2018 at 07:13:47AM -0800, gjf wrote:
> I control the server so I can change settings. Actually they are:
> push "redirect-gateway def1 bypass-dhcp"
> push "route-method exe"
> push "route 192.168.111.1 255.255.255.0"
> push "dhcp-option DNS 192.168.111.1"
> push "block-outside-dns" 
> push "dhcp-option WINS 192.168.111.1"

Most of these are fine...

> The main idea is to use windows network and shares for all VPN users as well as force change dns into the router one.
> 
> Do you mean only
> push "route-method exe"
> should be removed?

... but this one needs to go, yes :-)

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by gjf** [comment]
After removing it all works fine but I have another error during connection:

Wed Nov 21 18:16:51 2018 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 24 2018
Wed Nov 21 18:16:51 2018 Windows version 6.2 (Windows 8 or greater) 64bit
Wed Nov 21 18:16:51 2018 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
Wed Nov 21 18:16:53 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]xxx.xxx.xxx.xxx:23241
Wed Nov 21 18:16:53 2018 UDP link local: (not bound)
Wed Nov 21 18:16:53 2018 UDP link remote: [AF_INET]xxx.xxx.xxx.xxx:23241
Wed Nov 21 18:16:54 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Nov 21 18:16:54 2018 [Base] Peer Connection Initiated with [AF_INET]xxx.xxx.xxx.xxx:23241
Wed Nov 21 18:16:55 2018 open_tun
Wed Nov 21 18:16:55 2018 TAP-WIN32 device [Ethernet 2] opened: \\.\Global\{F3029CBA-57CA-44D1-88F6-8E5CC53220A7}.tap
Wed Nov 21 18:16:55 2018 Successful ARP Flush on interface [24] {F3029CBA-57CA-44D1-88F6-8E5CC53220A7}
Wed Nov 21 18:16:55 2018 Blocking outside dns using service succeeded.
Wed Nov 21 18:17:00 2018 ROUTE: route addition failed using service: Incorrect parameter.   [status=87 if_index=24]
Wed Nov 21 18:17:00 2018 Initialization Sequence Completed

"Incorrect parameter" is in Russian as I use Russian language in OS, so I translated it for understanding.

**Comment by gjf** [comment]
Looks like I found the problem: it should not be 
 push "route 192.168.111.1 255.255.255.0"
but
 push "route 192.168.111.0 255.255.255.0 192.168.111.1"

Now mo errors.

Thanks to everybody involved!

**Comment by selvanair** [comment]
The last you route you add is wrongly pushed by the server. Should be
push "route 192.168.111.0 255.255.255.0"  Windows wants the target to be the network address like not any within the network. Apart from that, what's the point of "route 0.0.0.0 255.255.255.255"? Considering all this, your server is likely setup poorly --- do you even really need to use tap and not tun? Windows active directory, file sharing etc will work perfectly with tun and perform better.

That said, the GUI sets the --service option after --config so that any route-method in the latter gets overwritten as ROUTE_METHOD_SERVICE. I had no idea route-method could be pushed and thus override this. I propose to enforce "--pull-filter ignore route-method" in the GUI when the service is in use. This i s a hack but --route-method is a bigger evil.

**Comment by cron2** [comment]
Hi,

On Wed, Nov 21, 2018 at 08:02:20AM -0800, Selva Nair wrote:
> That said, the GUI sets the --service option after --config so that any route-method in the latter gets overwritten as ROUTE_METHOD_SERVICE. I had no idea route-method could be pushed and thus override this. I propose to enforce "--pull-filter ignore route-method" in the GUI when the service is in use. This i s a hack but --route-method is a bigger evil.

Sounds good.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de
