### ISSUE TITLE
Why does OpenVPN-GUI have separate Language settings ?

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/openvpn-gui#283]
While testing I accidentally scrolled at some point and changed the language of the GUI which was a little annoying.  Why is the system Locale not sufficient ?

**Comment by selvanair** [comment]
This has been talked about in the past. There are many users who use localized Windows but prefer some applications like OpenVPN to display English menu and messages. We could default to the language in the locale for new installations (unless we already do so) as the user can change it. But, IMO, removing the ability to switch the language is not a good idea.

**Comment by TinCanTech** [comment]
I guess written/spoken language is always a work in progress -- Easier to set the language in one app than the entire system.
