### ISSUE TITLE
Commands to over ride registry settings does not work for standard user

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/openvpn-gui#284]
While testing the registry over ride options, I found that only a local admin can actually use these options successfully.
eg:
As local admin, this works
`openvpn-gui.exe --log_viewer c:/progra~1/baretail/baretail.exe`
but as a standard user it does not.
`bairtail.exe` has been given permission to run by the admin and the user can use it successfully via a desktop shortcut, explorer or command line but `openvpn-gui.exe` only uses `notepad.exe` for the standard user.

**Comment by selvanair** [comment]
The title of this report is misleading. There is no registry entry for log_viewer. In fact  the command line options --log_viewer and --editor are also no longer documented (== deprecated) as the preferred way to open configs and logs is using file association. For historic reasons, the GUI falls back to log_viewer if no file association found and log_viewer is specified on the command line.

So likely what's happening is: you have log files associated with notepad.exe for "user" but either not associated with anything or with baretail for "admin".  Not sure what you mean by "given permission to run by admin" but guess that's not relevant.

In the current code-base, if no file association is found, there is no default log_viewer or editor setting to fall back on. I think this was an oversight and in fact I have an old patch to fix  that ---  somehow lost in the pile of other pending things. See https://github.com/selvanair/openvpn-gui/tree/default-editor

**Comment by TinCanTech** [comment]
Further testing shows that, if I change the default Windows application to `baretail.exe` to open `.log` files then the openvpn-gui does use this application, although it has not been set in the registry and is being used only due to user default. This is when starting the openvpn-gui without specifying `--log_viewer`

**Comment by TinCanTech** [comment]
Sorry, I posted my second comment before noticing your reply.

**Comment by TinCanTech** [comment]
> The title of this report is misleading. There is no registry entry for log_viewer. In fact the command line options --log_viewer and --editor are also no longer documented (== deprecated) as the preferred way to open configs and logs is using file association. For historic reasons, the GUI falls back to log_viewer if no file association found and log_viewer is specified on the command line.

I got the list of options from `openvpn-gui --help` -- The deprecated options are still present there.

I added this data here: https://community.openvpn.net/openvpn/wiki/OpenVPN-GUI-New#gui-help

Due to the deprecation I will close this issue and if you could let me know which options are deprecated I will update the list on that page and do some further testing (if I find any related problems I'll reopen this issue), thanks.

**Comment by selvanair** [comment]
You are right --help lists some totally outdated stuff. Has to be fixed.

**Comment by TinCanTech** [comment]
I will watch out for a patch
