### ISSUE TITLE
Windows 10 Home no tap device

### ISSUE THREAD

**Issue by ghost** [OpenVPN/openvpn-gui#290]
There is some regression in the new release.

Again as I had in a previous version (which was fixed by a minor release) the tap device is not able to get alive. I don't see it in network devices.

I don't know what's the issue, I only remember the same exact thing happened and got fixed in some way.

On Pro is fine though.

Also the service fail to start. I tried even manually. And I have the message when I open the app about it.

**Comment by kitsune-one** [comment]
Try the new installer https://swupdate.openvpn.org/community/releases/openvpn-install-2.4.7-I603.exe
ref issue #291

**Comment by mattock** [comment]
Yes, that should fix it. In all the panic during OpenVPN 2.4.6 release and the inadequate tap-windows6 driver signature I forgot to update the build system to point to the old, functional tap-windows6 driver. Now the build systems is using the correct tap-windows6 driver by default. I tested the I603 installer  on Windows 10 as well as Windows 7 and there were no issues.

**Comment by signalguest** [comment]
It's wroking now.

I still get no service running though.

**Comment by selvanair** [comment]
Could you please manually start the service and look for any errors. Like:
`sc start OpenVPNServiceInteractive`
The service depends on tap0901 and dhcp client service which can be checked by
`sc qc openvpnserviceinteractive`
For GUI, that's the only service required. `OpenVPNService` is normally stopped unless you are specifically using it for connections started at boot (and not managed by the GUI).

**Comment by signalguest** [comment]
It started fine. And I don't know why now it even start automatically after reboot.
But I tested again before doing this to reboot, and was not started at all.
I don't know how a manual start could have fixed this.
