### ISSUE TITLE
Release 2.4.7

### ISSUE THREAD

**Issue by kitsune-one** [OpenVPN/openvpn-gui#291]
A couple of issues with release 2.4.7:
- TAP Windows driver appears to be the one singed in April 2018 and not the one signed in April 2016 bundled with 2.4.6. Version shows up as 9.22.1, not 9.21.2. This may be the reason for reports of driver issues on Windows 10 -- I have tested only on Windows 7 which works with either versions.

- Windows GUI shows up as version 11.10.0.0, same as in 2.4.6 although recently added features (nested menu) is in there. Should be 11.11.0.0?

- The GUI tarball  openvpn-gui-11.tar.gz   at  http://build.openvpn.net/downloads/releases/ shows the version as 11.12.0.0 -- should be 11.11.0.0?

**Comment by mattock** [comment]
These problems should be fixed in installer version I603 I pushed out last night my time.
