### ISSUE TITLE
Offer to replace existing configuration during import

### ISSUE THREAD

**Issue by philomory** [OpenVPN/openvpn-gui#294]
At the moment, replacing an existing configuration requires the user do one of three things:
1. Open the new config file in a text editor, select all the text in it, copy it to the clipboard, use the GUI's `edit config` option to open the existing config file in a text editor, remove the existing contents, paste in the new contents, and save the edited configuration file, or
2. Open `%USERPROFILE%\OpenVPN`, and replace the existing configuration file with the new one, or
3. Open `%USERPROFILE%\OpenVPN`, and delete the existing configuration file, then use the GUI's `import file` option to import the new configuration.

This process could be made smoother for non-technical users who have been provided with an updated configuration file by their IT department. When you use the OpenVPN GUI to import a config file whose filename matches that of an existing configuration file, a dialog is shown stating, "A config named <foo> already exists." Ideally, at this point the user could be prompted, "Would you like to replace the existing configuration?", or words to that effect.

**Comment by cron2** [comment]
Hi,

On Mon, Mar 04, 2019 at 04:58:39PM -0800, Adam Gardner wrote:
> When you use the OpenVPN GUI to import a config file whose filename matches that of an existing configuration file, a dialog is shown stating, "A config named <foo> already exists." Ideally, at this point the user could be prompted, "Would you like to replace the existing configuration?", or words to that effect. 

I like this idea.  Someone would have to write the code, though...

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by selvanair** [comment]
Useful and easy to do. So see PR #295

**Comment by cron2** [comment]
Hi,

On Tue, Mar 05, 2019 at 09:43:21AM -0800, Selva Nair wrote:
> Useful and easy to do. So see PR #295 

Nice.  Feature-ACK, will review the code ASAP (travelling right now).

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by philomory** [comment]
@selvanair @cron2 Is there any chance this PR will be merged for an upcoming release?

**Comment by TinCanTech** [comment]
Looks like this can be closed

**Comment by selvanair** [comment]
Handled by PR #295.
