### ISSUE TITLE
--command disconnect_all not working through SSH

### ISSUE THREAD

**Issue by tibitoth** [OpenVPN/openvpn-gui#301]
I wanted to run the `--command disconnect_all` (#104) via Windows Open SSH server+client but it does not take action. With the same user on the host machine I can successfully run this command

**Comment by selvanair** [comment]
Sending commands will only work within the same session. When executed from a new session we 
 try to start new instance of the GUI which would fail with no desktop.

You may be able to workaround this by implementing the same feature using a powershell script: send a WM_COPYDATA message to the window with dwData member of the copydata struct set to WM_OVPN_STOPALL. The latter constant is defined as WM_APP + 14. See main.c of the source code and comments under #104.  This is subject to UIPI restrictions in Windows. Or probably get access to the user's desktop using tmux or screen under cygwin, I haven't tried.
