### ISSUE TITLE
Improve Error Messages

### ISSUE THREAD

**Issue by matthew1471** [OpenVPN/openvpn-gui#302]
Hi,

Firstly thanks for such a great program. The fact I'm raising such a small issue is a sign of how reliable and well behaved the software is.

That said I think we can do something to improve error messages 😄

> Sat May 18 10:12:33 2019 write UDPv4: Unknown error (code=10065)
> Sat May 18 10:12:41 2019 write UDPv4: Unknown error (code=10051)

These aren't truly unknown status codes.. they're documented here : https://docs.microsoft.com/en-us/windows/desktop/winsock/windows-sockets-error-codes-2

Would be great if OpenVPN could provide a more human description for them 😄.

**Comment by selvanair** [comment]
These and many other WSA error codes are explicitly translated in error.c. I do not see why would it get printed as "Unknown error". Which version is this?

**Comment by selvanair** [comment]
No follow up. Closing.
