### ISSUE TITLE
OpenVPNServiceInteractive  installs as "Automatic (Delayed Start)"

### ISSUE THREAD

**Issue by sofakingdead** [OpenVPN/openvpn-gui#303]
I had the issue with 2.4.6 where I would receive a pop-up message that "OpenVPNServiceInteractive is not started. Tasks requiring administrative access may not work."  on start-up.
I resolved this by setting the OpenVPNServiceInteractive service to Automatic in services.msc

When I upgraded to 2.4.7 the issue came back and the service was reverted to "Automatic (Delayed Start)"

Is there anyway for the installer to configure the service to Automatic by default?

System Info:  
Windows 10 Enterprise 1803  64Bit
i7-8850H
32GB RAM
512 GB NVMe SSD

**Comment by mattock** [comment]
I'm not sure what it happening but looks like a local issue. Our installer [sets](https://github.com/OpenVPN/openvpn-build/blob/master/windows-nsis/openvpn.nsi#L411) OpenVPNServiceInteractive to startup type to "Automatic" if it is not present at install time. If it is present, the service startup type [is not touched](https://github.com/OpenVPN/openvpn-build/blob/master/windows-nsis/openvpn.nsi#L184). The installer does check if OpenVPNServiceInteractive is running and restarts it after upgrading it, but that does not affect startup type.

**Comment by sofakingdead** [comment]
I will test on a clean install of Windows 10 and see if it's just an issue with my setup.
