### ISSUE TITLE
[Feature Request] Portable Edition

### ISSUE THREAD

**Issue by seiya-git** [OpenVPN/openvpn-gui#307]
It's possible to make portable version of openvpn-gui?

**Comment by cron2** [comment]
To explain a bit more - openvpn-gui.exe "as it is"  could be made portable, but to be of any use, it needs the "OpenVPN interactive Service", and as far as I am aware, you can't make a "portable service" - and it needs the drivers (TAP-Windows6 / wintun / win-DCO), and these always require installation.
