### ISSUE TITLE
Feature request: allow to edit the config of imported profiles on all platforms

### ISSUE THREAD

**Issue by CodingSpiderFox** [OpenVPN/openvpn-gui#308]
I recently found that I'd like to use a different DNS server for my phone sometimes. I'd like to change my imported OVPN profile and add the DNS option (I think it was something like `push "dhcp-option DNS x.x.x.x"` that needs to be added to the config.

I don't want to go the extra mile editing the profile on PC, removing the one from the phone and importing a new one, having to enter the long password again

**Comment by selvanair** [comment]
This channel is for issues with OpenVPN-GUI which runs only on Windows. And it does allow you to edit configs. For other platforms such as IOS or Android please report to appropriate help/support channels for the product you are using.

**Comment by cron2** [comment]
Hi,

On Thu, Aug 08, 2019 at 10:51:39AM -0700, CodingSpiderFox wrote:
> I recently found that I'd like to use a different DNS server for my phone sometimes. I'd like to change my imported OVPN profile and add the DNS option (I think it was something like `push "dhcp-option DNS x.x.x.x"` that needs to be added to the config.
> 
> I don't want to go the extra mile editing the profile on PC, removing the one from the phone and importing a new one, having to enter the long password again

*This* github repo / issue tracker is for the Windows-Gui, so with
"I have a feature wish on my phone", you're totally off.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by CodingSpiderFox** [comment]
I can't even find an option in the windows app.

![image](https://user-images.githubusercontent.com/25173078/62726823-68b22e80-ba18-11e9-889b-c7299aefceea.png)
Where would I have to go inside the windows app?

**Comment by selvanair** [comment]
Again, this site is for OpenVPN-GUI, a Windows Desktop front-end for OpenVPN, which is a free software community product. "OpenVPN Connect" is closed-source software totally different from what we maintain here.

In case its still not clear, you are commenting about products unrelated to this repo. I have no idea how to get support for "OpenVPN Connect" -- please check the site where you downloaded it from.

**Comment by CodingSpiderFox** [comment]
OK. These different distributions were a bit confusing for me
