### ISSUE TITLE
OpenVPN, corporate proxy, connection timed out

### ISSUE THREAD

**Issue by instance2** [OpenVPN/openvpn-gui#310]
I installed OpenVPN at Amazon EC2 instance using AMI from OpenVPN with all the preinstalled packages. Tried to connect to VPN from home and everything works fine. The same with my phone(4g network). But when I'm trying to connect to the VPN from work computer it couldn't connect, with the reason `timeout`. Our network uses corporate proxy and we have to install corporate certificates for JVM and other tools using `keytool -importcert -trustcacerts ....` But I can't find where I should add the certificate at my OpenVPN GUI client. I use Windows 10 and `Client API 2.7.1.101/MSI`

The error log from `capi.log`
```
2019-08-21 16:27:51+0300 [HTTPChannel,1652,127.0.0.1] *** API CALL f=xmlrpc_Poll args=['sess_ge_1_12_123_1_p2598_7rNlia11aFsXQHSq_1', 10] kw={} ret=[{'timestamp': 1566394071, 'state': u'WAIT', 'type': 'STATE'}]
2019-08-21 16:27:52+0300 [MyOMIClient,0,127.0.0.1] FROM OMI: u">STATE:1566394072,TRANSPORT_ERROR,Transport error on '1.12.123.1: NETWORK_RECV_ERROR,,"
```

Connection log:
```
Wed Aug 21 15:47:46 2019 Wed Aug 21 15:47:46 2019 OpenVPN Management Interface 1.0.0/3.2 (qa:d87f5bbc04) win x86_64 64-bit [MbedTLS] built on Feb 26 2019 07:53:13
Wed Aug 21 15:47:46 2019 Wed Aug 21 15:47:46 2019 OMI Connecting to [127.0.0.1]:56132 [tcp]
Wed Aug 21 15:47:50 2019 Wed Aug 21 15:47:50 2019 OpenVPN core 3.2 (qa:d81f1bbc01) win x86_64 64-bit built on Feb 26 2019 07:53:13
Wed Aug 21 15:47:50 2019 Wed Aug 21 15:47:50 2019 Frame=512/2048/512 mssfix-ctrl=1250
Wed Aug 21 15:47:50 2019 Wed Aug 21 15:47:50 2019 UNUSED OPTIONS
4 [nobind] 
18 [sndbuf] [0] 
19 [rcvbuf] [0] 
22 [verb] [3] 
31 [CLI_PREF_ALLOW_WEB_IMPORT] [True] 
32 [CLI_PREF_BASIC_CLIENT] [False] 
33 [CLI_PREF_ENABLE_CONNECT] [True] 
34 [CLI_PREF_ENABLE_XD_PROXY] [True] 
35 [WSHOST] [1.12.123.1:443] 
36 [WEB_CA_BUNDLE] [-----BEGIN CERTIFICATE----- MIIDBjCZAe6gAwIBAgIEXVwafTANBgaqhkiG...] 
37 [IS_OPENVPN_WEB_CA] [1] 
38 [ORGANIZATION] [OpenVPN Inc] 
Wed Aug 21 15:47:50 2019 Wed Aug 21 15:47:50 2019 RESOLVE
Wed Aug 21 15:47:50 2019 Wed Aug 21 15:47:50 2019 Contacting 1.12.123.1:1194 via UDP
Wed Aug 21 15:47:50 2019 Wed Aug 21 15:47:50 2019 WAIT
Wed Aug 21 15:47:50 2019 Wed Aug 21 15:47:50 2019 Connecting to [1.12.123.1]:1194 (1.12.123.1) via UDPv4
Wed Aug 21 15:47:54 2019 Wed Aug 21 15:47:54 2019 Server poll timeout, trying next remote entry...
Wed Aug 21 15:47:54 2019 Wed Aug 21 15:47:54 2019 RECONNECTING
Wed Aug 21 15:47:54 2019 Wed Aug 21 15:47:54 2019 Contacting 1.12.123.1:1194 via UDP
...
Wed Aug 21 15:48:50 2019 Wed Aug 21 15:48:50 2019 WAIT
Wed Aug 21 15:48:50 2019 Wed Aug 21 15:48:50 2019 CONNECTION_TIMEOUT [FATAL-ERR]
Wed Aug 21 15:48:50 2019 Wed Aug 21 15:48:50 2019 DISCONNECTED
Wed Aug 21 15:48:50 2019 Wed Aug 21 15:48:50 2019 >FATAL:CONNECTION_TIMEOUT
```

How can I set corporate Root Ca certificate to connect to the VPN server? Thanx.

**Comment by cron2** [comment]
Hi,

On Wed, Aug 21, 2019 at 11:23:58PM -0700, instance2 wrote:
> I installed OpenVPN at Amazon EC2 instance using AMI from OpenVPN with all the preinstalled packages. Tried to connect to VPN from home and everything works fine. The same with my phone(4g network). But when I'm trying to connect to the VPN from work computer it couldn't connect, with the reason `timeout`. Our network uses corporate proxy and we have to install corporate certificates for JVM and other tools using `keytool -importcert -trustcacerts ....` But I can't find where I should add the certificate at my OpenVPN GUI client. I use Windows 10 and `Client API 2.7.1.101/MSI`

This is not a "openvpn gui development" related question, so better
suited on the openvpn-users lists or in the openvpn forum, or in the
commercial support you got for the commercial OpenVPN products you use.

But anyway, the problem might be "corporate proxy which breaks up SSL"
(so you need to install your own certificate).  Since OpenVPN is not using
traditional SSL, this sort of proxies will not work.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de
