### ISSUE TITLE
Autostart only works through Task Scheduler

### ISSUE THREAD

**Issue by lanmarti** [OpenVPN/openvpn-gui#315]
I'm using openVPN GUI v2.4 on Windows 10.
Activating the 'auto-startup' setting in the settings menu or trying to add the shortcut to Windows' autostart folder neither cause OpenVPN to start at boot. I assume this is because a UAC window pops up when trying to run it.
I created a TaskScheduler task running with highest privileges, which does work, yet sadly, the GUI disappears from the system tray after leaving sleep mode, so I have to manually kill the process and restart the GUI when I want to modify connections. I've been using this solution for months, but am getting tired of having to restart the process so often.

I read that v2.4 doesn't require admin privileges when the openVPN interactive service is running (which is the case), yet either something went wonky when upgrading from a previous version or the UAC messages are something separate from the admin privileges?

Is there a way to skip the UAC window (I tried running the shortcut as admin, to no avail) or is there another solution I can try?

**Comment by selvanair** [comment]
If you manually start OpenVPN-GUI by just double clicking on the short cut icon, does UAC window popup? If it does, somewhere it has been set to run with admin privileges. Check the properties of the shortcut (both advanced and compatibility tabs). If starting the executable directly (the GUI exe in C:\Program Files\OpenVPN\bin) also pops up UAC, either the manifest has been modified or some registry hack is in place to make it do so. As our installer doesn't do this, you will have to figure it out.

As you noted the 2.4 GUI is supposed to be run as a limited user (no elevated privileges). And autostarting the GUI on logon should just work by enabling it in the settings.

**Comment by lanmarti** [comment]
Ah yes, the executable itself was set to run as administrator, probably from some earlier attempts before I got to the TaskScheduler method. Removing the administrator rights has fixed it, thanks!
