### ISSUE TITLE
No connection on win 10 pro v1903 on Intel wireless N-7260

### ISSUE THREAD

**Issue by JMRexach** [OpenVPN/openvpn-gui#316]
Hi,

I'm triing to conect to free vpnbook servers using win 10 and a wireless Intel dual band N-7260 adapter without sucess. Using wired adapter works fine. It disables the wifi adapter at the end of the connection and cann't be enabled until vpn disconects, then works fine. Icon doesn't trogle to green state and says "connecting".

Versions:
openvpn 2.47-i607.win10
Open vpn gui: v. 11.13.0.0
Windows 10 pro v. 1903
Intel Dual band wireless adapter N-7260 controller v: 18.33.17.1
I send you the log of connection.
[vpnbook-fr8-tcp443.log](https://github.com/OpenVPN/openvpn-gui/files/3723920/vpnbook-fr8-tcp443.log)
Thanks for your time in advance,
B.R.

JMa

**Comment by selvanair** [comment]
If WiFi is getting disconnected when the tunnel adapter comes up, this may be the same bug that was reported on some HP laptops. In such cases, the logs would normally show error at route addition stage, but your logs report success at first instance, followed by a ping restart that fails to resolve the remote host. But could be the same issue.

If so, a fix has been merged (https://github.com/OpenVPN/tap-windows6/pull/94) and should be available in the next release.
If you wish to test this, try the following which will update the tap-windows driver.
https://build.openvpn.net/downloads/temp/tap-windows-9.24.2-I601.exe  (untested).

**Comment by JMRexach** [comment]
Thank you selvanair. It works. It's a HP notebook! I'll test more in depth but now it's working.
