### ISSUE TITLE
Add --update command to fetch newly added config files

### ISSUE THREAD

**Issue by jodel9227** [OpenVPN/openvpn-gui#319]
It would be nice to have the ability to tell the gui to fetch newly added config files. Right now, when the gui is running with an opened connection and we add config files, we can't connect a second connection because it doesn't recognize the .ovpn files until we interact directly with the trayicon.

**Comment by selvanair** [comment]
@jodel9227 Are you referring to use cases like the following?

With an instance of GUI running
(i) copy a new config file (foo.ovpn) to the config folder
(ii) run `openvpn-gui --command rescan`   <-- feature request
(iii) connect foo using `openvpn-gui --command connect foo`

If so, please test the implementation [here](https://github.com/selvanair/openvpn-gui/tree/command-rescan).

**Comment by jodel9227** [comment]
Yes that works like a charm, thanks a lot for the quick response !

One thing though. Would it be possible to make this work for config files located in Local AppData ? Right now multiple connections only work when config files are in Program Files/OpenVPN or Users/user123/OpenVPN. We'd rather not use these locations if at all possible. Thanks !

**Comment by selvanair** [comment]
You can change the user's config directory in the settings menu of the GUI
see: settings->Advanced 
Full paths or variable such as %AppData%\foo\bar are accepted. It defaults to %UserProfile%\OpenVPN\config

The global config diretory is set in HKLM\Programs\OpenVPN\ and can only be changed by an admin. Scroll down the repo landing page and you'll find more details on these (https://github.com/OpenVPN/openvpn-gui)

**Comment by jodel9227** [comment]
Alright everything works fine now, thanks for your help !

**Comment by jodel9227** [comment]
Do you by any chance know when this new command will be included in a release ?

**Comment by selvanair** [comment]
Hopefully in the next release if we get a code review.

**Comment by jodel9227** [comment]
Hello, just getting an update on this. We have customers waiting and would like to give them an ETA. 

Thanks !

**Comment by selvanair** [comment]
@jodel9227 This has been merged and will be in the next release -- both in 2.4.9 and 2.5.0, but I don't have a date for either.
