### ISSUE TITLE
Installation fails with "incorrect" installer name

### ISSUE THREAD

**Issue by Nightmaster** [OpenVPN/openvpn-gui#322]
Hello. 

I found a small but annoying problem with the installer. If the installer itself is name "openvpn.exe" (case insensitive, I think, but not sure), the installation process fails cause it tries to kill all "openvpn.exe" processes, and in this case itself...

Solution came from an [old post on the forum](https://forums.openvpn.net/viewtopic.php?t=20892). If this problem could be solved it would be great!

Thanks in advance

**Comment by cron2** [comment]
Hi,

On Wed, Nov 27, 2019 at 02:51:40AM -0800, BLAISE wrote:
> I found a small but annoying problem with the installer. If the installer itself is name "openvpn.exe" (case insensitive, I think, but not sure), the installation process fails cause it tries to kill all "openvpn.exe" processes, and in this case itself...
> 
> Solution came from an [old post on the forum](https://forums.openvpn.net/viewtopic.php?t=20892). If this problem could be solved it would be great!

This is very much a case of "pilot error".  Don't rename installers
to the same name of the program they will install.  Nothing good will
ever come out of it.

@mattock: can we make the installer abort if called as openvpn.exe?

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by chipitsine** [comment]
an idea to stop processes is to unlock executable files. however, it might be TOO offensive. killing openvpn.exe does not mean it is exactly the binary we are trying to override.

maybe we should find more intelligent way ?
@rozmansi , @mattock as for MSI installer, how close are we to it ? does MSI provide such intelligent way to override locked files ?

**Comment by chipitsine** [comment]
and answering to "can we make the installer abort..." - it seems to make sense. I'll send patch soon

**Comment by mattock** [comment]
@chipitsine thanks! That would definitely useful.
