### ISSUE TITLE
ROUTE: route addition failed using CreateIpForwardEntry: The parameter is incorrect.   [status=87 if_index=6]

### ISSUE THREAD

**Issue by kbdavis07** [OpenVPN/openvpn-gui#324]
Keep getting this Error when connecting:

ROUTE: route addition failed using CreateIpForwardEntry: The parameter is incorrect.   [status=87 if_index=6]

Full Error Log:

Tue Dec 03 17:40:47 2019 OpenVPN 2.4.8 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Oct 31 2019
Tue Dec 03 17:40:47 2019 Windows version 6.2 (Windows 8 or greater) 64bit
Tue Dec 03 17:40:47 2019 library versions: OpenSSL 1.1.0l  10 Sep 2019, LZO 2.10
Enter Management Password:
Tue Dec 03 17:40:47 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Dec 03 17:40:47 2019 SIGUSR1[soft,private-key-password-failure] received, process restarting
Tue Dec 03 17:41:06 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]52.32.119.134:1194
Tue Dec 03 17:41:06 2019 UDP link local: (not bound)
Tue Dec 03 17:41:06 2019 UDP link remote: [AF_INET]52.32.11x.xxx:1194
Tue Dec 03 17:41:07 2019 [vpn.jxxxxxxxx.com] Peer Connection Initiated with [AF_INET]52.32.11x.xxx:1194
Tue Dec 03 17:41:08 2019 open_tun
Tue Dec 03 17:41:08 2019 TAP-WIN32 device [Local Area Connection] opened: \\.\Global\{BB2C7112-5991-40A7-821A-BD3A3EA5FAA5}.tap
Tue Dec 03 17:41:08 2019 Notified TAP-Windows driver to set a DHCP IP/netmask of 192.168.245.6/255.255.255.252 on interface {BB2C7112-5991-40A7-821A-BD3A3EA5FAA5} [DHCP-serv: 192.168.245.5, lease-time: 31536000]
Tue Dec 03 17:41:08 2019 Successful ARP Flush on interface [6] {BB2C7112-5991-40A7-821A-BD3A3EA5FAA5}
Tue Dec 03 17:41:13 2019 Warning: address 10.1.0.0 is not a network address in relation to netmask 255.0.0.0
Tue Dec 03 17:41:13 2019 ROUTE: route addition failed using CreateIpForwardEntry: The parameter is incorrect.   [status=87 if_index=6]
Tue Dec 03 17:41:13 2019 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Tue Dec 03 17:41:13 2019 Initialization Sequence Completed

I Right Click and "Run as Admin"  still have same issue.

This is an AWS Server with VPN Set up, trying to connect as a client from a Windows 10 Pro Desktop.

Mac users seems not to have any issue, just with Windows seems to be the issue.

**Comment by selvanair** [comment]
As the log says, the route you are trying to add seems to be wrongly specified. Need log at verb=4 to be sure, but looks like you have `route 10.1.0.0 255.0.0.0` but you probably mean `route 10.0.0.0 255.0.0.0`. Mac may be forgiving.

Apart from that, the log you posted is  from a "Run as admin: session". The recommended way to run the GU in in 2.4.0 plus versions is as user. Run as admin is no longer supported.

**Comment by cron2** [comment]
Hi,

On Tue, Dec 03, 2019 at 03:18:43PM -0800, Brian Davis wrote:
> Tue Dec 03 17:41:13 2019 Warning: address 10.1.0.0 is not a network address in relation to netmask 255.0.0.0

This.

If you want to route 10.1.0.0/16, then pass a netmask of 255.255.0.0.

If you want to route 10.0.0.0/8, then pass "10.0.0.0", not 10.1.0.0

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by kbdavis07** [comment]
Hi @cron2 

> If you want to route 10.1.0.0/16, then pass a netmask of 255.255.0.0.

Where do I do this from?

The Client Side?

Or Server Side where the VPN server is located at?

Thanks 👍

**Comment by cron2** [comment]
Hi,

On Wed, Dec 04, 2019 at 06:48:10AM -0800, Brian Davis wrote:
> > If you want to route 10.1.0.0/16, then pass a netmask of 255.255.0.0.
> 
> Where do I do this from?
> 
> The Client Side?
> 
> Or Server Side where the VPN server is located at?

It could be in the client config ("route 10.1.0.0 255.0.0.0") or in the
server config ("push route ...").

Whever you set it up :-)

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by kbdavis07** [comment]
Hi @cron2 

This is current client.ovpn file

client
nobind
dev tun
remote-cert-tls server
remote VPN.Domain.com 1194 udp
route 10.1.0.0 255.0.0.0

<key>



Still get the following Errors:


Wed Dec 04 10:03:23 2019 OpenVPN 2.4.8 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Oct 31 2019
Wed Dec 04 10:03:23 2019 Windows version 6.2 (Windows 8 or greater) 64bit
Wed Dec 04 10:03:23 2019 library versions: OpenSSL 1.1.0l  10 Sep 2019, LZO 2.10
Enter Management Password:
Wed Dec 04 10:03:23 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Wed Dec 04 10:03:23 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]5x.3x.1xx.1xx:1194

Wed Dec 04 10:03:23 2019 UDP link local: (not bound)
Wed Dec 04 10:03:23 2019 UDP link remote: [AF_INET]5x.3x.1xx.1xx:1194
Wed Dec 04 10:03:24 2019 [vpn.domain.com] Peer Connection Initiated with [AF_INET]5x.3x.1xx.1xx:1194

Wed Dec 04 10:03:25 2019 open_tun
Wed Dec 04 10:03:25 2019 TAP-WIN32 device [Local Area Connection] opened: \\.\Global\{BB2C7112-5991-40A7-821A-BD3A3EA5FAA5}.tap

Wed Dec 04 10:03:25 2019 Notified TAP-Windows driver to set a DHCP IP/netmask of 192.168.245.6/255.255.255.252 on interface {BB2C7112-5991-40A7-821A-BD3A3EA5FAA5} 
                         [DHCP-serv: 192.168.245.5, lease-time: 31536000]

						 
						 
Wed Dec 04 10:03:30 2019 Warning: address 10.1.0.0 is not a network address in relation to netmask 255.0.0.0

Wed Dec 04 10:03:30 2019 ROUTE: route addition failed using CreateIpForwardEntry: Access is denied.   [status=5 if_index=6]
Wed Dec 04 10:03:30 2019 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Dec 04 10:03:30 2019 ERROR: Windows route add command failed [adaptive]: returned error code 1
Wed Dec 04 10:03:30 2019 Warning: address 10.1.0.0 is not a network address in relation to netmask 255.0.0.0
Wed Dec 04 10:03:30 2019 ROUTE: route addition failed using CreateIpForwardEntry: Access is denied.   [status=5 if_index=6]
Wed Dec 04 10:03:30 2019 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Dec 04 10:03:30 2019 ERROR: Windows route add command failed [adaptive]: returned error code 1
Wed Dec 04 10:03:30 2019 ROUTE: route addition failed using CreateIpForwardEntry: Access is denied.   [status=5 if_index=6]
Wed Dec 04 10:03:30 2019 env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Wed Dec 04 10:03:30 2019 ERROR: Windows route add command failed [adaptive]: returned error code 1
Wed Dec 04 10:03:30 2019 Initialization Sequence Completed


If you need any additional information please let me know, really need to get this fixed :) 

Client Computer is a Windows 10 DeskTop Pro if that helps any.

**Comment by cron2** [comment]
Hi,

On Wed, Dec 04, 2019 at 07:10:00AM -0800, Brian Davis wrote:
> This is current client.ovpn file
> 
> client
> nobind
> dev tun
> remote-cert-tls server
> remote VPN.Domain.com 1194 udp
> route 10.1.0.0 255.0.0.0

This.  This is precisely what it is complaining about: a netmask of
255.0.0.0 is not correct for a base address of 10.1.0.0 - make up
your mind what you want (10.0.0.0 255.0.0.0 or 10.1.0.0 255.255.0.0) 
and configure correctly.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by selvanair** [comment]
> This is current client.ovpn file
> 
> client
> nobind
> dev tun
> remote-cert-tls server
> remote VPN.Domain.com 1194 udp
> route 10.1.0.0 255.0.0.0
change that last line to

route 10.1.0.0 255.255.0.0
OR
route 10.0.0.0 255.0.0.0

Only you can decide which of those two (or something else) that you want. 

Both Gert and I wrote this multiple times already. If you need further help, the mailing list or IRC may be a better forum, not github issues.

**Comment by kbdavis07** [comment]
Hi @selvanair  and @cron2 

That fixed it!!!

Thanks for your help.

I missed typed the IP, and copied and pasted what you have into the .ovpn file and so far seems to be working finally!

👍

**Comment by rauanbag** [comment]
Advanced Configuration -> Custom options -> delete (push "route 10.0.0.0 255.255.255.0")
and 
Intaerface -> LAN -> Add -> LAN Gateway(don't default gateway)
