### ISSUE TITLE
Change password & static challenge transmission order

### ISSUE THREAD

**Issue by getle87** [OpenVPN/openvpn-gui#325]
Hello,

this is my first post here, so sorry for my bad English. Is there any possibility to change the order of password and OTP (static-challenge config option) in the OpenVPN client? The client seems to transmit the credentials in the order <otp>+<password>. In OPNsense I can switch the order on the OpenVPN server, but in some other commerical devices (ex. Sophos UTM) the order is fixed to <password>+<otp>, so the authentification doesn't work here with the client GUI. When I enter <password>+<otp> in the password field of the GUI, it works.

I use the following programs:

GUI: OpenVPN GUI V11.00.0.0 (Windows 10 x64) bundled with OpenVPN CE 2.4.8 (openvpn-install-2.4.8-I602-Win10.exe)
Client: OpenVPN 2.4.8 CE (Windows 10 x64) bundled with OpenVPN CE 2.4.8 (openvpn-install-2.4.8-I602-Win10.exe)
Servers: Various, OpenVPN 2.4.8 CE (embedded in OPNSense), Sophos UTM 9.6 (I know you don't support them, but it works if the otp is transmitted after the password)

The OTP is simple standard TOTP (SHA1, 6 digits), which is added before or after the password. When I use the static-challenge option in the config, the GUI displays an extra field for the OTP, then the otp is added before the password. I only want to know if there is a way to force the GUI to add the otp after the password. If not I want to open a feature request for this.

Do you need any additional information?

**Comment by selvanair** [comment]
I suspect there is some misunderstanding of how password and otp are transmitted to the server.

The recommended way to use OTP is to use the static challenge option in the config.  In that case the protocol used for transporting password + otp from the client to server is determined by OpenVPN core. The GUI just follows that. If a particular server is not parsing it correctly, the server-side verification script or plugin should be fixed. 

When you use static challenge, the user has to input password and OTP into their respective field. The GUI packages them and passes on. I am not sure what you mean by the order -- there is only one way to package it to be compliant with the documentation. And that is 
`SCRV1:<password-in-base64>:<otp-in-base64>`
Server-side script/plugin/whatever your server uses for password verification has to parse that and do the verification. 

I think recent versions of OpenSense does support static-challenge protocol and it should just work if you add static-challenge option to the client config and use the GUI in 2.4.x releases.

If you do not use static challenge, but ask the user to input both password and otp into the "password" field, whatever the user writes in that field is passed "as is" to the server. You have to find what order and separator (if any) that the server-side verification expects, and ask the user to input it accordingly. OpenSense has some options like "reverse token order" etc. which may affect how this is parsed, so check their docs. That said I would recommend to use the static-challenge option.
