### ISSUE TITLE
Enter Management Password

### ISSUE THREAD

**Issue by davidsarkany** [OpenVPN/openvpn-gui#328]
Hi!

I upgraded a laptop from Windows 7 to Windows 10.
openvpn-gui.exe can't connect I see this on logs:

> Sat Jan 11 22:30:47 2020 OpenVPN 2.4.8 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Oct 31 2019
> Sat Jan 11 22:30:47 2020 Windows version 6.2 (Windows 8 or greater) 64bit
> Sat Jan 11 22:30:47 2020 library versions: OpenSSL 1.1.0l  10 Sep 2019, LZO 2.10
> Enter Management Password:

I can connect when i start directly openvpn.exe

> taskkill.exe /F /IM openvpn.exe
> taskkill.exe /F /IM openvpn-gui.exe
> timeout 2
> openvpn --config "C:\Program Files\OpenVPN\config\cert.ovpn"

I try start openvpn-gui with arguments from the command line, but I got the same error.

**Comment by TinCanTech** [comment]
Looks a lot like this:
https://community.openvpn.net/openvpn/wiki/OpenVPN-GUI-New#gui-moreinfo

**Comment by davidsarkany** [comment]
@TinCanTech I tried. I disabled OpenVPNService and the OpenVPN Legacy Service.
Not work. (I restarted the laptop)

Today openvpn-gui magically started working.
