### ISSUE TITLE
OpenVPN new setup, Server poll timeout issue

### ISSUE THREAD

**Issue by kiran044** [OpenVPN/openvpn-gui#330]
Hi,

I have created new pivpn setup in my raspi and create a profile to test, but unable to connect with below error. Can you help on what I'm doing wrong

### Using Static local Ip, Raspi connected via wireless network (wlan0)
192.168.0.102, udp 
Port forwarding default port (1194) enabled in router.

### OpenVPN Connect Log

22:10:06.873 -- EVENT: RECONNECTING
22:10:06.906 -- EVENT: RESOLVE
22:10:06.929 -- Contacting 183.83.xxx.xx:1194 via UDP
22:10:06.930 -- EVENT: WAIT
22:10:06.947 -- Connecting to [183.83.xxx.xx]:1194 (183.83.xxx.xx) via UDPv4
22:10:16.877 -- Server poll timeout, trying next remote entry...

### /var/log/openvpn.log

Jan 24 16:38:31  ovpn-server[4697]: event_wait : Interrupted system call (code=4)
Jan 24 16:38:31  ovpn-server[4697]: Closing TUN/TAP interface
Jan 24 16:38:31  ovpn-server[4697]: /sbin/ip addr del dev tun0 10.8.0.1/24
Jan 24 16:38:31  ovpn-server[4697]: Linux ip addr del failed: external program exited with error status: 2
Jan 24 16:38:31  ovpn-server[4697]: SIGTERM[hard,] received, process exiting
Jan 24 16:38:31  ovpn-server[6152]: OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Jan 24 16:38:31  ovpn-server[6152]: library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Jan 24 16:38:31  ovpn-server[6152]: NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
Jan 24 16:38:31  ovpn-server[6152]: ECDH curve prime256v1 added
Jan 24 16:38:31  ovpn-server[6152]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Jan 24 16:38:31  ovpn-server[6152]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan 24 16:38:31  ovpn-server[6152]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Jan 24 16:38:31  ovpn-server[6152]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan 24 16:38:31  ovpn-server[6152]: TUN/TAP device tun0 opened
Jan 24 16:38:31  ovpn-server[6152]: TUN/TAP TX queue length set to 100
Jan 24 16:38:31  ovpn-server[6152]: /sbin/ip link set dev tun0 up mtu 1500
Jan 24 16:38:31  ovpn-server[6152]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Jan 24 16:38:31  ovpn-server[6152]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Jan 24 16:38:31  ovpn-server[6152]: Socket Buffers: R=[163840->163840] S=[163840->163840]
Jan 24 16:38:31  ovpn-server[6152]: UDPv4 link local (bound): [AF_INET][undef]:1194
Jan 24 16:38:31  ovpn-server[6152]: UDPv4 link remote: [AF_UNSPEC]
Jan 24 16:38:31  ovpn-server[6152]: GID set to openvpn
Jan 24 16:38:31  ovpn-server[6152]: UID set to openvpn
Jan 24 16:38:31  ovpn-server[6152]: MULTI: multi_init called, r=256 v=256
Jan 24 16:38:31  ovpn-server[6152]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Jan 24 16:38:31  ovpn-server[6152]: Initialization Sequence Completed

### /etc/openvpn/server.conf

dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/KRPHS_0cb89d39-8e8b-4b59-b666-cc7fd65b070f.crt
key /etc/openvpn/easy-rsa/pki/private/KRPHS_0cb89d39-8e8b-4b59-b666-cc7fd65b070f.key
dh none
ecdh-curve prime256v1
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 9.9.9.9"
push "dhcp-option DNS 149.112.112.112"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io

**Comment by selvanair** [comment]
This place is for reporting issues with Windows OpenVPN-GUI, not for generic questions about using openvpn core or clients other than OpenVPN-GUI. Ask in openvpn users mailing list, users forum or irc (see https://community.openvpn.net/openvpn/wiki/GettingHelp).

Likely, traffic to UDP 1194 on the server (pi) is not passing through your router or is blocked by some firewall elsewhere.
