### ISSUE TITLE
Feature request: mark ovpns that are in "connecting" state

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn-gui#331]
Currently connected profiles (ovpns) get a green tick mark against it, those waiting for connection (in the connecting state) are not marked. This makes it difficult to figure out the status of individual profiles especially when there are many of them. 

This is a pointer to the feature wish at [Trac1241](https://community.openvpn.net/openvpn/ticket/1241)

**Comment by selvanair** [comment]
Here is my working branch on this. 
https://github.com/selvanair/openvpn-gui/tree/checkmark
A test executable is here:
https://github.com/selvanair/openvpn-gui/releases/tag/checkmark
Any feed back would be appreciated -- especially on the appearance on different DPI displays.

The "connected" and "connecting" icons are used to mark the state instead of a tick-mark against connected profiles only. In case of nested configs the parent menus just get a tick-mark and only the actual profile gets marked with the icon bitmap.

This just uses bitmaps extracted from existing icons (with no masking) but ideally one could use bitmaps designed for this purpose. If anyone wants to supply bitmaps/icons, I'll be more than happy to use them.

**Comment by LoZio** [comment]
+1 on this. I usually have several VPN up and there is no obvious way to see which are down/reconnecting, only the connected ones are checked.

**Comment by selvanair** [comment]
Feature added by PR #390
