### ISSUE TITLE
OpenVPN Client Triggered As Malicious 

### ISSUE THREAD

**Issue by g33xter** [OpenVPN/openvpn-gui#335]
Hi,

I recently scanned windows binary of OpenVpn (openvpn-install-2.4.8-I602-Win10.exe) directly downloaded from official website. I scanned through Hybrid-Analysis service, and it detected it as malicious. If you want to check, search this hash d8f861de1519c680c4e506b4e08b4d80db7c385a4ccc2fcc56e2278d41c1cabe on hybrid-analysis or you can visit the link to see the report hxxps://hybrid-analysis.com/sample/d8f861de1519c680c4e506b4e08b4d80db7c385a4ccc2fcc56e2278d41c1cabe
<img width="1143" alt="Screen Shot 2020-03-02 at 02 10 06" src="https://user-images.githubusercontent.com/8503135/75666636-01193600-5c2b-11ea-9e1c-22eef50f89a2.png">

**Comment by devZer0** [comment]
mhh, virustotal is telling it's clean  https://www.virustotal.com/gui/url/658199568ba8381c1150bf5d1785135f816e65537c38fe8760820795e9895dff/detection

**Comment by selvanair** [comment]
Closing as we can't possibly do anything about third party virus scans,
