### ISSUE TITLE
OpenVPN GUI and OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by t0r3n0** [OpenVPN/openvpn-gui#338]
According to https://www.openssl.org/source/ any version that isn't 1.1.1 is not supported and "should not be used". So why hasn't OpenVPN GUI moved to 1.1.1 yet, not only as anything else "should not be used" but it is the only link in the chain between my linux-based server and my Windows clients that is preventing use of TLS 1.3. Will this come with the implementation of OpenVPN 2.5? If not, when?

**Comment by selvanair** [comment]
We have merged all patches required to support 1.1.1 on Windows, so its only a question of the release build. I think 2.5 windows release will be built with OpenSSL 1.1.1.

**Comment by selvanair** [comment]
The latest release 2.4.9 is built with OpenSSL 1.1.1f. Please upgrade.
