### ISSUE TITLE
Password box popping up for no reason

### ISSUE THREAD

**Issue by FolkSong** [OpenVPN/openvpn-gui#339]
Every so often while connected (maybe every hour or so), the password dialog pops up. I have my password saved so it goes away on its own after 5 seconds. But the thing is, I'm using Remote Desktop and don't notice any interruption. And the log doesn't show any activity since I originally connected hours ago. Maybe there's a good explanation but from my perspective it appears to be popping up for no reason.

Using OpenVPN v2.4.8, GUI v11.14.0.0

**Comment by selvanair** [comment]
You may have --auth-nocache in the client config which prevents openvpn core from caching the password. The core needs the password during renegotiation (by default every hour) and will prompt for it if not cached. Unless you have some strong reason not to allow it, remove --auth-nocache from the config.

**Comment by FolkSong** [comment]
Thanks very much. I did indeed have auth-nocache in my config. Removing it seems to fix the issue, although I get a red security warning in the log about it. But I guess I'm already storing the password in memory through the GUI so it's not much additional risk.
