### ISSUE TITLE
not connected to portmap.io from last 2 days

### ISSUE THREAD

**Issue by Haseeb-Pervaiz** [OpenVPN/openvpn-gui#342]
here is a log please help
Sat Mar 21 15:58:59 2020 OpenVPN 2.4.8 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Oct 31 2019
Sat Mar 21 15:58:59 2020 Windows version 6.2 (Windows 8 or greater) 64bit
Sat Mar 21 15:58:59 2020 library versions: OpenSSL 1.1.0l  10 Sep 2019, LZO 2.10
Enter Management Password:
Sat Mar 21 15:59:00 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]193.161.193.99:1194
Sat Mar 21 15:59:00 2020 Attempting to establish TCP connection with [AF_INET]193.161.193.99:1194 [nonblock]
Sat Mar 21 16:01:00 2020 TCP: connect to [AF_INET]193.161.193.99:1194 failed: Unknown error
Sat Mar 21 16:01:00 2020 SIGUSR1[connection failed(soft),init_instance] received, process restarting

**Comment by ghostsudo98** [comment]
what to do?

**Comment by selvanair** [comment]
Contact your VPN provider: portmap.io in this case.
