### ISSUE TITLE
Configure: error: This project is supported for windows only.

### ISSUE THREAD

**Issue by ikreb7** [OpenVPN/openvpn-gui#344]
I tried the [MYSYS2 manual](https://github.com/OpenVPN/openvpn-gui/blob/master/BUILD.rst#how-to-build-using-msys2). But I get this error message if I run ``configure``.

> $ ./configure
> configure: loading site script /etc/config.site
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking build system type... x86_64-pc-msys
> checking host system type... x86_64-pc-msys
> checking whether make supports the include directive... yes (GNU style)
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.exe
> checking for suffix of executables... .exe
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking dependency style of gcc... gcc3
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking minix/config.h usability... no
> checking minix/config.h presence... no
> checking for minix/config.h... no
> checking whether it is safe to define __EXTENSIONS__... yes
> checking for gcc option to accept ISO C99... none needed
> checking for windres... windres
> configure: error: This project is supported for windows only.

**Comment by selvanair** [comment]
I don't use msys, but it seems you are not using mingw:
> checking build system type... x86_64-pc-msys
should be x86_64-pc-mingw64
