### ISSUE TITLE
Make clear this repo is the official one

### ISSUE THREAD

**Issue by ffes** [OpenVPN/openvpn-gui#35]
At the moment the description above this repo here on GitHub says it is a fork of the official repo at sourceforge. If I understand correctly the repo at sourceforge is not maintained anymore and this it official one now.

So I would suggest to change the description of the repo. And ideally adjust the README and put a message on sourceforge as well.

**Comment by kq01526** [comment]
+1

**Comment by mattock** [comment]
I fixed the GitHub project description, but I do not have access to the OpenVPN-GUI SF.net right now. I should be able to fix this in a couple of weeks, when we have the OpenVPN hackathon. I suggest that we modify the project description on SF.net to say something like this:

    NOTE: the official OpenVPN-GUI repository has been migrated to
    https://github.com/OpenVPN/openvpn-gui

This would avoid the need to modify README.rst.

**Comment by mattock** [comment]
I managed to get admin access to the SF.net project already.The project has now been set to "relocated" state. I also added the GitHub URL to the project description:

* https://sourceforge.net/projects/openvpn-gui/

Is this a sufficient fix in your opinion?

**Comment by ffes** [comment]
> Is this a sufficient fix in your opinion?

To me it is. So closing this one.
