### ISSUE TITLE
How to run script.bat inside the ovpn file?

### ISSUE THREAD

**Issue by ememachado** [OpenVPN/openvpn-gui#350]
No meu trampo usamos o Sophos SSL VPN Client. Preciso de ajuda para executar um script.bat depois que a VPN é conectada. Tem como editar e colocar dentro do arquivo de configuração *.ovpn? 

In my job we use the Sophos SSL VPN Client. I need help to run a script.bat after the VPN is connected. Is it possible to edit and place it inside the * .ovpn configuration file?

**Comment by selvanair** [comment]
Two methods:

1. Use  `--up <path-to-script>` as described in the OpenvPN man page 
 
2. Name the script as `<config-name>_up.bat` and drop it into the same folder as the ovpn file. Here `<config_name>` is the name of the ovpn file without the `.ovpn` extension.  For more on the latter see [here](https://github.com/OpenVPN/openvpn-gui#run-connectdisconnectpreconnect-scripts) -- its executed after the connection is fully established.
 
First one is  executed by OpenVPN core and requires `script-security 2` while the second one is executed by the GUI. I recommend the latter.

**Comment by ememachado** [comment]
> Dois métodos:
> 
> 1. Use   `--up <path-to-script>`conforme descrito na página de manual do OpenvPN
> 2. Nomeie o script como `<config-name>_up.bat`e solte-o na mesma pasta do arquivo ovpn. Aqui `<config_name>`está o nome do arquivo ovpn sem a `.ovpn`extensão. Para obter mais informações sobre o último, consulte [aqui](https://github.com/OpenVPN/openvpn-gui#run-connectdisconnectpreconnect-scripts) - ele é executado após a conexão estar totalmente estabelecida.
> 
> O primeiro é executado pelo núcleo OpenVPN e requer `script-security 2`enquanto o segundo é executado pela GUI. Eu recomendo o último.

Ótimo, vou testar.. Sumi um pouco, muitos projetos. Obrigado pela ajuda.

**Comment by ememachado** [comment]
Ótimo, vou testar .. Sumi um pouco, muitos projetos. Obrigado pela ajuda.
