### ISSUE TITLE
OpenVPN connection fails with unexpected EOF for large requests

### ISSUE THREAD

**Issue by theodiefenthal** [OpenVPN/openvpn-gui#353]
In our company, we have a private docker registry, accessible from home only via OpenVPN.

With the latest `Docker for Windows`, if I perform a `docker pull some_large_image`, after a while, I receive `unexpected EOF` and the download is canceled. This happens reproduceable so that there is no way for me to download the image. 

If with the exact notebook I perform the same `docker pull` command in the company intranet attached via LAN (and without the need to use OpenVPN), the command works fine every time. So I expect this to be some issue with OpenVPN or our configuration. 

My environment is Windows 10 professional, tested with 1910 and 2004. I use the latest OpenVPN GUI for windows. 
Here is my OpenVPN config:

```
client
dev tun
proto udp
remote vpn.REMOVED.de 22194
verify-x509-name "REMOVED"
resolv-retry infinite
nobind
persist-key
persist-tun
auth-user-pass
cipher AES-256-GCM
auth SHA384
route-delay 4
verb 3
reneg-sec 0
tun-mtu 1500
fragment 1300
mssfix
<tls-crypt>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
REMOVED
-----END OpenVPN Static key V1-----
</tls-crypt>
<ca>
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            REMOVED
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: REMOVED
        Validity
            Not Before: REMOVED
            Not After : REMOVED
        Subject: REMOVED
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (384 bit)
                pub: 
                    REMOVED
                ASN1 OID: secp384r1
                NIST CURVE: P-384
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                REMOVED
            X509v3 Authority Key Identifier: 
                REMOVED

            X509v3 Basic Constraints: 
                CA:TRUE
            X509v3 Key Usage: 
                Certificate Sign, CRL Sign
    Signature Algorithm: ecdsa-with-SHA256
         REMOVED
-----BEGIN CERTIFICATE-----
REMOVED
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
REMOVED
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN PRIVATE KEY-----
REMOVED
-----END PRIVATE KEY-----
</key>
```

Is this a bug in OpenVPN or any misconfiguration?

**Comment by theodiefenthal** [comment]
I was able to reproduce the issue _without_ docker but using `git clone` on a git repo hosted at my company. Seems related to large downloads somehow..

**Comment by selvanair** [comment]
This sounds unrelated to the operation of the GUI. If still not resolved, please ask in ask in openvpn forums (https://forums.openvpn.net/) or mailing lists (https://sourceforge.net/p/openvpn/mailman/).
