### ISSUE TITLE
Installation Instructions: installer + manual. Changed download link

### ISSUE THREAD

**Issue by DamianFekete** [OpenVPN/openvpn-gui#354]
In the [README](https://github.com/OpenVPN/openvpn-gui) there are two sections present for installing OpenVPN GUI: [automatic](https://github.com/OpenVPN/openvpn-gui#installation-using-the-official-openvpn-installers) and [manual](https://github.com/OpenVPN/openvpn-gui#manual-installation-of-openvpn-gui).

As far as I see, you can only download the source or the installer, so maybe the steps should be merged together? Or at least the manual one should reference the automatic one first?

Also the current download link is https://openvpn.net/community-downloads/ . The existing link https://openvpn.net/index.php/open-source.html doesn't redirect to the download page anymore.

**Comment by selvanair** [comment]
Yes, the installation instructions in README are outdated, inconsistent and confusing. Need to fix.
(i) The section on using release installers should link to the correct download page
(ii) The manual installation section could be removed or describe how to install the GUI executable locally built or to how to use openvpn-build with custom GUI.
