### ISSUE TITLE
Add Windows 10 to the "About" section on GitHub

### ISSUE THREAD

**Issue by DamianFekete** [OpenVPN/openvpn-gui#355]
Add `10` to the list of supported OSes in the **About** section on the [project page](https://github.com/OpenVPN/openvpn-gui).

> OpenVPN GUI is a graphical frontend for OpenVPN running on Windows XP / Vista / 7 / 8. [...]

**Comment by selvanair** [comment]
@mattock Can we update the "About" ?

**Comment by mattock** [comment]
@selvanair sure. I added Windows 10 to the list.

Does openvpn-gui still work with XP and Vista or should those be removed?

**Comment by selvanair** [comment]
Let's remove XP and Vista from the list as those are officially no longer supported.
I think the GUI still works on Vista, not sure of XP. But, we have not been testing on XP for long, and going forward, ensuring Vista compatibility may be hard as well.

**Comment by mattock** [comment]
Done. I'll close this ticket now.
