### ISSUE TITLE
It is not easy to use when I have so many many profile

### ISSUE THREAD

**Issue by SprayHank** [OpenVPN/openvpn-gui#370]
It is not easy to use when I have so many many profile

![微信截图_20200923161215](https://user-images.githubusercontent.com/2662845/93985978-5760e880-fdb8-11ea-98a8-fdfe6f247016.png)
![微信截图_20200923161527](https://user-images.githubusercontent.com/2662845/93985995-5d56c980-fdb8-11ea-9776-39019b5e00ca.png)
![微信截图_20200923161546](https://user-images.githubusercontent.com/2662845/93985997-5e87f680-fdb8-11ea-9bae-08160aa6c8e2.png)
![微信截图_20200923161608](https://user-images.githubusercontent.com/2662845/93986010-62b41400-fdb8-11ea-9ab7-fbee92e8c39c.png)
![微信截图_20200923161627](https://user-images.githubusercontent.com/2662845/93986025-65166e00-fdb8-11ea-9091-b042a5232651.png)
![微信截图_20200923161642](https://user-images.githubusercontent.com/2662845/93986030-66e03180-fdb8-11ea-8d2f-90fd80470280.png)
![微信截图_20200923161705](https://user-images.githubusercontent.com/2662845/93986032-68115e80-fdb8-11ea-9ae8-f1edef1aebf9.png)

I can only use the down arrow button to scroll it slowly,
Can it display multi-column like below ?

![无题](https://user-images.githubusercontent.com/2662845/93987127-c1c65880-fdb9-11ea-8ca8-f21fb3fec87d.png)

**Comment by selvanair** [comment]
You can organise the profiles into folders and sub-folders to get a nested view. That would help somewhat with so many profiles. 

To do this, create sub directories in the config directory like (for example)

Asia\Japan and add all jp-tok..... and similar profiles in this folder
Asia\Korea\kr-seo.. files etc..
Europe\UK\uk-lon... files  etc.
etc... 

That will generate a hierarchical menu.

**Comment by LoZio** [comment]
I have somewhat the opposite problem.
I have 15/20 config files, they are put in separate directories to be organized under config.
Using GUI 2.4 they all appear as a single menu, so I right clicked the icon and then was ready to connect.
With GUI 2.5 I have to right click, system profile, directory, specific file, connect. Being in the tray bar each menu appears to the right or left depending on its size, ad missing the pixel space moving on the touchpad you have to restart.
It would be useful a configuration switch for the GUI to show a "flat" old-style menu or hierarchical new-style menu.

**Comment by selvanair** [comment]
The menu view can be changed by adding a registry key:  HKCU\Software\OpenVPN-GUI\config_menu_view = 1 (DWORD). The default is 0 which automatically switches to the nested view if number of configs exceed 25, and a value of 2 forces the nested view. Also the command line option `--config_menu_view 1` does the same.
Making this configurable from the UI has been in my TODO for long ... sigh..

**Comment by LoZio** [comment]
That is exactly what I was looking for, is this documented somewhere?
