### ISSUE TITLE
Log file scrolls opposite direction than expected

### ISSUE THREAD

**Issue by jfreake** [OpenVPN/openvpn-gui#371]
When using your mouse wheel or arrow keys to scroll the log in the log file window, the contents scroll the opposite way than expected.
Pressing up causes the log to move down and pressing down causes the log to move up.
Most other scroll boxes in other applications and/or browsers are opposite to this.

**Comment by selvanair** [comment]
I guess you mean the status window. If so, I do not see the behaviour you describe. The logs displayed in the status window uses a multi-line "rich-edit widget" with default scroll actions.

On my laptop that works as wheel down (or down arrow) for scrolling down and the opposite for scrolling up. This is same as what most applications do, and match with your expectation too. I cannot say why you seem to get an opposite scroll action.

**Comment by jfreake** [comment]
When connected to a vpn server, the main status window (the one with the connection stats graph etc) scrolls correctly.
When I click on the upper right icon (the one that looks like a script document with a "<>" on it), it brings me to the "Log File" screen. The contents of the log file scrolls opposite to the main status screen.

**Comment by selvanair** [comment]
Sounds like you are referring to OpenVPN-Connect which is a commercial product from OpenVPN Inc. This site is about OpenVPN-GUI, a community supported UI.

**Comment by jfreake** [comment]
Ahh, gotcha. Sorry about that.
