### ISSUE TITLE
Add a global "Disconnect" menu item to context menu?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [OpenVPN/openvpn-gui#372]
![image](https://user-images.githubusercontent.com/39491297/96944347-374c4400-14a0-11eb-81e0-910027e29f8a.png)

After (thankfully :) [increasing the level depth](https://github.com/OpenVPN/openvpn-gui/issues/364), there's another issue; whenever I need to disconnect, or switch to a different vpn, I have to drill down 7 levels to click the Disconnect menu item for that specific vpn.

Would it be possible to just add a disconnect item to the main context menu, that when clicked, simply disconnects any connected vpn? It'd be sooooo much easier. 

Like, in the screenshot, below the separator bar add "Disconnect", then another sep bar below it, and then the rest.

thanks!
Kacey

**Comment by selvanair** [comment]
Thanks for the suggestion.
If you have only one connected profile, just double left-click on the tray icon to open the status window from where you can disconnect. We could extend that behaviour to cover multiple connections (within a reasonable number). That would provide an easy way to review all connected tunnels or to disconnect/reconnect any. Could be more useful than a "disconnect all".
