### ISSUE TITLE
Looking for the Windows Form in Visual Studio 

### ISSUE THREAD

**Issue by kbencze95** [OpenVPN/openvpn-gui#376]
I am trying to build the gui in Visual Studio with 
#define DISABLE_CHANGE_PASSWORD
The build is successfull, but I cannot see a windows form anywhere in the project, and that's the part I want to mess around with. 
Am i looking at the wrong project? How can I access the visual part of the project?

**Comment by selvanair** [comment]
This is a win32 application using native C API.

**Comment by kbencze95** [comment]
Can you tell me how can I edit the actual GUI?

**Comment by selvanair** [comment]
Edit the C source files.

**Comment by kbencze95** [comment]
Can you tell me which ones exactly? It must be clear by now, but I am pretty new to C.

**Comment by selvanair** [comment]
There are less than 20 C files in this repo and the process of navigating through them is same as any other C project. Further, this channel is for discussing and reporting issues, bugs and feature requests -- if you have a specific question about modifying a function or feature this is the right place to discuss it. Other questions like how to read the source files are better asked in some IRC channels or similar.

Here is a gist:
tray.c -- for the tray icon related functions and the menu hierarchy 
openvpn.c -- for the per connection status window and popup dialogs
Global settings and advanced settings dialogs are initialized in localization.c and options.c, respectively
