### ISSUE TITLE
Changing the header of the Login dialog

### ISSUE THREAD

**Issue by kbencze95** [OpenVPN/openvpn-gui#379]
I am looking for a way to change the header ( window name ) of the Login dialog. 
I have checked the resources, found nothing useful there, so I am assuming the windows gets it's name when the Dialog is constructed. 
Is there a simple way to just change this string to whatever I would like to use? And if so where can I find this particular part of the code?

**Comment by selvanair** [comment]
For most dialogs the caption is as in the resource file with the config name appended to the text in some cases calling AppenTextToCaption() when the dialog is constructed. But the caption for user-authentication dialog was simplified by commit e7fd11812f984323d65ecfec123b9b6e3d953431 to use just the config name -- I don't recall the reasoning.  Its set using SetWindowText() in UserAuthDialogFunc() (openvpn.c).

**Comment by selvanair** [comment]
> For most dialogs the caption is as in the resource file with the config name appended in some cases by calling AppenTextToCaption() when the dialog is constructed. But the caption for user-authentication dialog was simplified by commit [e7fd118](https://github.com/OpenVPN/openvpn-gui/commit/e7fd11812f984323d65ecfec123b9b6e3d953431) to use just the config name -- I don't recall the reasoning. Its set using SetWindowText() in UserAuthDialogFunc() (openvpn.c).
