### ISSUE TITLE
OpenVPN site Page not found

### ISSUE THREAD

**Issue by Neurotoxin001** [OpenVPN/openvpn-gui#385]
When I open downloads page I got not found error:
https://openvpn.net/community-downloads-2/

Even when I click on `Official OpenVPN Community downloads (Only released versions)` here:
https://community.openvpn.net/openvpn

Where is now I can download latest version of OpenVPN GUI?

**Comment by selvanair** [comment]
> When I open downloads page I got not found error:
> https://openvpn.net/community-downloads-2/

The link below works for me.
https://openvpn.net/community-downloads/

**Comment by cron2** [comment]
Hi,

On Wed, Dec 09, 2020 at 11:14:53AM -0800, Selva Nair wrote:
> > When I open downloads page I got not found error:
> > https://openvpn.net/community-downloads-2/
> 
> The link below works for me.
> https://openvpn.net/community-downloads/

Neither works for me.  Seems that something went wrong trying to update
the page for the 2.4.10 release.

The first links is supposed to be valid, so it should be back in 
a few hours.

Sorry for the inconvenience... (I assume Samuli is busy fighting the
CMS behind these pages...)

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by Neurotoxin001** [comment]
> The link below works for me.
> https://openvpn.net/community-downloads/

Seems like I need to clear browser cache, because it only works in incognito mode, in default mode it redirects to /community-downloads-2/

**Comment by mattock** [comment]
I noticed the community-downloads-2 thing yesterday also, when making the release. Then it went away. Something probably happened at the website end and Cloudflare / Cloudfront magnified the problem. This problem does not seem widespread, but if more reports come in somebody from our website team needs to investigate it.
