### ISSUE TITLE
Newbie found it is so difficult to run the project on windows. 

### ISSUE THREAD

**Issue by tbwork** [OpenVPN/openvpn-gui#386]
It seems there was no document to elaborate how to rebuild and develop the project on Windows.
I found there were a lot of errors when it is imported to VS 2017 community.
SO, could you like give us some advices?
 
`
1>------ 已启动生成: 项目: openvpn-gui, 配置: Debug x64 ------
1>已复制         1 个文件。
1>  正在创建库 D:\workspace\c\openvpn-gui\x64\Debug\openvpn-gui.lib 和对象 D:\workspace\c\openvpn-gui\x64\Debug\openvpn-gui.exp
1>main.obj : error LNK2019: 无法解析的外部符号 OPENSSL_init_crypto，该符号在函数 wWinMain 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 OPENSSL_sk_pop_free，该符号在函数 sk_X509_pop_free 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 EVP_des_ede3_cbc，该符号在函数 ChangePasswordPEM 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 EVP_PKEY_new，该符号在函数 ChangePasswordPEM 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 EVP_PKEY_free，该符号在函数 ChangePasswordPEM 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 X509_free，该符号在函数 ChangePasswordPKCS12 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 X509_alias_get0，该符号在函数 ChangePasswordPKCS12 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 PEM_read_PrivateKey，该符号在函数 ChangePasswordPEM 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 PEM_write_PrivateKey，该符号在函数 ChangePasswordPEM 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 PKCS12_free，该符号在函数 ChangePasswordPKCS12 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 PKCS12_parse，该符号在函数 ChangePasswordPKCS12 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 PKCS12_create，该符号在函数 ChangePasswordPKCS12 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 i2d_PKCS12_fp，该符号在函数 ChangePasswordPKCS12 中被引用
1>passphrase.obj : error LNK2019: 无法解析的外部符号 d2i_PKCS12_fp，该符号在函数 ChangePasswordPKCS12 中被引用
1>D:\workspace\c\openvpn-gui\x64\Debug\openvpn-gui.exe : fatal error LNK1120: 14 个无法解析的外部命令
1>已完成生成项目“openvpn-gui.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

`

**Comment by lstipakov** [comment]
Hi,

You are right, documentation can be improved.

For this specific case, you could either:

- install openssl via vcpkg
```
c:\Users\lev\Projects\vcpkg>vcpkg install openssl-windows:x64-windows
Computing installation plan...
The following packages are already installed:
    openssl-windows[core]:x64-windows
Package openssl-windows:x64-windows is already installed
```
- build with DISABLE_CHANGE_PASSWORD defined, which strips away code 
which uses openssl.
