### ISSUE TITLE
allow username on auth dialog to be auto set from config/cert

### ISSUE THREAD

**Issue by fkooman** [OpenVPN/openvpn-gui#39]
we are trying to use OpenVPN with 2FA (two factor authentication), but the UI (on Windows) is a bit confusing. We have no need to ask for the user name, the CN is used on the server as the username. So only asking for a password/token makes more sense from the user's point of view.

There seem to be various ways to solve it:
- pre-fill the username field with the value of the CN, or the value of the `setenv USERNAME "foo"` from the config file (why else would it be there ;))
- allow a client option to only ask for a password and use the CN or setenv value as the username

(I realize you can use a file that lists only the username and specify that as parameter to `--auth-user-pass`, but that is not so easy for the user to configure as just grabbing this value from the config file)

**Comment by selvanair** [comment]
I understand why you may want this, but its a special use case. Some users want username to be prefilled by windows username, some by common name, some just do not want any username at all. There are even users who want the challenge response to be prefilled -- that may sound strange but there are some legitimate situations where the response is predefined (say "push" or "phone"  in case of duo)..

The generic way to use user-auth in OpenVPN is with a username, password and optionally a challenge-response and that's what the GUI currently supports . That said, there is a plan to implement prefilling of username by the previously used value. Such a feature is of much wider utility and may also take care of your need to a good extent -- users will have to enter the username only once.

Using a file for username will only work for command-line use, not with the GUI.

Note that there is nothing special about "setenv USERNAME name" --- one can define any name-value pair using the setenv option and these are passed by OpenVPN to scripts as env vars. The GUI currently does not parse the config file.

**Comment by fkooman** [comment]
Thanks for explaining how it works, I thought I was doing something wrong regarding storing the user name in a file and using the GUI. It didn't work :)

> That said, there is a plan to implement prefilling of username by the previously used value. Such a feature is of much wider utility and may also take care of your need to a good extent

Yes it would, that seems like a good solution :)

Thanks!

**Comment by selvanair** [comment]
Looks like resolved. Closing.

**Comment by M0ns1gn0r** [comment]
@selvanair 
> there is a plan to implement prefilling of username by the previously used value

It wasn't implemented, was it?

**Comment by selvanair** [comment]
Since Mid 2016, the GUI remembers the previously used username. Optionally the password is also saved.

There is a pending PR (#218) that proposes to save username only if password is also saved -- you can "vote" against it if not desirable.
