### ISSUE TITLE
./configure is throwing some errors on Windows 7

### ISSUE THREAD

**Issue by jnbdz** [OpenVPN/openvpn-gui#40]
Hi,

I am having some issues on my Windows 7 when I do ./configure.

Here are the errors I get:

![openvpn-error](https://cloud.githubusercontent.com/assets/237008/14711035/cf27c89c-07a5-11e6-9166-325437a6d2b9.png)

Thanks in advance for any help.

**Comment by selvanair** [comment]
pkg.m4 is not loaded?
pkg-config is required but either not installed or its location is not found by configure.

See the discussion here:
https://github.com/OpenVPN/openvpn-gui/issues/11

**Comment by selvanair** [comment]
Looks like resolved. Closing.
