### ISSUE TITLE
Number of config files limited to 2 to the power of 12 (4096)

### ISSUE THREAD

**Issue by sc-rs** [OpenVPN/openvpn-gui#404]
OpenVPN 2.5.1. for Windows x64 (Community Edition, OpenVPN-2.5.1-I601-amd64.msi):
openvpn-gui.exe throws an error if the number of config files in the config file folder exceeds 2 to the power of 12 (4096). The program stops working then from the command line and via GUI.

<img width="301" alt="open_vpn_error" src="https://user-images.githubusercontent.com/73759635/109167110-b4086b00-777d-11eb-8014-c6c0c57cae8f.png">

**Comment by cron2** [comment]
Hi,

On Thu, Feb 25, 2021 at 06:25:55AM -0800, sc-rs wrote:
> OpenVPN 2.5.1. for Windows x64 (Community EditionOpenVPN-2.5.1-I601-amd64.msi):
> openvpn-gui.exe throws an error if the number of config files in the config file folder exceeds 2 to the power of 8 (4096). The program stops working then from the command line and via GUI.
> <img width="301" alt="open_vpn_error" src="https://user-images.githubusercontent.com/73759635/109167110-b4086b00-777d-11eb-8014-c6c0c57cae8f.png">

2^8 is 256...

but seriously?  You have 5900+ openvpn configs on your system?

WHY?

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by sc-rs** [comment]
I need to frequently switch VPN servers so I'm working with the full TCP server list of NordVPN which provides nearly 6k servers.

**Comment by selvanair** [comment]
6K sub-menus will be very inconvenient to navigate. It would be better to merge related configs into one using connection blocks (multiple remotes in one config file) -- say one config per country or something like that. But, unfortunately, we do not (yet) support selecting the remote from the GUI.

As menu selection messages are delivered with a 16 bit id, and we reserve 4 bits for the type of action (connect, disconnect etc.) we only have 12 bits left for config index. It may be possible to change this to trigger a message that also delivers a handle of the menu item, I'll take a look.

>  OpenVPN 2.5.1. for Windows x64 (Community Edition, OpenVPN-2.5.1-I601-amd64.msi):
openvpn-gui.exe throws an error if the number of config files in the config file folder exceeds 2 to the power of 12 (4096). The program stops working then from the command line and via GUI.

Are you sure the GUI stops working? The intention was only to throw a warning and continue by ignoring configs beyond that max number. I have not tested it though. 
OpenVPN command line only accesses the config specified on the command line and has nothing to do with the number of configs in the config directories.

**Comment by sc-rs** [comment]
Thanks for the detailed answer, selvanair.
The feature to have multiple blocks very convenient. I also tried to split the files over various sub-folders of my config folder, but this did not help.

It would also be convenient to have the context menu of the tray icon (on right click) have sub-menus for the config files, settings, and the quit option. Currently, all my config files 'polute' the context menu, so I have troubles scrolling down to the settings option.

Thanks for the explanation about the integer, this makes perfect sense.

The gui itself appears (!, need further testing) to still work, but it wont work when I try to open a connection to a server that is not recognized. The connecting/re-connecting is done via a script and that code has no way of knowing which config file is considered by OpenVPN and which is not.

With respect to your last sentence: I have various network folder locations with the config files between which I switch depending on my current workflow and machine that I'm working on. So I call the openvpn-gui.exe via commandline with the --config_dir option, which also produces the "error".

Is there any possibility that the problem may be solved somewhere in the near future?

**Comment by selvanair** [comment]
> Thanks for the detailed answer, selvanair.
> The feature to have multiple blocks very convenient. I also tried to split the files over various sub-folders of my config folder, but this did not help.
> 
> It would also be convenient to have the context menu of the tray icon (on right click) have sub-menus for the config files, settings, and the quit option. Currently, all my config files 'polute' the context menu, so I have troubles scrolling down to the settings option.

This is already possible by moving all configs and their subfolders to a folder under the config_dir. Note that the GUI maps the directory structure to the menu view -- such a nested menu view is automatically enabled when number of configs exceed 25 or so. Organize your configs into subfolders for ease of use. Also try to keep the max number of configs in one folder under 30 or so to keep the menu within the screen space  etc. A directory depth of up to 20 is supported.

Example:
![image](https://user-images.githubusercontent.com/3981391/109315212-4b220100-7818-11eb-95aa-3734d81455a9.png)


> 
> Thanks for the explanation about the integer, this makes perfect sense.
> 
> The gui itself appears (!, need further testing) to still work, but it wont work when I try to open a connection to a server that is not recognized. The connecting/re-connecting is done via a script and that code has no way of knowing which config file is considered by OpenVPN and which is not.

Yes, only the "first" 4096 configs will work and its not easy to predict.

> 
> With respect to your last sentence: I have various network folder locations with the config files between which I switch depending on my current workflow and machine that I'm working on. So I call the openvpn-gui.exe via commandline with the --config_dir option, which also produces the "error".
> 
> Is there any possibility that the problem may be solved somewhere in the near future?

As the directory structure and menus are reconstructed on every right click on the tray, for interactive use, it gets slow beyond a few 1000 configs. 4000 is just barely usable on my slow laptop. But if you are sending commands  to a running instance (using the `--command action` feature), this wont be an issue. 

I'll look into relaxing the restriction on the number of config files.

**Comment by selvanair** [comment]
> OpenVPN 2.5.1. for Windows x64 (Community Edition, OpenVPN-2.5.1-I601-amd64.msi):
> openvpn-gui.exe throws an error if the number of config files in the config file folder exceeds 2 to the power of 12 (4096). The program stops working then from the command line and via GUI.
> 
> <img alt="open_vpn_error" width="301" src="https://user-images.githubusercontent.com/73759635/109167110-b4086b00-777d-11eb-8014-c6c0c57cae8f.png">

As a note to self -- there is a bug in that message. It should state 4096, not 5992.
Also the message is a left over from old times when we used to support 50 configs which was easy to raise by a few hundred or so  by recompiling. The current code is so different that its no longer a simple matter of "contacting the author" :)

**Comment by selvanair** [comment]
>I'll look into relaxing the restriction on the number of config files

@sc-rs Please test the executable in the [pre-release](https://github.com/selvanair/openvpn-gui/releases/tag/too-many-configs) or build from this [branch](https://github.com/selvanair/openvpn-gui/tree/too-many-configs) and test. Thanks.

**Comment by selvanair** [comment]
The limit is now removed (PR #409). However, in practice, the need to keep management_port_offset + number of configs under 65536 imposes a limit.

**Comment by TinCanTech** [comment]
With all Openvpn options, I fear 64k will soon be a broken limit :cactus:

**Comment by cron2** [comment]
Hi,

On Fri, Mar 05, 2021 at 08:56:41PM -0800, TinCanTech wrote:
> With all Openvpn options, I fear 64k will soon be a broken limit :cactus: 

It's neither useful nor desirable to have a separate config file for
every possible combination of options...

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by selvanair** [comment]
> It's neither useful nor desirable to have a separate config file for every possible combination of options...

We need to allow selecting the remote via the GUI to stop this config proliferation nonsense. I would like to show a list of remotes for the user to select from. But that requires the core to provide the list (instead of prompting for one by one) or the GUI has to parse the config. Wonder how other GUI's support `--management-remote` in a user-friendly way.

**Comment by TinCanTech** [comment]
If you want _suggestions_: You could introduce a new dialogue box.
A complete list of all configs found in a scrolling Window, double-click an entry to start it.

**Comment by selvanair** [comment]
> If you want _suggestions_: You could introduce a new dialogue box.
> A complete list of all configs found in a scrolling Window, double-click an entry to start it.

I know that :) The question is how to get that list of remotes from the core without having to implement a config parser.

**Comment by TinCanTech** [comment]
> how to get that list of remotes from the core without having to implement a config parser

I do not see the need to "get a list of remotes" ? Unless I missed something.

Initially, this was a problem with the GUI having a hard limit to the number of configs.
I think 64k as a hard limit is fine, despite my previous flippant comment.

Listing upto 64k configs is not feasible via the GUI menu system, so you are going to need a way to do that.

Trying to get users to "consolidate" their configs (which are not theirs but provider configs) is never going to happen, so that is an absolutely fruitless path IMO.

**Comment by TinCanTech** [comment]
If you simply want "The list" to show the actual `remote`, say by IP address, then `grep` each one for `remote`, don't actually parse the config.  Again, I may be missing your point, if so sorry.

**Comment by selvanair** [comment]
I think we have different approaches in mind. I want to implement a enhanced version of --management-remote for those who are ready to keep all related remotes in one config file using connection blocks. I know this consolidation of configs will have to be done by providers for it to be widely usable.

The alternative is to not use a menu but a list dialog for configs (I suppose that's what you have in mind). But that would involve significant design changes. Not compatible with my tardiness, nor lack of time.

**Comment by TinCanTech** [comment]
OK, I understand what you mean..

WRT the 64k limit -- you know somebody is going to try it -- it might be simpler to write a separate, quick and dirty: "Selection -> Fire-Up-Config" (_openvpn-gui.exe connect config-name_) List in VBasic .. even I could probably do that ;-)

**Comment by selvanair** [comment]
The "official" way to do that would be to  use the "send command to the GUI" feature. First start the GUI, do not use the navigation menu but send commands like

`openvpn-gui.exe --command connect foo` 
where foo.ovpn is an existing config
or
`openvpn-gui.exe --command disconnect foo`
etc.

Works well even with 1000's of configs and more flexible than starting the GUI with --connect foo.

**Comment by TinCanTech** [comment]
> The "official" way to do that would be to use the "send command to the GUI" feature

That is exactly what I meant.

**Comment by TinCanTech** [comment]
Adding details:

Left-click on the running GUI icon currently appears unused, I am proposing that a list would be shown.

From that list a user could `connect`, `disconnect`, `status`, `log` and _possibly_ `ping` _prior to connect_ or something like that.

**Comment by sc-rs** [comment]
> The limit is now removed (PR #409). However, in practice, the need to keep management_port_offset + number of configs under 65536 imposes a limit.

Thank you very much for your effort and support, much obliged!
