### ISSUE TITLE
Using openvpn-gui to connect multiple openvpn server

### ISSUE THREAD

**Issue by wyw900807** [OpenVPN/openvpn-gui#411]
Dear sir:
   It is assumed that there are two L2TP/Ipsec VPN server, and I use windows client to connect server 1 and server 2 in turn. In this case, all the communication traffic will pass through server 1 first and then through server 2.
  However, if I use openvpn-gui to connect openvpn server 1 and server 2 in turn, the communication traffic will not pass through server 1 first and then through server 2, I do not know the reason.
   Thank you very much !

**Comment by selvanair** [comment]
This is a question about setting up routing in OpenVPN and not directly related to the GUI. Consult OpenVPN documentation (https://openvpn.net/community-resources/how-to/) and/or ask in openvpn forums (https://forums.openvpn.net/) or mailing lists (https://sourceforge.net/p/openvpn/mailman/)
