### ISSUE TITLE
GUI started showing weird empty windows on my desktop

### ISSUE THREAD

**Issue by frj321** [OpenVPN/openvpn-gui#415]
For no apparent reason when I clicked on the OpenVPN gui tray icon today, it created a small empty window on my desktop. Closing the window closes the application.
I decided maybe it's time to upgrade to get it fixed, so I upgraded using OpenVPN-2.5.1-I601-amd64.msi and now I have 2 empty windows created on my desktop. Window (1) is created as soon as I start gui, then when I right click on the tray icon to access the context menu, it creates window (2).
Is there a way to rid of these windows?

Using Windows 10 Pro N, 20H2, build 19042.867
![Image1](https://user-images.githubusercontent.com/51425073/114484430-0e8b4880-9bbf-11eb-9c0f-de01fdb1cb6e.jpg)

**Comment by selvanair** [comment]
These are generated by the newly introduced feature for sending messages to the GUI. But it should popup only if there are `echo msg` commands in the config or pushed from the server. That too only during a connection initiation.  Also the windows should show the content of those messages.

I'm not sure why these would would popup just by starting the GUI and not when connecting a VPN. Probably you are auto-starting some connections. 

In any case,  check your configs for commands starting with `echo msg-window` and comment them out. If these are pushed by the server, you could add `pull-filter ignore "echo msg-wndow"` in your config files. Note that this would suppress any messages from the server. Do this only if the server is misconfigured to send empty or repeated messages.

There is a PR that will add an option to the settings menu to enable/disable popup messages, but not yet merged.

**Comment by frj321** [comment]
Thank you for fast response. I don't have any config starting automatically, but I noticed some of my other apps also started to behave in unusual manner related to showing windows. So I restarted my computer and this fixed the issue [facepalm]...
Sorry for the trouble.
