### ISSUE TITLE
Need to run route-up script as administrator for non-admin users

### ISSUE THREAD

**Issue by opoplawski** [OpenVPN/openvpn-gui#421]
We would like to be able to run a "route-up" script for our non-admin users.  We need a script as it uses information from the local machine to generate the needed routes.  As the script modifies the routing table it needs admin privileges.  However this appears to only be possible if the openvpn gui is run as an administrator.  Is there any way around this?

**Comment by selvanair** [comment]
What you are asking for is not possible. If you can collect the required routes using a script you can add it to the config before starting the connection. The GUI's pre-connect-script could come handy here. And the feature in OpenVPN to include additional configs from the main config file.

OpenVPN has generic ways of specifying route through the tunnel or bypassing the tunnel without needing to know the VPN explicit gateway address. Like this:

`route network netmask [gateway] [metric]`

leave out the gateway to use the tunnel, use the placeholder 'net_gateway' to route outside the tunnel. See the manpage of OpenVPN for details. This should take care of most needs.

**Comment by opoplawski** [comment]
Thanks, that works!  Here is a quick hack I came up with for routing local printers since we use the "block-local" option to "redirect-gateway":
```
# Empty file
"" | Out-File -Encoding ASCII "C:\Program Files\OpenVPN\config\routes.conf"

# Direct interface routes don't work, so use the local gateway instead.
# This also has the benefit of working with local printers on a different subnet.
$route_fmt = "route {0} 255.255.255.255 net_gateway"
$route_ipv6_fmt = "route-ipv6 {0}/128 net_gateway"
Get-WmiObject Win32_Printer | where {($_.Location -Match "^http")} |
  ForEach-Object { [System.Uri]$_.Location } |
  ForEach-Object {
    if ($_.Host -Match '^\[') {
      $route_ipv6_fmt -f $_.Host.Replace("[","").Replace("]","") | Out-File -Encoding ASCII -Append "C:\Program Files\OpenVPN\config\routes.conf"
    } else {
      $route_fmt -f $_.Host | Out-File -Encoding ASCII -Append "C:\Program Files\OpenVPN\config\routes.conf"
    }
  }
```

I did try to create local interface routes with:
```
$route_fmt = "route {0} 255.255.255.255 0.0.0.0"
$route_ipv6_fmt = "route-ipv6 {0}/128 ::"
```
but at least for IPv6, this doesn't work - it tries to add to the tunnel.  Is it worth an RFE to support local interface routes?

**Comment by cron2** [comment]
Hi,

On Mon, May 17, 2021 at 08:45:57AM -0700, Orion Poplawski wrote:
> but at least for IPv6, this doesn't work - it tries to add to the tunnel.  Is it worth an RFE to support local interface routes?

We do have an open trac on that.  It's just that nobody came around
to actually building the necessary code.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by opoplawski** [comment]
Well, I've decided that the local gateway is an okay option for us so I guess I won't be working on it either ;).
