### ISSUE TITLE
Create log directory if necessary

### ISSUE THREAD

**Issue by opoplawski** [OpenVPN/openvpn-gui#432]
We are installing VPN configs in C:\Program Files\OpenVPN\config, but having users launch the connections manually.  It this case log files do not get created because C:\User\USER\OpenVPN\log does not exist.  OpenVPN should create this directory if necessary.

**Comment by selvanair** [comment]
As you know this repo is about the GUI and it decides where to keep the logs -- this is currently %USERPROFILE%\OpenVPN\log. The GUI creates it if/when required.

If you are running openvpn.exe from command line (not using the GUI), this is not the right place to ask. Anyway, in this case the log file is specified by you in the config file or command line. The usual location for logs  is C:\Program files\OpenVPN\log which I believe is created by the installer. If you want openvpn.exe to create any missing directories for arbitrary log paths specified by the user, please ask in openvpn-users or openvpn-devel mailing list.

**Comment by opoplawski** [comment]
Hm, my apologies - openvpn does appear to be creating the %USERPROFILE%\OpenVPN\log on launch - at least for me on my machine.  But I have at least one user running 2.5.019 where that directory does not exist, and I can't think why not.

**Comment by opoplawski** [comment]
Now that exists, so likely user error here.
