### ISSUE TITLE
Accept 2FA code using the Enter key

### ISSUE THREAD

**Issue by elliotabbott** [OpenVPN/openvpn-gui#433]
Currently, users need to use the mouse click to send an authenticator code to connect. 

As 2FA is a timed process, the Enter/Return key would be quicker.

I am happy to try to make a pull request, but have never written in C. Any guidance/direction would be greatly appreciated!

![image](https://user-images.githubusercontent.com/16312899/122584943-f0abeb00-d028-11eb-97e1-37bb2251045e.png)

**Comment by selvanair** [comment]
You are referring to a OpenVPN connect, a commercial product from OpenVPN Inc. while this repo is for the community supported free OpenVPN-GUI client for Windows. Enter key should work on the GUI --- you may want to try it  :)

**Comment by elliotabbott** [comment]
Ahh, I see. Thanks for explaining @selvanair ! :-)

Upon revisiting, the Enter key does seem to work on the OpenVPN Connect GUI, but inconveniently requires clicking on the dialog again or pressing the Tab key twice first (for me at least).
