### ISSUE TITLE
Any thoughts of porting this wonderful project to run on macOS environment ? 

### ISSUE THREAD

**Issue by iradization** [OpenVPN/openvpn-gui#434]
When using openVPN client from the official openVPN website, it present a cross platform gui built in Electron. I don't have much experience with this framework, but do you think it would be possible to make this gui cross-platform as well ?

**Comment by cron2** [comment]
Hi,

On Fri, Jun 25, 2021 at 04:07:26AM -0700, iradization wrote:
> When using openVPN client from the official openVPN website, it present a cross platform gui built in Electron. I don't have much experience with this framework, but do you think it would be possible to make this gui cross-platform as well ? 

This is not "openvpn gui", but OpenVPN Connect.  Different thing.

Plus, Connect is available for Mac...

For the free OpenVPN project on MacOS, have a look at tunnelblick.net

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by mattock** [comment]
I believe seeing that OpenVPN Connect weighs 191MB or so. OpenVPN 2.x installer with this GUI weighs ~4MB.

I don't think this project can ever be ported to MacOS. It is too entangled with Windows APIs to make any sense. Gert mentioned Tunnelblick already as an option. Viscosity is another one, but it costs $$$. It supports Windows and MacOS afaik.
