### ISSUE TITLE
[Minor-annoyance] Invalid error message If Windows user login completes before the Interactive service has started

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/openvpn-gui#435]
If Windows is setup to auto-login with a specific user then it is possible that the user is logged in and the GUI is started before the Interactive service has had time to start.  The GUI then pops up and error window stating that the Interactive service has **not** started, when (in my use case) it has started but it was too slow for the GUI.

This really is not important, however, I expect it can be improved.

**Comment by selvanair** [comment]
We do not have a fine-grained option to suppress this warning. If  silent_connection is on (in settings->General menu) it wont be shown. However, the real cure would be to distinguish between whether the service is just slow to start or really dead. 

Unless we make the interactive service a requirement[*] to run the GUI, its hard to provide a better UX. We could make it always wait for a while if the service is not running at the expense of slowing down the startup for some (i.e., those who insist on running the GUI without the service).

[*] IMO, this should be imposed, but some will complain.

**Comment by chipitsine** [comment]
We can check service status. If is disabled, we do not wait

**Comment by chipitsine** [comment]
I am against extra setting. We do not need complexity

**Comment by TinCanTech** [comment]
I think it would be reasonable to inspect the service for start-up type and act accordingly.

**Comment by TinCanTech** [comment]
Although it is only a minor annoyance to me (I don't really mind it at all) but, to a new user, it could be confusing, if they look only to find that the service is running ..

**Comment by TinCanTech** [comment]
> Unless we make the interactive service a requirement[*] to run the GUI, its hard to provide a better UX. We could make it always wait for a while if the service is not running at the expense of slowing down the startup for some (i.e., those who insist on running the GUI without the service).
> 
> [*] IMO, this should be imposed, but some will complain.

Some _did_ complain that there is a spurious error message.

Considering the diminishing minority of people who would use the Openvpn-Windows-GUI without the Interactive-service seems like a waste of your time to me.
