### ISSUE TITLE
OpenVpn-Gui Command Called with --command when no previous instance available

### ISSUE THREAD

**Issue by lucaswhob** [OpenVPN/openvpn-gui#439]
Hello My Friend
My Operating System : OS Windows Server 2019 Data Center
I Run With Cmd : openvpn-gui.exe --command disconnect  usa1
usa1 is Profile Loaded With Ovpn file
When Run In Command Prompt Run Ok
But When Run From Web Server IIs In Windows Return 
 --command when no previous instance available
Please Help Me
I Used C# Programming I Runned My Application Good Work
Buth When Run From iis return Called with --command when no previous instance available
Please See This Screenshot
[ScreenShot](https://www.mediafire.com/convkey/260e/fj2qsjan7k803o19g.jpg)

**Comment by lucaswhob** [comment]
I Use These Code Please See Screen Shot
[MyCode](https://www.mediafire.com/convkey/3a7d/dbk5b70fh0xmsgl9g.jpg)

**Comment by selvanair** [comment]
Sending commands to running GUI will l only work from the same session. When a process is executed from IIS, I guess it is started in a different session. Your use case may be better handled by starting openvpn.exe from automatic service with `--management-hold` and then control it via the management interface.

**Comment by lucaswhob** [comment]
How Set Only One Session ?
How Conect disconnect with managment Interface ?
thx

**Comment by selvanair** [comment]
For documentation on management interface see
https://github.com/OpenVPN/openvpn/blob/master/doc/management-notes.txt
If you have specific questions about using it, ask in the openvpn-users mailing list. It is unrelated to OpenVPN-GUI.

**Comment by lucaswhob** [comment]
ok but openvpn-gui why cannot command run from anothr session ?
I read your link but cannot find how connect disconnect command

**Comment by lucaswhob** [comment]
How Create Same Session ? Or Disable this Feature ?
