### ISSUE TITLE
CR_TEXT dialog should be closed if server receives client-auth, client-deny or client-kill

### ISSUE THREAD

**Issue by ro0p** [OpenVPN/openvpn-gui#440]
We use the server's management interface to authenticate users and handling 2FA. Our users can use OTP or push notification on their mobile device for 2FA. OTP works fine this way, but when push notification is accepted or rejected on mobile device, we send client-auth or client-deny to the server and the client is connects or disconnects as expedted, but CR_TEXT dialog stays and waits for user action.

 It would be very useful if this dialog would be closed automatically if the state of the connection is changed from "AUTH_PENDING" to anything else while the dialog waits for user input.

Thank you

**Comment by selvanair** [comment]
I suppose you are sending CR_TEXT with no-response required (i.e. flag R not present) but the dialog still needs the user to press OK. When it was coded it was felt that if a message is to be shown to the user, some form of acknowledgement from the user is required before it can be closed. 

Your proposal to close it when authenticated makes sense. Or should we add a timeout?

**Comment by ro0p** [comment]
Flag R is present, because the input field is required for typing the OTP if push notification is not working for some reason (network issue, buggy device etc).
I think using a timeout is not a good idea, because users can be... dumb :)

Closing the dialog on state change  will be great. If this behavior breaks the original design, it could be controlled by another flag.

Thank you

**Comment by selvanair** [comment]
If R is present we interpret it as response is required and have to consider all use cases before auto closing the dialog. IIRC, there is an optional timeout value in AUTH_PENDING message. We could close the dialog at its expiry as the connection will anyway restart at that point. 

That said, looking for a state change that makes any pending auth dialog obsolete and closing them sounds good at first blush. Let's give it some more thought.

**Comment by ro0p** [comment]
Sounds great.
Thank you

**Comment by selvanair** [comment]
@ro0p see PR #441. Would appreciate it if you could test it.

**Comment by ro0p** [comment]
Works like charm!
Thank you for the very quick solution!

**Comment by selvanair** [comment]
Fixed by #441
