### ISSUE TITLE
RFC: on setting the name of profiles downloaded from URLs

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn-gui#450]
When a profile is imported using "import from URL" (or from access server), we take the profile name from the config file using a meta-tag, falling back to the hostname as the default. I'm thinking of extending this to use the filename in http header as the default . If not found, use the hostname.
 
That is, read the content-disposition header and look for filename:

"content-disposition: attachment; filename=foo.ovpn"

If non-ascii filenames are to be supported we could allow the extended format with filename* as in rfc [5987](https://datatracker.ietf.org/doc/html/rfc5987)

Is there a better/preferred way? What do other server administrators use when they generate configs to be downloaded from a web server?

In our current implementation we also want `content-type: application/x-openvpn-profile` .This is not imposed for AS profiles. The content charset is assumed to be UTF-8.

**Comment by cron2** [comment]
Hi,

On Wed, Sep 01, 2021 at 11:06:18AM -0700, Selva Nair wrote:
> When a profile is imported using "import from URL" (or from access server), we take the profile name from the config file using a meta-tag, falling back to the hostname as the default. I'm thinking of extending this to use the filename in http header as the default . If not found, use the hostname.
>  
> That is, read the content-disposition header and look for filename:
> 
> "content-disposition: attachment; filename=foo.ovpn"

I like this.

> Is there a better/preferred way? What do other server administrators use when they generate configs to be downloaded from a web server?

I currently store files on the server (with a "random" component in the
URL, but not the filename), so people download

 https://corp.com/asdiojqwe139/myusername.ovpn

and there is a filename to work with.

Moving from there to a "please login here, and click <generate profile>"
style would indeed require a way to signal a filename for a generated
.ovpn (which does not physicall exist on disk on the server) - and
using this via standard headers sounds like a good approach.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by selvanair** [comment]
Resolved by #462
