### ISSUE TITLE
Cryptoapicert stops working after 2.5.3 -> 2.5.4 client upgrade

### ISSUE THREAD

**Issue by chefino** [OpenVPN/openvpn-gui#456]
Hi,

Since we've upgraded our Windows 10 OpenVPN clients to 2.5.4, an essential auth mechanism stopped working.
It seems the 2.5.4 client can't load certificates from the MS certificate store.

Both options for `cryptoapicert` don't work now (`SUBJ:` nor `THUMB:`) with MS cert store.
I have a correct config file that works with both methods in OpenVPN GUI version 2.5.3, but neither work in 2.5.4 (on the same computer). 

After initiating a connection, we get this error.

![image](https://user-images.githubusercontent.com/4114876/137141220-d13f1556-1005-46a0-a954-13a6c2dcdf32.png)

Rolling back to 2.5.3 "fixes" the issue and VPN connects:

This is how our config file looks like (generated by pfSense openvpn export plugin):

```
dev tun
persist-tun
persist-key
data-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC
data-ciphers-fallback AES-256-CBC
auth SHA256
tls-client
client
resolv-retry infinite
remote vpn.example.com 1197 udp4
setenv opt block-outside-dns
lport 0
verify-x509-name "Example Server" name
auth-user-pass
ca vpn-UDP4-1197-username-ca.crt
### Using only 1 option at a time
#cryptoapicert "SUBJ:username, US, .... etc. "
cryptoapicert "THUMB:047*******"
tls-crypt vpn-UDP4-1197-username-tls.key
remote-cert-tls server
explicit-exit-notify
reneg-sec 36000
```

**Comment by selvanair** [comment]
I think a build issue with OpenSSL. No EC key support compiled in?

@chefino  Could you confirm you are using an EC certificate?

For me  RSA certificates continue to work, but EC fails. Looks like OpenSSL was built with OPENSSL_NO_EC defined. If that's the case, we'll need a new release.

**Comment by chefino** [comment]
> That error is shown if the public key in the certificate is neither RSA nor EC. But that's not possible with the same certificate, and none of the relevant code has changed from 2.5.3 to 2.5.4. It nothing else has changed in y our setup, I'll try to reproduce this.

No, we didn't change anything for the last couple of weeks. Issues started appearing when road warriors started updating OpenVPN client to 2.5.4 a few days ago.

**Comment by selvanair** [comment]
For inlined keys we do not check the key type and if its working that means OpenSSL library in the release has EC support. But if OpenVPN is built with OPENSSL_NO_EC, many of the EC related functionalities wont work including EC keys in cryptoapicert, possibly ECDHE, showing EC related parameters etc.

All that points to OpenVPN being built using msvc-config.h with wrong defines that I mentioned in trac.
