### ISSUE TITLE
Popup challenge response window size

### ISSUE THREAD

**Issue by ziedrv** [OpenVPN/openvpn-gui#468]
Hello,
I hope this can be fixed,. A long challenge text must be displayed at the end use but the window size doesn't fit to show all the message. The popup size is not dynamic.

**Challenge text:** To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.

![141252](https://user-images.githubusercontent.com/24189414/143683234-840da4ed-e665-45bb-93c0-45bc2c3a9604.PNG)

**Comment by selvanair** [comment]
That particular dialog (dynamic challenge response) is already resizable. 

The problem may be that your text is getting wrapped and  there is no vertical space for a second line. We can increase the line length and allow space for a second line. Will test and see.

That said, giving a URL in the challenge text will provide a poor UX as the user cannot even cut and paste the URL.  See whether the new client-pending-auth management command that can ask the client to open a URL works better for this.

**Comment by ziedrv** [comment]
As mentioned in management note, client-pending-auth is a good idea. I am trying to implement it in python code it but it will took time because there is a little information and no examples how to use this option (It's a new feature in version 2.5).

I confirm that I can resize the popup window manually but text still fixed.
![412552](https://user-images.githubusercontent.com/24189414/143721882-741af013-dc0d-4c0b-a0ab-63f0b940dae3.PNG)

**Comment by selvanair** [comment]
The maximum width of the line is currently limited to ~60 characters, and vertical space assigned is just enough for one line. The text wraps at that point as you can see from some text fragments (black pixels) showing up on line 2. This will be fixed in #469. 

For client-pending-auth we currently support openurl in the GUI. For your use case it should be usable if the device code can be submitted as GET.

**Comment by schwabe** [comment]
@ziedrv see for example this script: https://github.com/schwabe/openvpn/commit/0976079d8bbd078fd1a1dc902ad1a3b03173b6b0

**Comment by selvanair** [comment]
@ziedrv You can test the fixed version using CI-build executables here: https://github.com/OpenVPN/openvpn-gui/actions/runs/1513839435#artifacts

**Comment by ziedrv** [comment]
Did I miss something ?

![1000212](https://user-images.githubusercontent.com/24189414/143926633-8de1c3c7-00c1-44f2-9753-496e815d1364.PNG)

**Comment by ziedrv** [comment]
OK it's the vcruntime version. I this it should be the same as the one installed vcruntime140.dll

**Comment by lstipakov** [comment]
It should indeed, but looks like out GitHub actions script has its own opinion. Let me check.

**Comment by selvanair** [comment]
...140D.dll is likely the debug version of the dll.

**Comment by lstipakov** [comment]
@ziedrv please try this one https://github.com/OpenVPN/openvpn-gui/suites/4497886072/artifacts/119988806

**Comment by ziedrv** [comment]
Yes! It works great now .. Thanks

![1000213](https://user-images.githubusercontent.com/24189414/143942279-d5aecd2c-99ba-412b-a232-b8c2efef2ebf.PNG)

**Comment by selvanair** [comment]
Fixed in 2.5.5.
