### ISSUE TITLE
Support for password change feature and OpenSSL 3.0

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn-gui#474]
In the GUI we use OpenSSL only for changing password of privtae keys (PEM and pkcs12). With OpenSSL 3.0, this is broken for legacy key encryption algorithms (eg., 40bitRC2-CBC). We have a couple of options:
(i) load legacy & default providers at startup
(ii) add a configurable option to enable legacy provider 
My preference would be do (i) if fips is not enabled, do nothing otherwise. Easier to implement and no user action required.

**Comment by cron2** [comment]
Hi,

On Wed, Feb 02, 2022 at 02:40:17PM -0800, Selva Nair wrote:
> In the GUI we use OpenSSL only for changing password of privtae keys (PEM and pkcs12). With OpenSSL 3.0, this is broken for legacy key encryption algorithms (eg., 40bitRC2-CBC). We have a couple of options:
> (i) load legacy & default providers at startup

Sounds like the easiest way forward.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***
