### ISSUE TITLE
Connection to management interface failed

### ISSUE THREAD

**Issue by KVPV** [OpenVPN/openvpn-gui#478]
Initially everything worked well. But suddenly, it stopped working! Every time I reinstall OpenVPN-GUI I always get the same error. (Regardless of whether I have interfaces enabled or not). Can anyone provide an answer on this?

PS: Services are running.
OS: Windows 10 (build 18363)

![image](https://user-images.githubusercontent.com/68104307/154868635-7c2168de-6a87-42eb-963b-e48c17a29d3e.png)
![image](https://user-images.githubusercontent.com/68104307/154868652-2fe6168d-f769-4cb1-b351-5520d53c0fb4.png)

**Comment by selvanair** [comment]
For some reason the interactive service is failing to open the NUL device to redirect stdout. 
Could you please provide an English translation of the error message text beyond the "Create File for stdout"? Or, a cut and paste of the error as plain text so that it could be machine translated.

**Comment by lstipakov** [comment]
It says ”cannot find the file specified”.

**Comment by selvanair** [comment]
> It says ”cannot find the file specified”.
Missing NUL device?
 
@KVPV could you open a command window and check whether the following generates an error?

`echo something > NUL`

If it does print an error, driver for NUL is not loaded. Likely some messed up registry settings.

**Comment by KVPV** [comment]
> 

It says ”cannot find the file specified”.

**Comment by selvanair** [comment]
> What can i do about it? NULL service is missing for me. 

I do not want to suggest registry edits but you could check whether HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Null has start = 1. Other values could lead to null not loaded at boot.

The right fix would be to find out what caused it and and eliminate that cause.

**Comment by KVPV** [comment]
Thanks, problem is solved!
