### ISSUE TITLE
openvpn-gui client do not connect server

### ISSUE THREAD

**Issue by 422365613** [OpenVPN/openvpn-gui#479]
Hello, I have tested on both Win10 and Win7 systems, but I still can't connect. I don't know where the problem is, it was installed for the first time. Please look at it for me. Thank you very much
![20220305](https://user-images.githubusercontent.com/46477353/156805914-f3b4277f-f8c8-41ef-b008-54241eae19a0.PNG)
!

**Comment by selvanair** [comment]
Is there anything in the log file `C:\Program Files\OpenVPN\log\client.log`? You can use the "View Log" menu item to see the log or open it directly in notepad.

**Comment by selvanair** [comment]
Closing for lack of follow-up.
