### ISSUE TITLE
Import from Access Server doesn't send basic auth credentials

### ISSUE THREAD

**Issue by jacopotediosi** [OpenVPN/openvpn-gui#480]
#436 implemented the "Import from Access Server" feature.

As stated in the [OpenVPN WebAuth documentation](https://github.com/OpenVPN/openvpn3/blob/master/doc/webauth.md#basic-api), the client should send credentials using HTTP Basic Authentication.

[OpenVPN-GUI v11.26.0.0](https://swupdate.openvpn.org/community/releases/OpenVPN-2.5.5-I602-amd64.msi) (latest version available in the [OpenVPN "Community Downloads" webpage](https://openvpn.net/community-downloads/)) on Windows 10 seems not to send the Authorization header.

![image](https://user-images.githubusercontent.com/20026524/157290885-c9ce55c8-5d43-4f67-bb9c-ab69a358fae9.png)

**Comment by schwabe** [comment]
While not familiar with thatr specifric implementation, a lot of HTTP implemention only send the credentials after getting a 401 response. Have you have that the server sends a 401?

**Comment by jacopotediosi** [comment]
> While not familiar with thatr specifric implementation, a lot of HTTP implemention only send the credentials after getting a 401 response. Have you have that the server sends a 401?

You are right, the client sends a second request with the Authorization header if server replied with 401 and a "WWW-Authenticate: Basic" header to the first one.
Still, I'm not sure this should be the intended behaviour.

**Comment by selvanair** [comment]
> > While not familiar with thatr specifric implementation, a lot of HTTP implemention only send the credentials after getting a 401 response. Have you have that the server sends a 401?
> 
> You are right, the client sends a second request with the Authorization header if server replied with 401 and a "WWW-Authenticate: Basic" header to the first one. Still, I'm not sure this should be the intended behaviour.

I think that's how basic auth works -- see rfc 7523. The server responds with 401 (unauthorized) before the client sends the auth header. 
Anyway, the question is, does it work for you or are you running into some issue? If the latter it could be something other than not sending credentials.

**Comment by selvanair** [comment]
oops -- rfc 7235

**Comment by jacopotediosi** [comment]
Responding 401 and setting the WWW-Authenticate header, it works.
OpenVPN Connect V3 and many other clients immediately send the authorization header, so I leave this ticket open to let the maintainers decide if this is working as expected or not.

**Comment by selvanair** [comment]
We use wininet API and it seems to always wait for 401 and authentication header before retrying with the authorization header set. This is in spite of assigning the username and password in the request structure in advance.
It may be possible to force-send authorization in the first round by explicitly constructing the header and adding it, but that's ugly. I would leave this as is unless there is a real case where the round-trip hurts or someone knows a better way.
