### ISSUE TITLE
‘OPENSSL_INIT_LOAD_CONFIG’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by SunnyWjw** [OpenVPN/openvpn-gui#485]
When I compile this code, the compilation fails, prompting  
`
error: ‘OPENSSL_INIT_LOAD_CONFIG’ undeclared (first use in this function)
`

Here is the complete error message:
```

$ make
make  all-am
make[1]: Entering directory '/cygdrive/e/openvpn-gui-master'
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I.   -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=_WIN32_WINNT_VISTA -DWINVER=_WIN32_WINNT -municode -g -O2 -pedantic -Wall -Wextra -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
main.c: In function ‘wWinMain’:
main.c:290:3: warning: implicit declaration of function ‘OPENSSL_init_crypto’; did you mean ‘OPENSSL_init’? [-Wimplicit-function-declaration]
  290 |   OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, NULL);
      |   ^~~~~~~~~~~~~~~~~~~
      |   OPENSSL_init
main.c:290:23: error: ‘OPENSSL_INIT_LOAD_CONFIG’ undeclared (first use in this function)
  290 |   OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, NULL);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~
main.c:290:23: note: each undeclared identifier is reported only once for each function it appears in
main.c: In function ‘GetDllVersion’:
main.c:836:26: warning: cast between incompatible function types from ‘FARPROC’ {aka ‘long long int (*)()’} to ‘HRESULT (*)(DLLVERSIONINFO *)’ {aka ‘long int (*)(DLLVERSIONINFO *)’} [-Wcast-function-type]
  836 |         pDllGetVersion = (DLLGETVERSIONPROC)GetProcAddress(hinstDll,
      |                          ^
make[1]: *** [Makefile:579: main.o] Error 1
make[1]: Leaving directory '/cygdrive/e/openvpn-gui-master'
make: *** [Makefile:447: all] Error 2

```
![image](https://user-images.githubusercontent.com/11763317/158290898-59e50de4-711c-4b42-9275-3656ff66fc89.png)
![image](https://user-images.githubusercontent.com/11763317/158290957-49ee0b8b-cbbb-41a0-ba8f-7b1ba81c9d9c.png)

**I don't know how to fix this**
`

**Comment by selvanair** [comment]
It seems you are trying to build against an old version of OpenSSL that we do not support. OPENSSL_init_crypto() was added in OpenSSL version 1.1.0. We recommend OpenSSL 1.1.1 or OpenSSl 3.0 though 1.1.0 also may work.

**Comment by SunnyWjw** [comment]
### How can I import or install openssl？
I updated the version of openssl to 1.1.1, but there is still an error in the process of compiling, it prompts me: "Cannot find OpenSSL library".

![image](https://user-images.githubusercontent.com/11763317/158511854-7d38d0a1-4f6d-48a2-82b6-14cd8df3918d.png)
![image](https://user-images.githubusercontent.com/11763317/158511867-85af98f5-25d2-425a-867f-ade76c0fa134.png)

**Comment by SunnyWjw** [comment]
> It seems you are trying to build against an old version of OpenSSL that we do not support. OPENSSL_init_crypto() was added in OpenSSL version 1.1.0. We recommend OpenSSL 1.1.1 or OpenSSl 3.0 though 1.1.0 also may work.

I updated the version of openssl to 1.1.1, but still got an error during compilation.
Error :"Cannot find OpenSSL library"

**Comment by selvanair** [comment]
I don't build on cygwin but I think the instructions in BUILD.rst should work provided all required packages are in place. That is,
```
autoreconf -iv
./configure --host=x86_64-w64-mingw32
make
```
If the location of OpenSSL is not automatically detected due to missing pkg-config or non-standard installation, you will have to define OPENSSL_CRYPTO_LIBS and OPENSSL_CRYPTO_CFLAGS. See `./configure -- help`.

**Comment by SunnyWjw** [comment]
> 

I have installed all the necessary packages, but when
` ./configure --host=x86_64-w64-mingw32`
 it still prompts me that openssl is missing。

![image](https://user-images.githubusercontent.com/11763317/158536998-c39c8632-f536-44e5-8917-9ff0fd6e4fb8.png)

**Comment by cron2** [comment]
Hi,

On Wed, Mar 16, 2022 at 12:20:25AM -0700, SunnyWu wrote:
> I have installed all the necessary packages, but when
> ` ./configure --host=x86_64-w64-mingw32`
>  it still prompts me that openssl is missing???

This is cross-building, so you need to have cross-built openssl libraries.

Follow these steps:

https://community.openvpn.net/openvpn/wiki/BuildingUsingGenericBuildsystem

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by lstipakov** [comment]
Please note that you could (and I would say _should_, but someone may disagree :) build openvpn-gui using Visual Studio/CMake with vcpkg as a dependency manager. This is what we do when we make releases.

**Comment by selvanair** [comment]
> Please note that you could (and I would say _should_, but someone may disagree :) build openvpn-gui using Visual Studio/CMake with vcpkg as a dependency manager.
Though I do not build that way, I agree especially since OP is compiling on Windows (cygwin). But I couldn't find build instructions for MSVC to point to. We have to update BUILD.rst.

**Comment by SunnyWjw** [comment]
Solution：
1: Download the source code of [OpenSSL](https://www.openssl.org)
2: Compiling openssl with cygwin
```
cd /cygdrive/c/Users/sunny/Downloads/openssl-1.1.1n/openssl-1.1.1n
./config shared 
make
```
3: After compilation, the "libcrypto.dll.a" and "libssl.dll.a" files will be generated
4: Copy the dynamic library to the following directory
```
cp libcrypto.dll.a /lib/gcc/x86_64-w64-mingw32/11/
cp libssl.dll.a /lib/gcc/x86_64-w64-mingw32/11/
```
5: Copy include/openssl in the openssl source directory to the following location /usr/x86_64-w64-mingw32/sys-root/mingw/include/openssl
```
cp -r include/openssl  /lib/gcc/x86_64-w64-mingw32/11/
```
6: Compile by following openvpn's compilation instructions using cygwin

**Comment by SunnyWjw** [comment]
this issue has been resolved
