### ISSUE TITLE
Feature request: Numpad Enter key for OTP

### ISSUE THREAD

**Issue by gjrtimmer** [OpenVPN/openvpn-gui#488]
Dear OpenVPN team,

I've been using OpenVPN for a very long time. However I noticed a difference between the new UI and the previous one. I believe the previous one is called version: `2`. In the new UI I can enter my OTP code to connect to my office VPN with the numpad keys however the `Enter` key of the numpad does not word to confirm the OTP entry. However I just found out that the normal `Enter` key does work.

Feature request:
Could you make it possible to allow the `Enter` key of the numpad to work like the normal `Enter` key so that after typing my OTP code I just press the `Enter` on my Numpad like my muscle memory is trying to do.

This might be a very simple feature request but I'm sure it greatly improve the usability of the OpenVPN UI.

I hope the team will consider this feature request.
With regards,
Gert-Jan (Garrett) Timmer

---
Screenshot of where the Numpad `Enter` key is not working.
![image](https://user-images.githubusercontent.com/6072255/161181429-2e9af30c-c0eb-4f2c-9328-9d6d8d0e5133.png)

**Comment by selvanair** [comment]
OpenVPN Connect is a commercial product, while this site is about OpenVPN-GUI for Windows which is a free, open source  project. Please report this issue to where you received OpenVPN Connect from.
