### ISSUE TITLE
anyone interested in password save?

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn-gui#49]
Ref: https://github.com/selvanair/openvpn-gui/tree/save-pass
The above link is to a cleaned up version of a feature we use locally -- option to save private key and user-auth passwords (username is always saved). If more than one person is interested in this feature I'll post a PR here.  @chipitsine has already asked for it.
Thanks.

**Comment by EagleErwin** [comment]
I would be interested in a password save option.

**Comment by selvanair** [comment]
Thanks for your interest. If you want to test run it a 64 bit executable is here: 
https://github.com/selvanair/openvpn-gui/releases/download/11.0_save-pass/openvpn-gui-save-pass-64.exe

It has no dependency, so should run without installation.

**Comment by chipitsine** [comment]
![pt](https://cloud.githubusercontent.com/assets/2217296/15498009/46fce1f8-21bf-11e6-83c7-5f3882451e1c.png)

it shows PT instead of EN, can you please merge this patch https://github.com/OpenVPN/openvpn-gui/pull/45 ?

as for password save, it works great.
However, I'd skip dialog at all if connect (with saved password) was successful, and show dialog only if authentication failed.

I'll try to patch that.

**Comment by selvanair** [comment]
The language error should not be there any more --- #45 was merged more than 10 days ago.

> as for password save, it works great.
> However, I'd skip dialog at all if connect (with saved password) was successful, and show dialog only if authentication failed.

The private key dialog is skipped is password is available. I am not keen on doing the same for user-auth as it provides an easy access to stop saving the password. Else separate buttons for deleting each kind of saved passwords would be needed. Will think about it.

**Comment by chipitsine** [comment]
https://github.com/selvanair/openvpn-gui/blob/save-pass/res/openvpn-gui-res-pt.rc#L130 - "ENGLISH" is still there

**Comment by selvanair** [comment]
Oh, you are referring to my private branch save-pass? That will automatically get the commits in  PR#45 if/when merged upstream. It was rebased to master before PR#45 was merged. Unless changes in it conflicts with upstream no urgent need to rebase.

**Comment by chipitsine** [comment]
it is merged already, we can close this issue
