### ISSUE TITLE
Multiple VPN's in a go

### ISSUE THREAD

**Issue by hellcry37** [OpenVPN/openvpn-gui#498]
Hello,

I am using openvpn from some time now. I work on windows 10 and use openvpn-gui with --connect option

What I want to do is connect 2 vpn's at start so I edited the shortcut when I lunch it it connects both vpn's, but only is openvpn-gui is not already started.

for example:

I use "C:\Program Files\OpenVPN\bin\openvpn-gui.exe" --command connect vpn1 --command connect vpn2 both vpn connect correctly only if openvpn-gui is not started in windows sys try.

If openvpn-gui is started in windows sys try then one vpn get's connected and one does not (is totally ignored)

same for this:
"C:\Program Files\OpenVPN\bin\openvpn-gui.exe" --connect vpn1.ovpn --connect vpn2.ovpn

Windows 10
OpenVPN 2.5.5 x64

**Comment by hellcry37** [comment]
forum discussion: https://forums.openvpn.net/viewtopic.php?p=106668

**Comment by selvanair** [comment]
When the GUI is running, the second instance is sending commands to it, and only one command per invocation is supported. Its meant to be used from scripts. For interactive uses one is expected to start the GUi using the shortcut only when the GUI is not running. Use the GUI menu when its running.

Here is a possible workaround (untested): write a small batch script as:

cd "C:\Program Files\OpenVPN\bin"
start /B openvpn-gui.exe --connect vpn1
timeout /t 2 /nobreak
start /B openvpn-gui.exe --connect vpn2
start /B openvpn-gui.exe --connect vpn3

Make a short-cut to this batch file, configure it to start minimized and add an icon.

The timeout is required for cases when it is used with the GUI not running. It takes some time for the GUI to come up and ready to accept commands from a second instance. You may have to tweak the 2 second value above. 

Also, this may not work reliably if you have warnings during start up (like duplicate configs) which will delay the startup and thus lose the second command.

**Comment by hellcry37** [comment]
thanks for your replay and help, still I'll leave this here maybe it will get fixed sometime

**Comment by hellcry37** [comment]
I see you guys working on this, thank you very much. This is awesome!

**Comment by hellcry37** [comment]
tested and seem to work ok when gui is already lunched both vpn's connect, awesome work
