### ISSUE TITLE
Support numerical ENTER key when typing a multi-factor authentication code 

### ISSUE THREAD

**Issue by peterpoliwoda** [OpenVPN/openvpn-gui#499]
Hi there,
I'd like to add the ability to press the return key when typing in a 2FA code when switching the app on. 

![image](https://user-images.githubusercontent.com/14016749/169778609-a2a835ed-35ae-46e0-8715-ea51ab3e7c75.png)

At the moment it only supports the standard RETURN key in the middle of the keyboard and not the numerical keyboard's ENTER key. When typing on the right-hand side of the keyboard, it feels strange that you can't just use the enter key closest to you.

![image](https://user-images.githubusercontent.com/14016749/169778369-41099169-6c5a-4153-9635-093a8dc481fe.png)

**Comment by schwabe** [comment]
The screenshots are from OpenVPN Connect, the commerical client from OpenVPN Inc. Please see [here](https://openvpn.net/vpn-server-resources/support-options-for-openvpn/#openvpn-connect-client-for-windows-and-macos) for support for them.
