### ISSUE TITLE
Import profile from URL works in OpenVPN Connect but not OpenVPN-GUI

### ISSUE THREAD

**Issue by CloudyDory** [OpenVPN/openvpn-gui#511]
I have purchased a VPN service which support connection by OpenVPN by importing a profile from URL. However it seems that importing from URL works only in OpenVPN-Connect client, not OpenVPN-GUI client, on Windows 10.

The verion of OpenVPN-GUI is v11.29.0.0, downloaded from [https://openvpn.net/community-downloads/](https://openvpn.net/community-downloads/). If I use "import from URL", after entering the URL, username and passward and click "OK", it will pop-up a window saying "`Error fetching profile from URL: [0] HTTP contet-type mismatch`". If I use "import from Access Server", entering the URL, username and passward and click "OK", it will pop-up a window saying "`Error fetching profile from URL: [401] HTTP error`".

I am not sure where the problem is. Is it a problem related to my VPN provider, or is there a bug in OpenVPN-GUI client? I think this issue (#480) might be relavent, but I am not sure.

**Comment by selvanair** [comment]
Looks like your VPN provider has set the content-type to something we do not recognize. Unrelated to #480.
Contact the provider and tell them to set content-type to application/x-openvpn-profile.  Connect client may not be requiring it, but we are enforcing it for generic URLs (not for access-server compliant ones). Quoting from the commit message:

```
To avoid input errors leading to download and import of arbitrary
web content, the content-type is required to be
application/x-openvpn-profile
```

Its also a good idea to set content-disposition so that the profile can be imported with a custom filename, though not required.

**Comment by bdalkhbyrghazy1-bit** [comment]
> به نظر می‌رسد ارائه‌دهنده VPN شما نوع محتوا (content-type) را روی چیزی تنظیم کرده که ما نمی‌شناسیم. ربطی به [#480](https://github.com/OpenVPN/openvpn-gui/issues/480) ندارد . با ارائه‌دهنده تماس بگیرید و به آنها بگویید که نوع محتوا را روی application/x-openvpn-profile تنظیم کنند. ممکن است کلاینت Connect به آن نیازی نداشته باشد، اما ما آن را برای URLهای عمومی (نه برای URLهای سازگار با access-server) اجباری می‌کنیم. به نقل از پیام commit:
> 
> ```
> To avoid input errors leading to download and import of arbitrary
> web content, the content-type is required to be
> application/x-openvpn-profile
> ```
> 
> همچنین ایده خوبی است که content-disposition را طوری تنظیم کنید که بتوان پروفایل را با یک نام فایل سفارشی وارد کرد، هرچند که الزامی نیست.

az2-4030
