### ISSUE TITLE
[Feature consideration] Add `Openvpn version` to GUI interface

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/openvpn-gui#526]
**Just a thought**: Sometimes `openvpn` is aborted prior to logging the version info. It _could_ be useful to have a GUI menu item: `Openvpn version`

**Edit**: Apparently, having `openvpn` always log the version has also been discussed and is being considered, i guess ..

**Comment by selvanair** [comment]
> Sometimes openvpn is aborted prior to logging the version info. 

As in  aborted during option parsing? In fact, the GUI reads the version of installed openvpn.exe binary at startup and saves it as o.ovpn_version --- could be *easily* added it to the about page. Patches welcome.

**Comment by selvanair** [comment]
Implemented in PR #536
