### ISSUE TITLE
Use certificate from Windows machine certificate store

### ISSUE THREAD

**Issue by feuertaenzer** [OpenVPN/openvpn-gui#528]
I am not sure if this is a bug or feature request.
Based on my research this was possible at some point but it isn't anymore so I consider this a bug, correct me if I'm wrong.

I use Windows 10 Clients with the OpenVPN GUI 64bit version 2.5.7.
Also I use automatically enrolled client certificates, stored in the machine certificate store.
These certificates are supposed to be the second factor next to username+password.

In the OpenVPN config(see config below) I use cryptoapicert to use the certificates from the Windows client certificate store but for some reason OpenVPN doesn't use the machine certificate store.

When I run OpenVPN as administrator it does use the machine certificate store, picks the correct certificate and everything works like a charm but of course giving every user these priviledges is not an option. This test makes me think it's a issue with permissions though.

From what I've seen, OpenVPN has a service running in system context to perform certain tasks with higher priviledges, shouldn't be accessing the machine certificate store be possible with this?
Also I've found super old postings describing that this used to work.

`dev tun
persist-tun
persist-key
data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305:AES-256-CBC
data-ciphers-fallback AES-256-CBC
auth SHA256
tls-client
auth-nocache
client
resolv-retry infinite
remote X.X.X.X 1194 udp4
nobind
verb 3
auth-user-pass
remote-cert-tls server
explicit-exit-notify
cryptoapicert "SUBJ:XXX"
<ca>
-----BEGIN CERTIFICATE-----
...certificate
-----END CERTIFICATE-----
</ca>`

Kind regards

**Comment by selvanair** [comment]
OpenVPN.exe runs with limited user privileges and certificate in machine store is read only if its readable by user -- certificates are accessed directly, not using the service. You can explicitly run the GUI and thus openvpn.exe as administrator, but that'snot recommended. 

Client certificate is supposed to be issued to the user, so make it user readable (key can be kept non-exportable). If that is not acceptable, you can start the connection using the automatic service at boot, and then let user(s) control it using the GUI. The GUI from next release on has support for "controlling" such pre-started connections (see PR #512). Its less secure than starting the process from the GUI, but if you must keep certificates not user readable, go for it.

In the interest of keeping privileged code minimal, the interactive service handles only those tasks that must absolutely need administrator or system privileges. I do not consider signing with client certificates a privileged operation.

>Also I've found super old postings describing that this used to work.

The only time it could have worked is in the pre-interactive-service days, when OpenVPN-GUI had to be run as admin.

**Comment by feuertaenzer** [comment]
Okay thanks for the clarification.
I was pretty focused on using machine certificates but I'll then use user certificates with non-exportable private keys instead!

**Comment by selvanair** [comment]
For connections profiles stored in the global config directory, certificate in machine store may be preferred so that different users can start the connection. For those in the user-specific config folder, storing the certificate in user store is better. In either case, if you can keep the key accessible by users (not exportable), it will work.
