### ISSUE TITLE
Version update commit for the GUI

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn-gui#535]
@mattock version and tag for 2.5.8 release appears to be not pushed here as yet..

**Comment by cron2** [comment]
Hi,

On Fri, Nov 04, 2022 at 08:43:12AM -0700, Selva Nair wrote:
> @mattock @cron2 
> In fact the 2.5.8 release appears to have issues;
> openvpn.exe shows version as 2.5.7 -- it seems last two commits in 2.5.8 (Including version bump) are missing.

This comes as a bit of surprise to me - my understanding of the 
dark and mystical ways to brew a windows release was "mattock fills
in a git tag, and it builds exactly this" - so it should have built
v2.5.8.

More interesting question - what is in the tarballs published?

(I do "update version.m4, commit, tag+sign that commit, push", mattock and
now djpig do "formal tarball and windows installer based on that")

gert


-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***
