### ISSUE TITLE
Critical security oversight Openvpn-Connect 

### ISSUE THREAD

**Issue by fennectech** [OpenVPN/openvpn-gui#542]
ive been using the openvpn connect client to torrent but found that its not showing the amount of traffic the torrent client is using   however the IP displayed in the corner is indeed the IP of the vpn  So after a bit of testing ive found that ipv6 traffic is going arround the VPN and googling "what is my ip" with the client connected actually shows my public IPV6 address but if i force ipv4 it shows the address of the vpn provider.   This means that openvpn connect is not blocking ipv6 traffic at all which is in my eyes a critical privacy impacting vulnerability. 

I am running windows 11  
the UUID in openvpn connect 4C4C4544-0056-5710-8046-B4C04F374433
Profile for VPN is here https://freevpnme.b-cdn.net/FreeVPN.me-OpenVPN-Bundle-July-2020.zip   Please look into this as soon as possible   if you need any more information let me know

**Comment by fennectech** [comment]
![image](https://user-images.githubusercontent.com/11953665/201279276-19a01d0f-98bf-4783-946d-33aba38bd34d.png)

**Comment by cron2** [comment]
Hi,

On Thu, Nov 10, 2022 at 10:39:37PM -0800, FennecTECH wrote:
> ive been using the openvpn connect client to torrent but found that its not showing the amount of traffic the torrent client is using   however the IP displayed in the corner is indeed the IP of the vpn  So after a bit of testing ive found that ipv6 traffic is going arround the VPN and googling "what is my ip" with the client connected actually shows my public IPV6 address but if i force ipv4 it shows the address of the vpn provider.   This means that openvpn connect is not blocking ipv6 traffic at all which is in my eyes a critical privacy impacting vulnerability. 

This is not a bug in OpenVPN Connect, but in your VPN setup.

Your VPN provider needs to either offer IPv6, or put "block-ipv6"
into the VPN config (to prevent IPv6 from circumventing the VPN,
as you have observed).  Specifically:

              Client config

                        --ifconfig-ipv6 fd15:53b6:dead::2/64 fd15:53b6:dead::1
                        --redirect-gateway ipv6
                        --block-ipv6

("give the tun interface some IPv6, redirect all routing into the tunnel,
and then reject all IPv6")

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by fennectech** [comment]
you are correct!
