### ISSUE TITLE
Visual Studio 2022 not found

### ISSUE THREAD

**Issue by bjoernv** [OpenVPN/openvpn-gui#543]
The build instructions in BUILD.rst formulate carefully that Visual Studio 2022 may be supported ("Visual Studio 2019 (build tools should be enough, also 2022 will likely work)").

I tested the build instructions with Visual Studio 2022 and the master version of OpenVPN-GUI and the build fails.

In the first run a missing component "Desktop Development with C++" (see [Visual Studio 16 2019: Could not find any instance of visual studio flutter](https://stackoverflow.com/questions/70554827/visual-studio-16-2019-could-not-find-any-instance-of-visual-studio-flutter])) probably caused the build failure.

But also the second run failed with the error "Visual Studio 16 2019 could not find any instance of Visual Studio.":

```
C:\Users\myuser\Documents\openvpn-gui>cmake -S . --preset x64-release-ossl3
Preset CMake variables:

  CMAKE_BUILD_TYPE="Release"
  CMAKE_TOOLCHAIN_FILE:FILEPATH="C:\dev\vcpkg/scripts/buildsystems/vcpkg.cmake"
  VCPKG_MANIFEST_DIR="C:/Users/myuser/Documents/openvpn-gui/vcpkg_manifests/openssl_3"

-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
All requested packages are currently installed.
Restored 0 package(s) from C:\Users\myuser\AppData\Local\vcpkg\archives in 338.5 us. Use --debug to see more details.
Total install time: 378.7 us
json-c provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(json-c CONFIG REQUIRED)
    target_link_libraries(main PRIVATE json-c::json-c json-c::json-c-static)

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

-- Running vcpkg install - done
CMake Error at CMakeLists.txt:9 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/Users/myuser/Documents/openvpn-gui/out/build/x64-release-ossl3/CMakeFiles/CMakeOutput.log".
```

**Comment by lstipakov** [comment]
I haven't tested VS2022 myself, I can look into in next week. Does it work if you replace `Visual Studio 16 2019` with `Visual Studio 17 2022`?

**Comment by chipitsine** [comment]
Lev is right, replacing works (for me)

https://github.com/OpenVPN/openvpn-gui/blob/master/CMakePresets.json#L8

I tried to find a way how to detect that automatically, but I did not
