### ISSUE TITLE
"password change disable" feature

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-gui#57]
I do not lnow any case when openvpn-gui is compiled with that feature defined.
do we really need it?

and, if we do, should I add couple of configuration to travis-ci?

**Comment by selvanair** [comment]
@chipitsine : Its a useful feature to be able to build without openssl, so I think we should keep it. And make it even easier to use by fixing the unconditional check on openssl that you pointed out.

**Comment by chipitsine** [comment]
so, I should expand build matrix in travis-ci, right?

**Comment by selvanair** [comment]
Yes, that may be useful.

**Comment by chipitsine** [comment]
ok, that makes sense.

I'll do another PR after this one https://github.com/OpenVPN/openvpn-gui/pull/50 is merged
