### ISSUE TITLE
Release download doesn't include all files

### ISSUE THREAD

**Issue by res0nance** [OpenVPN/openvpn-gui#585]
On the website https://build.openvpn.net/downloads/releases/openvpn-gui-11.tar.gz is available but inside the tarball it is missing resource.h so users who download it will be met with a broken build.

**Comment by res0nance** [comment]
@selvanair Thanks, the cause of the issue has been fixed. But the package that is still downloadable remains broken

**Comment by flichtenheld** [comment]
Yes, it will be refreshed on next OpenVPN release next week.
