### ISSUE TITLE
No server certificate verification method has been enabled.

### ISSUE THREAD

**Issue by xuroka** [OpenVPN/openvpn-gui#588]
I have no idea what is going on, but OpenVPN stopped working properly a few days ago.
![OpenVPN](https://user-images.githubusercontent.com/120301330/213692905-0522b0de-ba45-4dd2-b267-25fbfc795119.png)
Please help!

**Comment by cron2** [comment]
Indeed, what Arne says.  This warning message states that the OpenVPN profile you is not scrutinizing the server it's connecting to very thoroughly, like requiring a special certificate name, "only server certificates" flag, etc - but warnings created by use of configs that someone else provided are fully outside the realm the OpenVPN developers are capable and willing to assist with.
