### ISSUE TITLE
OpenVPN-2.6.0-I001 - Not installed!

### ISSUE THREAD

**Issue by EmmettF17** [OpenVPN/openvpn-gui#594]
![изображение](https://user-images.githubusercontent.com/111609341/214875223-6747049a-b28d-4879-901e-2375a3e93e64.png)
Windows server 22

**Comment by EmmettF17** [comment]
on windows 11 installed without problems

**Comment by lstipakov** [comment]
Yes thanks, we're aware. A new version is coming with the fix.

**Comment by lstipakov** [comment]
@EmmettF17 does this https://build.openvpn.net/downloads/releases/OpenVPN-2.6.0-I003-amd64.msi fix the problem?

**Comment by EmmettF17** [comment]
> @EmmettF17 does this [https://build.openvpn.net/downloads/releases/OpenVPN-2.6.0-I003-amd64.msi ](https://build.openvpn.net/downloads/releases/OpenVPN-2.6.0-I003-amd64.msi) fix the problem?

yes
