### ISSUE TITLE
v2.6.0 on Windows 11: Nothing happens when you click `Connect` or `Disconnect` in system tray icon menu

### ISSUE THREAD

**Issue by jdrch** [OpenVPN/openvpn-gui#597]
Noticed the above behavior just now. If you right-click the system tray icon and then click `Connect` (when currently disconnected) or `Disconnect` (when current connected) nothing happens. The workaround is to double-click the icon to raise the main window and then use the `Connect` and `Disconnect` buttons there.

**Comment by selvanair** [comment]
Are you using the updated release (I003)? See here: https://openvpn.net/community-downloads/
Ufortunately, the earlier version I001 was buggy.

**Comment by jdrch** [comment]
Fixed in `I003`, thanks!
