### ISSUE TITLE
Open VPN preventing Windows 10 to start when autoconfig is set up

### ISSUE THREAD

**Issue by yvan3869** [OpenVPN/openvpn-gui#602]
Hello, as my title says, I set up an auto-config and everything just worked fine when I log out ; I saw the ovbn button on the logon screen, and then vpn connection was ok, before connection to my domain, and after in session mode.

But when I reboot my Dell, Windows stuck at startup. So I had to remove the config files in safe mode to be able to go back in my system....bye bye Pre logon access...

Anyone having an idea? I'm using OpenVPN 2.6 with Windows 10 22H2 (19045.2546)

thanks

**Comment by cron2** [comment]
Hi,

On Tue, Feb 07, 2023 at 06:31:53AM -0800, yvan3869 wrote:
> Hello, as my title says, I set up an auto-config and everything just worked fine when I log out ; I saw the ovbn button on the logon screen, and then vpn connection was ok, before connection to my domain, and after in session mode.
> 
> But when I reboot my Dell, Windows stuck at startup. So I had to remove the config files in safe mode to be able to go back in my system....bye bye Pre logon access...

"Dell" suspiciously sounds like 

  https://github.com/OpenVPN/ovpn-dco-win/issues/24

can you please try the I004 installer

  https://build.openvpn.net/downloads/releases/OpenVPN-2.6.0-I004-amd64.msi

this should fix all boot issues with Dell laptops and ovpn-dco.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by yvan3869** [comment]
Thank you cron2, indeed it really fixed the problem!
