### ISSUE TITLE
VPN not used for accessing folder shares (samba)

### ISSUE THREAD

**Issue by Entretoize** [OpenVPN/openvpn-gui#603]
Hello, I created a samba folder share on a linux server, and installer openvpn server on the same server.
The share is limited to local ip so I can only acces it though a vpn.

I tested with the android openvpn client and it work perfectly which means the server configuration is ok, but on windows the acces is rejected and on my server log I see the computer IP instead of the vpn one. As I checked in a browser that the server IP replaces my computer one when I access whatismyipaddress.com for example, I understand that OpenVPN GUI is working for HTTP but not for SMB.

Is it true or is there a setting I can change somewhere ? Is it a bug ?

Thanks

**Comment by selvanair** [comment]
Recently there was a similar report and some discussion that may help you troubleshoot this further. It started out as a routing question, but one issue was smb traffic bypassing the tunnel. See [this](https://www.mail-archive.com/openvpn-users@lists.sourceforge.net/msg06478.html), and the corresponding thread in openvpn-users mailing list.
