### ISSUE TITLE
Unable to connect to openvpn with the new openvpn-gui version

### ISSUE THREAD

**Issue by Guigz25** [OpenVPN/openvpn-gui#605]
Hi there, 

I setup an OpenVPN/PKI architecture for my company. Everything worked perfectly fine with the openvpn-gui 2.5.8
Unfortunately I'm unable to connect to my infrastructure with the version 2.6.0

Here is the errors on the log file : 
TUN: adding address failed using service: Élément introuvable.   [status=1168 if_index=61]
TUN: setting IPv4 mtu using service failed: Élément introuvable.   [status=1168 if_index=61]
Warning: route gateway is not reachable on any active network adapters: 10.8.1.1
ERROR: Some routes were not successfully added. The connection may not function correctly
Connection reset, restarting [-1]

`client
dev tun 
proto tcp

remote x.x.x.x 443
remote x.x.x.x 443

resolv-retry infinite

ca ca
cert xxxxxxxxxx
key xxxxxxxxxxx.key

remote-cert-tls server
tls-auth xxxxxxxxxxxxx 1

replay-persist file
data-ciphers AES-256-GCM:AES-128-GCM
cipher AES-256-GCM
auth SHA256

verb 3

#################################################
#
route x.x.x.x x.x.x.x net_gateway
#
route x.x.x.x x.x.x.x net_gateway
#
route x.x.x.x x.x.x.x net_gateway
#################################################`

I can't find any solution to this problem. 

Thanks in advance.

**Comment by schwabe** [comment]
Please do not post the same issue over multiple repositories. You also have this posted as https://github.com/OpenVPN/openvpn/issues/249
