### ISSUE TITLE
Running command "disconnect_all" removes tray icon from taskbar

### ISSUE THREAD

**Issue by Markus74a** [OpenVPN/openvpn-gui#607]
I'm running Windows 11 22H2 and just switched from `OpenVPN-2.5.8-I604-amd64.msi` to the newest version `OpenVPN-2.6.1-I001-amd64.msi`. I often have multiple VPN connections open which I want to close all at once. 

Therefore, I execute: `"C:\Program Files\OpenVPN\bin\openvpn-gui.exe" --command disconnect_all`

- With `2.5.8-I604`, this command only disconnected all currently active OpenVPN connections.
- With `2.6.1-I001`, this command also does the disconnect, but it **additionally** removes the OpenVPN-GUI tray icon from the Windows 11 taskbar, while the `openvpn-gui.exe` process keeps running in the background.

Now I can't access the GUI any more since its tray icon is missing and I can't start the GUI again since it is detected as already running.

**Comment by selvanair** [comment]
A fix is in PR #608

> Now I can't access the GUI any more since its tray icon is missing and I can't start the GUI again since it is detected as already running.

When tray goes missing, you can do "openvpn-gui.exe --command exit" to terminate the GUI and then start again. Sorry for the trouble.
