### ISSUE TITLE
GUI opens with Error, even though connection works.

### ISSUE THREAD

**Issue by MySurmise** [OpenVPN/openvpn-gui#609]
Hey!

I am starting my Connection with the following command: 
&"C:\Program Files\OpenVPN\bin\openvpn-gui.exe" --command connect openvpn --silent_connection 1 --show_balloon 0 --show_script_window 0 --disable_popup_messages

I tried to include everything that could potentially mean "hide GUI" but at the end of the connection there is an error that will still force the window to show:
Tue Mar 14 03:38:04 2023 ERROR: Some routes were not successfully added. The connection may not function correctly

Is this really a critical error? The connection works...
And if yes, is there a possibility to keep the GUI closed even when there are critical errors?

my config looks like this (Cyberghost VPN)

```
client
remote 87-1-de.cg-dialup.net 443
dev tun 
proto udp
auth-user-pass


resolv-retry infinite 
redirect-gateway def1
persist-key
persist-tun
nobind
cipher AES-256-CBC
auth SHA256
ping 5
ping-exit 60
ping-timer-rem
explicit-exit-notify 2
script-security 2
remote-cert-tls server
route-delay 5
verb 4


ca ca.crt

cert client.crt

key client.key
```

**Comment by selvanair** [comment]
> Tue Mar 14 03:38:04 2023 ERROR: Some routes were not successfully added. The connection may not function correctly
> Is this really a critical error? The connection works...

The error means one or more routes pushed by the server could not be set. Post your client logs to see which routes failed and then you may know how critical they are.
 
> And if yes, is there a possibility to keep the GUI closed even when there are critical errors?

No.
But you could add "pull-filter ignore ...." to ignore unwanted push directives from the server, and thus eliminate the error. Depends on how important those failed routes are and why they are failing.
