### ISSUE TITLE
on eliminating some registry keys

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn-gui#61]
I am looking into simplifying user configurable  parameters (registry keys, command line options) and propose to eliminate these:

- passphrase_attempts: currently limited to a single digit > 0 (i.e 1 to 9). It forces the user to restart the connection after that many attempts which doesn't appear to serve any purpose.  It also complicates the code (had to be worked around to support dynamic challenge, for example) and adds another registry entry for little gain.
- allow_password: this controls whether the change-password menu is shown with no regard to whether user has write access to the key file or not. Instead, we can check the file access for each key and show the menu if appropriate for a better user experience and one less registry key.
- allow edit: let the user always view the config file (or edit if permissions allow)
- disconnect_on_suspend: not needed as we do not handle suspend/resume in the GUI anymore
- allow_proxy: always show the proxy settings tab
- editor and log_viewer: hard code to notepad.exe as a fallback and use file association to open config and log files. User keeps full control through associations.

If these keys will be missed by anyone please comment.

**Comment by mattock** [comment]
With keys now stored in HKCU for most users, the "authorization"-type registry keys (allow_*) don't really make much sense imho. I think all the changes you propose make sense.

**Comment by cron2** [comment]
Hi,

On Wed, Jul 06, 2016 at 12:33:23PM -0700, Selva Nair wrote:
> I am looking into simplifying user configurable  parameters (registry keys, command line options) and propose to eliminate these:

Feature-ACK.  I was not aware that these keys exist at all, and I assume
I share this with most if not all users of the gui...

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by mattock** [comment]
@selvanair: I tested a few things in the openvpn-gui.exe you linked to, and it seemed to work fine. I noticed that if no settings are changed, OpenVPN-GUI will use the (hardcoded) defaults instead of writing each key to the registry like it used to do. I this new behavior is reasonable, and it makes HKCU\Software\OpenVPN-GUI look nice and clean on a fresh install. I tested changing various options (log_append, config_ext, proxy_source...) and everything worked as expected, with keys and values appearing into the registry as expected.

I also tested connecting to two different VPNs before removing all OpenVPN-GUI registry keys (both HKLM and HKCU), and then afterwards removing them and launching OpenVPN-GUI again. In both cases things worked as expected.

**Comment by mattock** [comment]
The file association thing also works. I configured Notepad++ to be the default editor for .txt, .log and .ovpn, and after that OpenVPN-GUI opened logs and config files with Notepad++ as it should.

**Comment by selvanair** [comment]
@mattock Thanks for testing --- good to know it works as expected.  I'll do some clean up and add it to PR62 or submit a new PR for the settings dialog part. 

> I noticed that if no settings are changed, OpenVPN-GUI will use the (hardcoded) defaults instead of writing each key to the registry like it used to do. I this new behavior is reasonable, and it makes HKCU\Software\OpenVPN-GUI look nice and clean on a fresh install. I tested changing various options (log_append, config_ext, proxy_source...) and everything worked as expected, with keys and values appearing into the registry as expected.

Yeah, storing default values in the registry is superfluous and makes upgrades harder. This way its also easy to change the defaults in an upgrade without having to do anything special. 

The rationale for defining all options in the registry was probably to assist users who edit the registry and as a way of documenting the options.  With the settings dialog available we don't  need this and registry may be rightfully treated as a private store for the app not meant to be edited by the user.

**Comment by cron2** [comment]
Hi,

On Wed, Jul 13, 2016 at 06:20:23PM -0700, Selva Nair wrote:
> Apart from the PR 62 that implements the above, I have made a patch that allows all options to be set from the settings dialog. With this we'll need to store only user-edited options in the registry making it much easier to handle updates. 

I like this :-) - so, feature-ACK.

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by selvanair** [comment]
The feature discussed here is now merged into master. Closing.
