### ISSUE TITLE
Invalid SSL certificate error 

### ISSUE THREAD

**Issue by Relkci** [OpenVPN/openvpn-gui#611]
When the SSL certificate expires on the OpenVPN server specified by OpenVPN Client, the client correctly states that the certificate is invalid, but incorrectly reports that the certificate is self-signed, rather than correctly reporting the certificate is expired.

Client: OpenVPN v3.3.6
SSL Certificate: signed by trusted intermediary root CA
SSL Validity Expires on: previous date

![image](https://user-images.githubusercontent.com/29710634/225655654-4847e28c-cb2d-402a-80d1-3a603da022e2.png)

**Comment by lstipakov** [comment]
This repository is for openvpn-gui community client. You are using proprietary OpenVPN Connect. Unfortunately corporate folks refuse to monitor GitHub so you would need to submit a support ticket [here](https://support.openvpn.com/hc/en-us/requests/new).
