### ISSUE TITLE
How to select better host vpn?

### ISSUE THREAD

**Issue by dangdkhanh** [OpenVPN/openvpn-gui#616]
Hi, after activating Openvpn my connection seems still quite slow, after googling it seems i should choose connections with **low ping and high linespeed**.
My question is assuming I use the following host:
vpn728736015.opengw.net
118,241.69.102
it has pretty good parameters.
so have these hostnames changed? I mean after some time(a week, month..) I will have to download this .vpn file again and activate as it is?
Or I can use it for a long time without any problem..

Thanks you!

**Comment by lstipakov** [comment]
This is the issue tracker for openvpn-gui project. We are unable to assist you in choosing a VPN provider.

**Comment by dangdkhanh** [comment]
Hi @lstipakov , 
I would like to ask if these provided lists (host names) are random or are they fixed lists?
do they disappear after a while?

**Comment by selvanair** [comment]
As @lstipakov said, we do not know what you are talking about. This place is for reporting bugs and errors in OpenVPN-GUI software. VPN hosts and configurations are managed and provided by your VPN service provider. We have no way of assisting with what hostnames to use. Contact your VPN service provider or server administrator. 

Your question is like asking Microsoft whether the telephone numbers in a word file you received from your employer are random or fixed.

**Comment by dangdkhanh** [comment]
Hi,
sorry, I confused that web link providing that list hostname and openVPN are same source 
problem has been solved now.
