### ISSUE TITLE
[Request] Would like the numpad enter key to work when typing 2FA codes

### ISSUE THREAD

**Issue by roxas232** [OpenVPN/openvpn-gui#627]
Hi,

It would be nice to allow the numpad enter key to also trigger completion of passwords / 2FA codes since many of these are just a series of numbers anyway. Thanks!

**Comment by selvanair** [comment]
This is probably unrelated to OpenVPN-GUI. Does that key work like an "ENTER" key on other dialogs? I tested using an external number pad and ENTER key on it does  submit the username-password-OTP dialog.

**Comment by roxas232** [comment]
Hmm maybe OpenVPN Connect is something different than this and I am confused. Thanks anyway!

**Comment by selvanair** [comment]
If your issue is on Connect, this is the wrong place to report it. Closing.
