### ISSUE TITLE
"wrong credentials": after changing my password, the new one is not working

### ISSUE THREAD

**Issue by marcelatapajos** [OpenVPN/openvpn-gui#641]
I've recently changed my password to access OpenVPN_GUI (EBSCO plataform). But it returns the message "wrong credentials", although i'm typing it correctly (i've checked many times and it works in another computer, but not in mine). 

The report given by the app is:
Fri Jul 21 11:46:08 2023 OpenVPN 2.4.8 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Oct 31 2019
Fri Jul 21 11:46:08 2023 Windows version 6.2 (Windows 8 or greater) 64bit
Fri Jul 21 11:46:08 2023 library versions: OpenSSL 1.1.0l  10 Sep 2019, LZO 2.10
Enter Management Password:
Fri Jul 21 11:46:08 2023 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Fri Jul 21 11:46:08 2023 Need hold release from management interface, waiting...
Fri Jul 21 11:46:09 2023 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Fri Jul 21 11:46:09 2023 MANAGEMENT: CMD 'state on'
Fri Jul 21 11:46:09 2023 MANAGEMENT: CMD 'log all on'
Fri Jul 21 11:46:09 2023 MANAGEMENT: CMD 'echo all on'
Fri Jul 21 11:46:09 2023 MANAGEMENT: CMD 'bytecount 5'
Fri Jul 21 11:46:09 2023 MANAGEMENT: CMD 'hold off'
Fri Jul 21 11:46:09 2023 MANAGEMENT: CMD 'hold release'
Fri Jul 21 11:46:17 2023 MANAGEMENT: CMD 'username "Auth" "uc2017224976"'
Fri Jul 21 11:46:17 2023 MANAGEMENT: CMD 'password [...]'
Fri Jul 21 11:46:17 2023 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Fri Jul 21 11:46:17 2023 TCP/UDP: Preserving recently used remote address: [AF_INET]193.137.210.220:444
Fri Jul 21 11:46:17 2023 Socket Buffers: R=[65536->65536] S=[65536->65536]
Fri Jul 21 11:46:17 2023 UDP link local: (not bound)
Fri Jul 21 11:46:17 2023 UDP link remote: [AF_INET]193.137.210.220:444
Fri Jul 21 11:46:17 2023 MANAGEMENT: >STATE:1689950777,WAIT,,,,,,
Fri Jul 21 11:46:18 2023 MANAGEMENT: >STATE:1689950778,AUTH,,,,,,
Fri Jul 21 11:46:18 2023 TLS: Initial packet from [AF_INET]193.137.210.220:444, sid=852fd69c b744729f
**Fri Jul 21 11:46:18 2023 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this**
Fri Jul 21 11:46:18 2023 VERIFY OK: depth=1, CN=Easy-RSA CA
Fri Jul 21 11:46:18 2023 VERIFY OK: depth=0, CN=server
Fri Jul 21 11:46:18 2023 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Fri Jul 21 11:46:18 2023 [server] Peer Connection Initiated with [AF_INET]193.137.210.220:444
Fri Jul 21 11:46:20 2023 MANAGEMENT: >STATE:1689950780,GET_CONFIG,,,,,,
Fri Jul 21 11:46:20 2023 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
**Fri Jul 21 11:46:20 2023 AUTH: Received control message: AUTH_FAILED**
Fri Jul 21 11:46:20 2023 SIGUSR1[soft,auth-failure] received, process restarting
Fri Jul 21 11:46:20 2023 MANAGEMENT: >STATE:1689950780,RECONNECTING,auth-failure,,,,,
Fri Jul 21 11:46:20 2023 Restart pause, 5 second(s)
Fri Jul 21 11:47:21 2023 MANAGEMENT: Client disconnected
**Fri Jul 21 11:47:21 2023 ERROR: could not read Auth username/password/ok/string from management interface**
Fri Jul 21 11:47:21 2023 Exiting due to fatal error

I assume there's something to do with the change of passwords. Maybe the old one is "cached" somewhere... I hope anyone could help with solving this problem.

Tks

**Comment by selvanair** [comment]
If you are being prompted for a password it will get used, you can rule out any cached passwords. There are not many reasons for the password not to work on one client and not on another. If you have any non-ascii characters in the password sometimes Windows input could mangle them.

If you can upgrade to the latest version, we now have a password reveal feature and you can see what exactly is being input into the password field. If that's not an option, test by inputting the password into the username field to see what exactly is getting registered -- that may give a clue.

**Comment by cron2** [comment]
2.4.8 is really ancient.  I do remember that we had some issues with non-ASCII characters in windows builds in some places, and fixed all of it (that we are aware of) for 2.6.5...
