### ISSUE TITLE
Service> OpenThreadToken Access Denied

### ISSUE THREAD

**Issue by TheLaskY** [OpenVPN/openvpn-gui#667]
Hi there!

I'm coming up here with a pretty naughty thing.

I've got some users, nearly 10 all of them are on Windows 10, whose openvpn  GUI v2.5.9 worked a week ago, but now it give them this error:
``
Service> OpenThreadToken Access Denied
``

Obviously, i've tried opening OpenVPN as administrator, as another user, but this error won't go off.
On the little information i could gather, someone talked about antivirus, which i disabled for test purposes, but didn't help at all...

I also tried uninstalling it, with revouninstaller, but it gave nothing.
The only moment the users can mount the tunnel is by rebooting each time they close their tunnel.
Changing the config and log folder didn't helped either.

As you can see, i'm a little bit cornered, a little bit of help is very much pleased!

**Comment by GTihon** [comment]
Hello,

I've got the same error. I saw it can be due to BitDefender update (see https://forums.openvpn.net/viewtopic.php?t=43519). I've just updated my BitDefender and restarted my computer, and now it's working for me.
