### ISSUE TITLE
PLAP Auto Connection

### ISSUE THREAD

**Issue by hoo29** [OpenVPN/openvpn-gui#672]
Hello, I have the PLAP optional enabled and can connect to profiles at the Windows login screen. Is it possible to configure one to auto connect so I don't have to manually select it?

**Comment by selvanair** [comment]
Autoconnect at boot? If using username/password authentication, you will have to somehow provide them without user interaction. You could do that by adding a second parameter to `--auth-user-pass` in the config file like
`auth-user-pass <filename>`
where `<filename>` is a file that contains the username and password. The file will have two lines with username as line 1, password as line2.

**Comment by hoo29** [comment]
> Autoconnect at boot?

Yes, if possible before I have logged into windows. 

We have certificate authentication with the certs hardcoded (for now) into the ovpn file at `C:\Program Files\OpenVPN\config-auto` (it has a `--management 127.0.0.1 7987` entry). All I currently have to do is click the connect PLAP connect button on the windows login screen, and select the profile name.  It will say connected within a couple of seconds.

**Comment by selvanair** [comment]
If there are no passwords to be entered, it should get connected at boot without any need for interaction at PLAP screen. PLAP will not show it as connected until you click on it though, if that's what you mean.

IIRC, getting PLAP to automatically recognize that a profile is already connected had some issues. That said, would be nice if `someone` implements it without unwanted side effects :)

**Comment by hoo29** [comment]
Ah that is what I mean, I thought it might already be connected as clicking connect it was almost instantaneous to report success. Thank you for confirming!
