### ISSUE TITLE
OpenVPN GUI issue if use in several Windows user accounts

### ISSUE THREAD

**Issue by HombronHelmer** [OpenVPN/openvpn-gui#676]
I have installed OpenVPN 2.6.0 client (OpenVPN GUI 11.37.0.0) on a Windows 10 PC with two local user accounts (e.g. user A and user B)
If I connect (via OpenVPN GUI) from user A, then switch to user B (user A is still active and VPN connection made from user A is still active),  OpenVPN GUI is locked for user B: trayicon is not green though VPN traffic is available for user B; OpenVPN GUI menu looks like no connection is established, but if I try to establish connection I get error "All tap-windows6 adapters on this system are currently in use or disabled". Is there possibility to make OpenVPN GUI to be "common" for all local users?

**Comment by flichtenheld** [comment]
Looks to me like the question was answered
