### ISSUE TITLE
Minor Windows GUI flaw: white strip on 125% dpi

### ISSUE THREAD

**Issue by transcendreamer** [OpenVPN/openvpn-gui#678]
Not sure if this is right repo to post issues about OVPN Connect. Please delete my issue if I was wrong. 

The problem is: when Windows system scaling (DPI) is set to 125% GUI gets minor distortion: white strip on the right like on the screenshot. 100% and 150% scaling is OK.

![987647283](https://github.com/OpenVPN/openvpn-gui/assets/46658406/c33036b4-ba5f-4fcc-b3f6-14019c14041c)

**Comment by schwabe** [comment]
Use support.openvpn.net to report bugs with OpenVPN connect.
