### ISSUE TITLE
Can application split tunneling be supported?

### ISSUE THREAD

**Issue by user00036** [OpenVPN/openvpn-gui#684]

**Comment by cron2** [comment]
A bit more wording on what exactly you want, and on which platform, would be helpful.  My crystal ball is cloudy today.

**Comment by selvanair** [comment]
See #323.

**Comment by user00036** [comment]
> 参见 [#323 ](https://github.com/OpenVPN/openvpn-gui/issues/323) 。

Yes, that's exactly what I want. Just like what expressvpn provides
