### ISSUE TITLE
Reintroduce the private key password change feature

### ISSUE THREAD

**Issue by timolagus** [OpenVPN/openvpn-gui#686]
Please add back the private key password change feature removed in [version 11.40.0](https://github.com/OpenVPN/openvpn-gui/blob/master/CHANGES.rst#version-11400).

This was an extremely useful, security-conscious feature that allowed you to change the default passphrase of a private key created for you by someone else, such as a system administrator. I've relied on this feature for close to 10 years now.

If you cannot or will not reintroduce the feature, can you please explain why it was removed?

**Comment by selvanair** [comment]
Easiest alternative would be to select to install OpenSSL utilities in OpenVPN installer and use openssl.exe to change the key password. Not as user friendly as a menu item in the GUI, but still effective. User friendly option is to upload the certificate and key to the Windows store and use cryptoapicert option. Possibly more secure too.

The original feature worked in a limited set of situations where the key file is writeable by user and not inlined, so it was felt not worth having dependency on OpenSSL dll just for that.
