### ISSUE TITLE
Blurry eye icons when UI scaling is set

### ISSUE THREAD

**Issue by inelisoni** [OpenVPN/openvpn-gui#697]
Eye icons are blurry when UI scaling is set (125%, 150%, 175%, or even 200%).
I believe this is because icons are only available in 16x16 size. For example, tray icon is available in sizes of 16x16, 20x20, 24x24, and 32x32.

125%
![image](https://github.com/user-attachments/assets/0a2eb2af-059e-4f84-aa3c-1947307b1a5b)

150%
![image](https://github.com/user-attachments/assets/b4fb8bc8-3206-4711-9778-2e13d0d0eeb4)

175%
![image](https://github.com/user-attachments/assets/525f5845-0041-4afc-9009-c930eea9013a)

200%
![image](https://github.com/user-attachments/assets/6f962175-c819-497e-b5d1-965e6bb2467b)

**Comment by selvanair** [comment]
@inelisoni could you please test whether the GUI executable from the link below work better? https://github.com/selvanair/openvpn-gui/actions/runs/10030273814#artifacts

This one has eye icons with 16, 20, 24 and 32 bit variants.

**Comment by inelisoni** [comment]
Yes, it looks much better now. If necessary, I can provide screenshots.
