### ISSUE TITLE
OpenVPN service starts / auto connects properly on login, but tray icon does not show connected.

### ISSUE THREAD

**Issue by Samg381** [OpenVPN/openvpn-gui#703]
I have a VPN configuration in my `C:\Program Files\OpenVPN\config-auto` directory, and a shortcut to `openvpn-gui.exe` in `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp`. The result works properly, and I am able to access my remote drives after login.

However, despite the OpenVPN connection being active, and the service running, the tray icon does not appear as green:

![Screenshot 2024-09-14 125832](https://github.com/user-attachments/assets/b6925519-901a-4ee8-a1cc-f37a221fd865)

Right-clicking the tray icon to open the context menu reveals the option to connect, despite the connection already being active:

![Screenshot_1](https://github.com/user-attachments/assets/3486736b-84de-478c-bb81-70d346fc7ddc)

**Expected behavior:** after automatically starting on windows login, the OpenVPN GUI tray icon should appear as green when a connection is active.

**Theory:** this might have something to do with windows user accounts / privileges on login. Perhaps the OpenVPN service is being launched as a system service, while the GUI is being launched in user space, making them unable to communicate?

**Comment by selvanair** [comment]
A couple of things to check:
(i) See the section on persistent connections in README (https://github.com/OpenVPN/openvpn-gui?tab=readme-ov-file#persistent-or-pre-started-connections) and ensure the conditions stated there are satisfied -- in particular the `management` option in config file
(ii) Ensure that scanning for persistent connections is not disabled in General settings menu (Persistent connections option)
(iii) Ensure you **do not have an identically named config file** in other folders like global config directory or user's config directory -- what you see in the menu as disconnected may be a different config that is shadowing the one in config-auto.

Privileges should not matter -- as long as the GUI can read the config file and access its management interface, controlling it from the GUI should work.

**Comment by Samg381** [comment]
Thank you for your detailed response.

Regarding your suggestions:

1. I have `management 127.0.0.1 41000 mysecret.txt` in my config file, and a matching `mysecret.txt` file in the `C:\Program Files\OpenVPN\config-auto` directory.
2. Persistent connections is set to `auto` within my general settings menu.
3. I do not have any identically named (or any other, for that matter) config files in either  `C:\Program Files\OpenVPN` or `C:\Users\Sam\OpenVPN`

**Comment by selvanair** [comment]
This is odd. As all buttons except connect are grayed out the GUI is not treating this as a prestarted/persistent connection. Else the "show status" button will be active and you will be able to see what state its in -- even if the service has not started the connection the status window should show up and display that its waiting.

Only think I can think of is that you have set the config-auto folder as the global or user's config folder as well -- check the advanced tab of the GUI settings menu and see location of config folder (should be `C:\Users\username\OpenVPN\config` which is the default). Also check the registry key `HKLM\Software\OpenVPN\config_dir` -- should be `C:\Program Files\OpenVPN\config` which is the default. Do not point any of these to the location of the auto-config folder.

**Comment by Samg381** [comment]
> you have set the config-auto folder as the global or user's config folder as well -- check the advanced tab of the GUI settings menu and see the location of the config folder (should be C:\Users\username\OpenVPN\config which is the default)

That solved it! I had that parameter set to config-auto for some reason. After changing 'Folder' under 'Configuration files' within Advanced Settings to `C:\Program Files\OpenVPN\config` and saving/closing, the tray icon immediately turned green! Thanks!

Perhaps the menu UI could be tweaked to clarify this distinction- maybe renaming 'Folder' to 'Config Folder' or something.

Thanks a ton in any case!

**Comment by selvanair** [comment]
> Perhaps the menu UI could be tweaked to clarify this distinction- maybe renaming 'Folder' to 'Config Folder' or something.

Perhaps the confusion is the impression that controlling prestarted connections from the GUI is a hack. It is not, its a feature. It requires no manipulation of default paths. Or no need to give up the option of having GUI-started configs (as opposed to pre-started) in a global location.
