### ISSUE TITLE
Feature Request: Option to configure an alternative Config Editor

### ISSUE THREAD

**Issue by protogen** [OpenVPN/openvpn-gui#709]
In Windows, the default config editor is Notepad.  It is automatically launched when ```Edit Config``` is selected on the menu.

I would like the ability to configure an alternative editor (e.g. vim/gvim).  The alternative would be configured by defining a ```C:\path\to\alternative-editor-binary.exe```.

Below is an example of how this is done by [Rainmeter](https://www.rainmeter.net/).  This application defaults to Notepad but can be changed by browsing for a different editor binary.

![image](https://github.com/user-attachments/assets/6a07fd38-b838-4f44-9da0-e3cfb488e4b9)

![image](https://github.com/user-attachments/assets/b522590a-a5a4-4725-9d0b-3dafd8a0c16f)

**Comment by selvanair** [comment]
We use file associations for opening the config. The `open` verb is used and you can associate that for `.ovpn`  with an editor of choice. In the GUI notepad is only used as a fallback if no associations are defined.
But I'm not sure whether the installer messes up with  file associations

**Comment by protogen** [comment]
Thank you for the quick response.

I have changed the ```open``` association for ```.ovpn``` files to use vim/gvim.  Tested and working correctly.  Thank you!
