### ISSUE TITLE
[Feature Request] Authentik totp support

### ISSUE THREAD

**Issue by spanguel** [OpenVPN/openvpn-gui#713]
Hey, I want to use totp in combination with opnsense and Authentik
Authentik as the ldap and totp backend inside of opnsense.

The default ldap+totp configuration of Opnsense for Openvpn is having an ldap backend and getting the totp from inside opnsense's User Settings

I would like to have opnsense validating the password and the totp token against authentik.
The way they do it is having a user submit their password and token in the format of \<password>;\<token> (password and token separated by a semicolon)

When using Openvpn GUI with 'static-challenge "TOTP Code" 1' it prompts the user for a password and for a token. (thats how i want the users to be prompted)

Openvpn GUI now submits both in the format of \<totp>\<password>
What i want to have is either Openvpn GUI OR Authentik supporting the others default setting.
So in this case i would like to have an option to get the submitted format into <password>;<totp>

i requested the format (or rather format options) for Authentik here for reference: https://github.com/goauthentik/authentik/issues/12209

**Comment by selvanair** [comment]
> The way they do it is having a user submit their password and token in the format of <password>;<token>

This is not going to happen as there is no end to these kind of hacks. Ask "them" to support an existing protocol instead of inventing yet another one. See also discussion in #701.
