### ISSUE TITLE
The parameter is incorrect. [status=87 if_index=6]

### ISSUE THREAD

**Issue by BAXONnt** [OpenVPN/openvpn-gui#715]
I'm trying to register routes in OpenVPN, but in the end the client complains about one of them. I figured out which one.
Route to some youtube servers.
route 108.177.0.0 255.254.0.0
If you delete this line, the error disappears.
I don't understand what the client doesn't like about this route.

ERROR: route addition failed using CreateIpForwardEntry: The parameter is incorrect. [status=87 if_index=6]
ERROR: Some routes were not successfully added. The connection may not function correctly

A similar route with the same mask works fine:
route 104.134.0.0 255.254.0.0

Config:

client
resolv-retry infinite
nobind
remote xxx.xxx.xxx.xxx xxxxx
proto udp
dev tun
comp-lzo
ca ca.crt
cert yt.crt
key yt.key
remote-cert-tls server
tls-client
tls-auth ta.key 1
float
keepalive 10 120
persist-key
persist-tun
verb 0
tun-mtu 1500
mssfix 1620
route-nopull
route 108.177.0.0 255.254.0.0

**Comment by cron2** [comment]
255.254.0.0 is not a valid mask for a network with an odd number in the 2nd position (.177.)

Also, this is not a user help forum but a bug tracker.

*Also* this has nothing to do with the GUI, but is a basic OpenVPN config question.
