### ISSUE TITLE
"about" tab in GUI contains totally outdated text

### ISSUE THREAD

**Issue by cron2** [OpenVPN/openvpn-gui#81]
at least the german text shown by the gui in the "about" tab is really 10 years old, talking about copyright up to 2005...  didn't check other languages

**Comment by selvanair** [comment]
This is something we should update. I don't know enough of the history to properly phrase an updated copyright notice. For the GUI shall we add something like  copyright various contributors and link to the contributors page on github?
@mattock thoughts?

The current About page reads as
```
OpenVPN GUI v11 - A Windows GUI for OpenVPN
Copyright (C) 2004-2005 Mathias Sundman <info@openvpn.se>
http://openvpn.se/
OpenVPN - An application to securely tunnel IP networks
over a single UDP port, with support for SSL/TLS-based
session authentication and key exchange, packet
encryption, packet authentication, and packet compression.

Copyright (C) 2002-2005 OpenVPN Solutions LLC <info@openvpn.net>
http://openvpn.net/
```

**Comment by selvanair** [comment]
About page in English updated by PR 89 (already merged).
Updated copyright statements copied to all language files in PR 100 (pending review).

**Comment by selvanair** [comment]
Fixed by PR 100 (merged). Closing.
