### ISSUE TITLE
Warning about no configuration files found should include directory where they are expected

### ISSUE THREAD

**Issue by schwabe** [OpenVPN/openvpn-gui#82]
![image](https://cloud.githubusercontent.com/assets/1038539/18615831/1b561802-7db9-11e6-9634-f967d201ab94.png)

It would be nice to add the directory the user is expected to place config files, especially with the new per user config file directory.

**Comment by selvanair** [comment]
Good point. See [PR 84](https://github.com/OpenVPN/openvpn-gui/pull/84)

**Comment by selvanair** [comment]
Resolved by [commit 9ed9abe](https://github.com/OpenVPN/openvpn-gui/commit/9ed9abe)
