### ISSUE TITLE
OpenVPN GUI and OpenVPN Access Server

### ISSUE THREAD

**Issue by Lightah** [OpenVPN/openvpn-gui#83]
I'm using OpenVPN GUI connecting to a OpenVPN server. The server uses Google Authenticator OTP.

The client software never prompts me to enter the generated code.

Logging:
Sun Sep 17 21:06:11 2016 AUTH: Received control message: AUTH_FAILED,CRV1:R,E:F/xxxxxx+xxxxxxxxxxxxxxxxxxxxxxxx:Enter Google Authenticator Code
Sun Sep 17 21:06:11 2016 SIGUSR1[soft,auth-failure] received, process restarting
Sun Sep 17 21:06:11 2016 MANAGEMENT: >STATE:1474225571,RECONNECTING,auth-failure,,
Sun Sep 17 21:06:11 2016 Restart pause, 2 second(s)

**Comment by selvanair** [comment]
The GUI does not currently support dynamic challenge response.  I have an implementation that's waiting for some cleanup. If you want to try it out, see here:
https://github.com/selvanair/openvpn-gui/releases/tag/v11-dynamic-cr
The executable included is only for 64 bit windows. No special installation is needed, just copy to C:\Program Files\OpenVPN\bin\  and run.

**Comment by Lightah** [comment]
Thanks for your quick reply! I'll try if it works.

When do you expect to have it integrated in the official distribution?

**Comment by selvanair** [comment]
I hope to submit it as a PR soon. Some independent tests by users would help speed up that process. Also, so far there has been little user demand for supporting dynamic challenge-response. It looks like that is changing.

**Comment by mattock** [comment]
Once selvanair's PR is merged, the code will soon get into the [openvpn master snapshot installers](http://build.openvpn.net/downloads/snapshots/).

**Comment by selvanair** [comment]
Support for dynamic challenge response is now in PR #87 waiting for review. If anyone wants to test it an executable may be found [here](https://github.com/selvanair/openvpn-gui/releases/tag/v11-pkcs11-pin) .

**Comment by Lightah** [comment]
I have tested the executable in the link provided.
What I first found odd was it always shows a box to enter the Response code. But then I found out it also prompts when you leave it blank. Maybe it might be nice to make this behaviour an option which is default disabled. So default it then wouldn't show a Response code input when connecting but prompts when required. If enabling the option it always shows the Response code input.
Authenticating against a access server 2.1.2 worked perfectly. I tried most combinations of valid/invalid credentials and all worked as expected.
Great work, imo a far better alternative than the embedded client.

**Comment by selvanair** [comment]
@Lightah Thanks for the test report. 
> edit: wait I was wrong! It does take the challenge into account for (not) showing a Response code input box. All good

Glad to know it works.

Only if the config has "--static-challenge" will a response be prompted for along with username/password. Whereas dynamic challenge prompt is shown if/when the server responds with a challenge after auth-user-pass authentication. In most setups only one (either static or dynamic) will be in use so if you do not need static challenge leave it out of the config.
