### ISSUE TITLE
OpenVPN & pam_radius_auth - Dynamic CR

### ISSUE THREAD

**Issue by roberthunt-dm** [OpenVPN/openvpn-gui#92]
I am trying to get OpenVPN working with a Radius server configured to send an access_challenge for an otp code it dynamically generates.

(server) openvpn server 2.3.2-7ubuntu3.1
(client)  Openvpn-gui-cr.exe  

The big question mark for me is how pam_radius_auth interacts with Openvpn.  

Logs show that the plugin is receiving the code 11 access_challenge from the radius server:

Nov  3 15:30:21 openvpn openvpn[10910]: pam_radius_auth: Got user name xxxxxx
Nov  3 15:30:21 openvpn openvpn[10910]: pam_radius_auth: Sending RADIUS request code 1
Nov  3 15:30:21 openvpn openvpn[10910]: pam_radius_auth: Got RADIUS response code 11
Nov  3 15:30:21 openvpn openvpn[10910]: pam_radius_auth: Got response to challenge code 11
Nov  3 15:30:21 openvpn openvpn[10910]: pam_radius_auth: Got response to challenge code 3
Nov  3 15:30:21 openvpn openvpn[10910]: pam_radius_auth: authentication failed

However I don't see any pop-up box on the OpenVPN client prompting for the OTP code.  

On the radius server, for the 2nd access request message (in response to the access_challenge) - openvpn is just sending the same original access_request message.  The radius server then rejects access.  

Do I need to modify pam_radius_auth to send messages in a special format to openvpn?    I'm using this from here:  https://github.com/FreeRADIUS/pam_radius/blob/master/src/pam_radius_auth.c

**Comment by selvanair** [comment]
Discussion moved to openvpn-devel.

**Comment by chim1005** [comment]
roberthunt-dm

I have same question as you and wondering if there was any closure in openvpn-devel forum which I am not sure how to search properly.

Would you share any update on this?

Thanks.
-chang

**Comment by chim1005** [comment]
Thanks Selva for the comment.   

I also looked through OpenVPN source code and found that the plugin API supports returning data through "struct openvpn_plugin_string_list", but the caller verify_user_pass_plugin() passes NULL for that.

We already deployed our plugin implementation for user authentication and was looking for a way to extend it to support dynamic challenge and response.

It looks like we have two choices.  One is to re-implement user authentication through management interface using "management-client-auth" and the other is to patch opensource verify_user_pass_plugin() to accept challenge and pass back to client side the same way as management interface handler for "client-deny" does.

**Comment by selvanair** [comment]
Making the plugin return data is easy but getting it back to the client is not. The current way of sending back AUTH_FAILED reason during reneg is too closely tied to management-client-auth. See my comments on such a patch [here](https://patchwork.openvpn.net/patch/306/#656)

Still looking for a good way to get hold of context info required for calling send_auth_failed() from verify_user_pass().

**Comment by chim1005** [comment]
By the way, does management interface for user authentication support asynchronous response like plugin API does it with auth control file?

**Comment by selvanair** [comment]
Interaction with the management interface is asynchronous so think of management-client-auth as a deferred auth by default. On top of it you get things like client-id and whether the auth is first time or a reauth (ie., auth during reneg), ability to reject clients with a reason, features only available through the management. client-id allows one to refer to clients by a unique id where as common name need not be unique.
